import { issueReward } from "../crm";
import { getSettings } from "../settings";
import { isJalaliBirthday } from "../commerce-common";
import { and, desc, eq, inArray, isNotNull, ne, sql } from "drizzle-orm";
import { db } from "@/db";
import { centralBirthdaySms, centralLoyaltyMembers, settings, centralPosItems, centralPosSales, posTerminals, products, productVariants, stockMovements } from "@/db/schema";
import { requireApi, rateLimit } from "../auth";
import { audit } from "../audit";
import { postJournal, type Line } from "../accounting";
import { sendDirectSms } from "../sms";
import { genNumber, HttpError, int, str } from "../util";
import { body, type Route } from "./router";
import { consumeConsignmentLots, postConsignmentPayables } from "../services/inventory-accounting";

const normalizePhone = (v: unknown) => str(v, 20).replace(/[۰-۹]/g, d => String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).replace(/\D/g, "").replace(/^98/, "0").replace(/^9/, "09");
const parseBirthdate = (value: unknown) => { const raw=str(value,10); if(!raw)return null; const date=new Date(`${raw}T12:00:00.000Z`); if(!/^\d{4}-\d{2}-\d{2}$/.test(raw)||Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==raw)throw new HttpError(400,"تاریخ تولد معتبر نیست"); return date; };
const validCampaignDate = (value: string) => { const d=new Date(`${value}T12:00:00.000Z`); return /^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(d.getTime())&&d.toISOString().slice(0,10)===value; };
export const centralPosRoutes: Route[] = [
 { method:"GET", pattern:"admin/loyalty", handler:async()=>{await requireApi("SMS_MANAGE");return db.select().from(centralLoyaltyMembers).orderBy(desc(centralLoyaltyMembers.updatedAt)).limit(2000)}},
 { method:"POST", pattern:"admin/loyalty/members", handler:async(req,_p,meta)=>{const user=await requireApi("SMS_MANAGE"),b=await body(req),name=str(b.name,100),phone=normalizePhone(b.phone),birthdate=parseBirthdate(b.birthdate);if(!name)throw new HttpError(400,"نام مشتری الزامی است");if(!/^09\d{9}$/.test(phone))throw new HttpError(400,"شماره همراه معتبر وارد کنید");const [member]=await db.insert(centralLoyaltyMembers).values({name,phone,birthdate,smsConsent:b.smsConsent===true}).onConflictDoUpdate({target:centralLoyaltyMembers.phone,set:{name,...(birthdate?{birthdate}:{}),smsConsent:sql`${centralLoyaltyMembers.smsConsent} OR ${b.smsConsent===true}`,updatedAt:new Date()}}).returning();await audit(db,{userId:user.id,...meta},"admin.loyalty_member","central_loyalty_member",member.id,null,{name,phone,smsConsent:member.smsConsent});return{ok:true,id:member.id}}},
 { method:"POST", pattern:"admin/loyalty/members/:id/consent", handler:async(req,p,meta)=>{const user=await requireApi("SMS_MANAGE"),id=int(p.id,1),consent=(await body(req)).smsConsent===true;const [member]=await db.update(centralLoyaltyMembers).set({smsConsent:consent,updatedAt:new Date()}).where(eq(centralLoyaltyMembers.id,id)).returning();if(!member)throw new HttpError(404,"مشتری یافت نشد");await audit(db,{userId:user.id,...meta},"admin.loyalty_consent","central_loyalty_member",id,{smsConsent:!consent},{smsConsent:consent});return{ok:true}}},
 { method:"DELETE", pattern:"admin/loyalty/members/:id", handler:async(_req,p,meta)=>{const user=await requireApi("SMS_MANAGE"),id=int(p.id,1);const [member]=await db.delete(centralLoyaltyMembers).where(eq(centralLoyaltyMembers.id,id)).returning();if(!member)throw new HttpError(404,"مشتری یافت نشد");await audit(db,{userId:user.id,...meta},"admin.loyalty_member.delete","central_loyalty_member",id,member,null);return{ok:true}}},
 { method:"GET", pattern:"admin/loyalty/birthdays", handler:async(req)=>{await requireApi("SMS_MANAGE");const date=req.nextUrl.searchParams.get("date")??new Date().toISOString().slice(0,10);if(!validCampaignDate(date))throw new HttpError(400,"تاریخ مناسبت معتبر نیست");const people=await db.select().from(centralLoyaltyMembers).where(and(eq(centralLoyaltyMembers.smsConsent,true),isNotNull(centralLoyaltyMembers.birthdate))).orderBy(centralLoyaltyMembers.name).limit(10000);const matches=people.filter(m=>isJalaliBirthday(m.birthdate!,date));const sent=matches.length?await db.select({memberId:centralBirthdaySms.memberId}).from(centralBirthdaySms).where(and(eq(centralBirthdaySms.birthdayDate,date),ne(centralBirthdaySms.status,"failed"),inArray(centralBirthdaySms.memberId,matches.map(m=>m.id)))):[];const sentIds=new Set(sent.map(x=>x.memberId));const pending=matches.filter(m=>!sentIds.has(m.id));return{date,total:matches.length,alreadySent:sent.length,recipients:pending.length,members:pending.slice(0,20).map(m=>({id:m.id,name:m.name,phone:m.phone}))}}},
 { method:"GET", pattern:"admin/loyalty/birthday-history", handler:async(req)=>{await requireApi("SMS_MANAGE");const date=req.nextUrl.searchParams.get("date");if(date&&!validCampaignDate(date))throw new HttpError(400,"تاریخ مناسبت معتبر نیست");return db.select({id:centralBirthdaySms.id,date:centralBirthdaySms.birthdayDate,status:centralBirthdaySms.status,sentAt:centralBirthdaySms.sentAt,name:centralLoyaltyMembers.name,phone:centralLoyaltyMembers.phone}).from(centralBirthdaySms).innerJoin(centralLoyaltyMembers,eq(centralLoyaltyMembers.id,centralBirthdaySms.memberId)).where(date?eq(centralBirthdaySms.birthdayDate,date):undefined).orderBy(desc(centralBirthdaySms.sentAt)).limit(500)}},
 { method:"POST", pattern:"admin/loyalty/birthday-settings", handler:async(req,_p,meta)=>{const user=await requireApi("SMS_MANAGE"),b=await body(req);const values={birthdayRewardPercent:int(b.percent,0,90),birthdayRewardMinOrder:int(b.minOrder??0,0),birthdayRewardValidityDays:int(b.validityDays,1,365)};for(const [key,value] of Object.entries(values))await db.insert(settings).values({key,value}).onConflictDoUpdate({target:settings.key,set:{value}});await audit(db,{userId:user.id,...meta},"admin.birthday_reward_settings","settings",null,null,values);return{ok:true,...values}}},
 { method:"POST", pattern:"admin/loyalty/birthday-campaign", handler:async(req,_p,meta)=>{const user=await requireApi("SMS_MANAGE");rateLimit(`admin-birthday:${user.id}`,2,60_000);const b=await body(req),date=str(b.date,10),message=str(b.message,800),cfg=await getSettings();if(!validCampaignDate(date))throw new HttpError(400,"تاریخ مناسبت معتبر نیست");if(message.length<3)throw new HttpError(400,"متن پیامک کوتاه یا خالی است");const people=await db.select().from(centralLoyaltyMembers).where(and(eq(centralLoyaltyMembers.smsConsent,true),isNotNull(centralLoyaltyMembers.birthdate))).orderBy(centralLoyaltyMembers.name).limit(10001);const matches=people.filter(m=>isJalaliBirthday(m.birthdate!,date));if(matches.length>500)throw new HttpError(400,"در این مناسبت بیش از ۵۰۰ مشتری واجدشرایط است؛ ارسال را در چند روز/نوبت تقسیم کنید");const sent=matches.length?await db.select({memberId:centralBirthdaySms.memberId}).from(centralBirthdaySms).where(and(eq(centralBirthdaySms.birthdayDate,date),ne(centralBirthdaySms.status,"failed"),inArray(centralBirthdaySms.memberId,matches.map(m=>m.id)))):[];const sentIds=new Set(sent.map(x=>x.memberId));let success=0,failed=0,skipped=sent.length;for(const m of matches){if(sentIds.has(m.id))continue;let [reserve]=await db.insert(centralBirthdaySms).values({memberId:m.id,birthdayDate:date,status:"sending"}).onConflictDoNothing().returning({id:centralBirthdaySms.id});if(!reserve)[reserve]=await db.update(centralBirthdaySms).set({status:"sending",sentAt:new Date()}).where(and(eq(centralBirthdaySms.memberId,m.id),eq(centralBirthdaySms.birthdayDate,date),eq(centralBirthdaySms.status,"failed"))).returning({id:centralBirthdaySms.id});if(!reserve){skipped++;continue}const code=cfg.birthdayRewardPercent>0?await db.transaction(tx=>issueReward(tx,null,m.phone,cfg.birthdayRewardPercent,cfg.birthdayRewardMinOrder,cfg.birthdayRewardValidityDays)):"";const text=message.replace(/\{\{\s*name\s*\}\}/g,m.name).replace(/\{name\}/g,m.name).replace(/\{\{\s*code\s*\}\}/g,code).replace(/\{\{\s*percent\s*\}\}/g,String(cfg.birthdayRewardPercent));const status=await sendDirectSms("birthday",m.phone,text,{name:m.name,code,percent:cfg.birthdayRewardPercent,shop:cfg.siteName});if(status==="sent"||status==="simulated")success++;else failed++;await db.update(centralBirthdaySms).set({status,sentAt:new Date()}).where(eq(centralBirthdaySms.id,reserve.id));}await audit(db,{userId:user.id,...meta},"admin.birthday_campaign","central_loyalty_member",0,null,{date,recipients:matches.length,success,failed,skipped});return{ok:true,recipients:matches.length,success,failed,skipped}}},
 { method:"GET", pattern:"admin/pos/terminals", handler:async()=>{await requireApi("INVENTORY_MANAGE");return db.select().from(posTerminals).where(and(sql`${posTerminals.sellerId} is null`,eq(posTerminals.enabled,true))).orderBy(posTerminals.name)}},
 { method:"GET", pattern:"admin/settings/pos-terminals", handler:async()=>{await requireApi("SETTINGS_MANAGE");return db.select().from(posTerminals).where(sql`${posTerminals.sellerId} is null`).orderBy(posTerminals.id)}},
 { method:"POST", pattern:"admin/settings/pos-terminals", handler:async(req,_p,meta)=>{const user=await requireApi("SETTINGS_MANAGE"),b=await body(req),name=str(b.name,80);if(!name)throw new HttpError(400,"نام کارتخوان الزامی است");const [row]=await db.insert(posTerminals).values({sellerId:null,name,bankName:str(b.bankName,80)||null,terminalCode:str(b.terminalCode,80)||null,enabled:b.enabled!==false}).returning();await audit(db,{userId:user.id,...meta},"pos_terminal.create","pos_terminal",row.id,null,row);return row}},
 { method:"PUT", pattern:"admin/settings/pos-terminals/:id", handler:async(req,p,meta)=>{const user=await requireApi("SETTINGS_MANAGE"),id=int(p.id,1),b=await body(req),name=str(b.name,80);if(!name)throw new HttpError(400,"نام کارتخوان الزامی است");const [row]=await db.update(posTerminals).set({name,bankName:str(b.bankName,80)||null,terminalCode:str(b.terminalCode,80)||null,enabled:b.enabled===true,updatedAt:new Date()}).where(and(eq(posTerminals.id,id),sql`${posTerminals.sellerId} is null`)).returning();if(!row)throw new HttpError(404,"کارتخوان یافت نشد");await audit(db,{userId:user.id,...meta},"pos_terminal.update","pos_terminal",id,null,row);return row}},
 { method:"DELETE", pattern:"admin/settings/pos-terminals/:id", handler:async(_req,p,meta)=>{const user=await requireApi("SETTINGS_MANAGE"),id=int(p.id,1);const [row]=await db.delete(posTerminals).where(and(eq(posTerminals.id,id),sql`${posTerminals.sellerId} is null`)).returning();if(!row)throw new HttpError(404,"کارتخوان یافت نشد");await audit(db,{userId:user.id,...meta},"pos_terminal.delete","pos_terminal",id,row,null);return{ok:true}}},
 { method:"GET", pattern:"admin/pos/products", handler:async()=>{
   await requireApi("INVENTORY_MANAGE");
   const rows=await db.select({variant:productVariants,product:products,lastCost:sql<number>`coalesce(${productVariants.costPrice},(select sm.unit_cost from stock_movements sm where sm.variant_id=${productVariants.id} and sm.type in ('purchase_in','repack_in') order by sm.created_at desc, sm.id desc limit 1),${products.avgCost},0)`}).from(productVariants).innerJoin(products,eq(products.id,productVariants.productId)).where(and(eq(productVariants.isActive,true),eq(productVariants.isSellable,true),eq(products.source,"central"),eq(products.status,"active"))).orderBy(products.nameFa);
   return rows.filter(x=>x.variant.onHand>x.variant.reserved && (x.variant.price??x.product.basePrice)>0).map(({variant,product,lastCost})=>({offerId:variant.id,productId:product.id,name:product.nameFa,brand:product.brand,sku:variant.sku,price:variant.price??product.basePrice,cost:Number(lastCost),stock:variant.onHand-variant.reserved}));
 }},
 { method:"GET", pattern:"admin/pos/recent", handler:async()=>{await requireApi("INVENTORY_MANAGE");return db.select().from(centralPosSales).orderBy(desc(centralPosSales.createdAt)).limit(20)}},
 { method:"POST", pattern:"admin/pos", handler:async(req,_p,meta)=>{
   const user=await requireApi("INVENTORY_MANAGE");rateLimit(`central-pos:${user.id}`,60,60_000);const b=await body(req);const key=str(b.idempotencyKey,100);if(key.length<8)throw new HttpError(400,"شناسه یکتای فروش نامعتبر است");
   const phone=normalizePhone(b.phone);if(!/^09\d{9}$/.test(phone))throw new HttpError(400,"شماره همراه مشتری معتبر نیست");const customerName=str(b.customerName,100)||"مشتری حضوری",birthdate=parseBirthdate(b.birthdate);
   if(!Array.isArray(b.items)||!b.items.length||b.items.length>80)throw new HttpError(400,"سبد فروش خالی یا نامعتبر است");const items=new Map<number,number>();for(const raw of b.items as Record<string,unknown>[]){const id=int(raw.offerId,1),qty=int(raw.qty,1,10000);items.set(id,(items.get(id)??0)+qty)}
   const [prior]=await db.select().from(centralPosSales).where(eq(centralPosSales.idempotencyKey,key));if(prior){if(prior.createdBy!==user.id)throw new HttpError(409,"شناسه فاکتور تکراری است");return{ok:true,...prior,repeated:true}}
   const percent=int(b.discountPercent??0,0,90),cash=int((b.settlement as Record<string,unknown>|undefined)?.cash??0),card=int((b.settlement as Record<string,unknown>|undefined)?.card??0),method=str(b.paymentMethod,10),terminalId=card>0?int(b.terminalId,1):null;const ids=[...items.keys()];
   const sale=await db.transaction(async tx=>{
    await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${key}))`);const [duplicate]=await tx.select().from(centralPosSales).where(eq(centralPosSales.idempotencyKey,key));if(duplicate){if(duplicate.createdBy!==user.id)throw new HttpError(409,"شناسه تکراری");return {...duplicate,repeated:true};}
    const rows=await tx.select({variant:productVariants,product:products,lastCost:sql<number>`coalesce(${productVariants.costPrice},(select sm.unit_cost from stock_movements sm where sm.variant_id=${productVariants.id} and sm.type in ('purchase_in','repack_in') order by sm.created_at desc, sm.id desc limit 1),${products.avgCost},0)`}).from(productVariants).innerJoin(products,eq(products.id,productVariants.productId)).where(and(inArray(productVariants.id,ids),eq(productVariants.isActive,true),eq(productVariants.isSellable,true),eq(products.source,"central"),eq(products.status,"active"))).for("update");
    if(rows.length!==ids.length)throw new HttpError(400,"یکی از کالاها دیگر برای فروش فعال نیست");const norm=rows.map(({variant,product,lastCost})=>({variant,product,lastCost:Number(lastCost),qty:items.get(variant.id)!}));
    for(const x of norm)if(x.variant.onHand-x.variant.reserved<x.qty)throw new HttpError(409,`موجودی «${x.product.nameFa}» کافی نیست`);
    const subtotal=norm.reduce((s,x)=>s+(x.variant.price??x.product.basePrice)*x.qty,0);if(!Number.isSafeInteger(subtotal))throw new HttpError(400,"مبلغ فاکتور بیش از حد مجاز است");
    for(const x of norm){const price=x.variant.price??x.product.basePrice,cost=x.lastCost,max=Math.max(0,Math.floor(((price-cost)*100)/price));if(percent>max)throw new HttpError(400,`حداکثر تخفیف مجاز برای «${x.product.nameFa}» ${max.toLocaleString("fa-IR")}٪ است؛ قیمت فروش نباید از آخرین قیمت خرید انبار کمتر شود`)}
    const discount=Math.floor(subtotal*percent/100),total=subtotal-discount;
    const minimumTotal=norm.reduce((sum,x)=>sum+x.lastCost*x.qty,0);if(total<minimumTotal)throw new HttpError(400,`مبلغ نهایی فاکتور نباید از بهای آخرین خرید کالاها (${minimumTotal.toLocaleString("fa-IR")} تومان) کمتر باشد`);
    if(!["cash","card","mixed"].includes(method)||cash+card!==total||(method==="cash"&&(cash!==total||card!==0))||(method==="card"&&(card!==total||cash!==0))||(method==="mixed"&&(!cash||!card)))throw new HttpError(400,"جمع نقد و کارت باید با مبلغ فاکتور برابر باشد");
    if(card>0){const [terminal]=await tx.select().from(posTerminals).where(and(eq(posTerminals.id,terminalId!),eq(posTerminals.enabled,true),sql`${posTerminals.sellerId} is null`));if(!terminal)throw new HttpError(400,"کارتخوان فعال انبار مرکزی را انتخاب کنید")}
    const rewardCode=b.sendNextReward===true?await issueReward(tx,null,phone,int(b.nextRewardPercent??10,1,50),0,30):null;
    const number=genNumber("POS");const [created]=await tx.insert(centralPosSales).values({number,rewardCode,idempotencyKey:key,terminalId,createdBy:user.id,customerName,customerPhone:phone,subtotal,discount,total,paymentMethod:method,settlement:{cash,card}}).returning();let cogs=0;
    for(const x of norm){const [updated]=await tx.update(productVariants).set({onHand:sql`${productVariants.onHand}-${x.qty}`}).where(and(eq(productVariants.id,x.variant.id),sql`${productVariants.onHand}-${productVariants.reserved} >= ${x.qty}`)).returning({id:productVariants.id});if(!updated)throw new HttpError(409,"موجودی هم‌زمان این تنوع تغییر کرد؛ دوباره تلاش کنید");const consigned=await consumeConsignmentLots(tx,x.product.id,x.variant.id,x.qty,{action:"sale",refType:"central_pos_sale",refId:created.id}),consignedQty=consigned.reduce((sum,item)=>sum+item.quantity,0),consignedCost=consigned.reduce((sum,item)=>sum+item.quantity*item.unitCost,0),ownedQty=x.qty-consignedQty;await postConsignmentPayables(tx,consigned,`فروش کالای امانی فاکتور ${number}`,{type:"central_pos_sale",id:created.id},user.id);cogs+=x.lastCost*ownedQty;const unitPrice=x.variant.price??x.product.basePrice,lineTotal=unitPrice*x.qty,unitCost=Math.round((x.lastCost*ownedQty+consignedCost)/x.qty);
      await tx.insert(centralPosItems).values({saleId:created.id,variantId:x.variant.id,productId:x.product.id,title:x.product.nameFa,quantity:x.qty,unitPrice,lineTotal,unitCost});
      await tx.insert(stockMovements).values({productId:x.product.id,variantId:x.variant.id,type:"central_pos_sale",qty:-x.qty,unitCost,refType:"central_pos_sale",refId:created.id,note:`فروش حضوری انبار مرکزی ${number}`,userId:user.id});}
    await tx.insert(centralLoyaltyMembers).values({name:customerName,phone,birthdate,smsConsent:b.smsConsent===true,visits:1,totalSpent:total,lastPurchaseAt:new Date()}).onConflictDoUpdate({target:centralLoyaltyMembers.phone,set:{name:customerName,...(birthdate?{birthdate}:{}),visits:sql`${centralLoyaltyMembers.visits}+1`,totalSpent:sql`${centralLoyaltyMembers.totalSpent}+${total}`,smsConsent:sql`${centralLoyaltyMembers.smsConsent} OR ${b.smsConsent===true}`,lastPurchaseAt:new Date(),updatedAt:new Date()}});
    const lines:Line[]=[{code:"1101",debit:total},{code:"4101",credit:total}];if(cogs){lines.push({code:"5101",debit:cogs});lines.push({code:"1201",credit:cogs})}await postJournal(tx,`فروش حضوری انبار مرکزی ${number}`,lines,{type:"central_pos_sale",id:created.id},user.id);
    await audit(tx,{userId:user.id,...meta},"central.pos_sale","central_pos_sale",created.id,null,{number,items:norm.length,total});return created;
   });if(sale.rewardCode&&b.smsConsent===true&&!("repeated" in sale))await sendDirectSms("pos_reward",phone,`${customerName} عزیز، کد تخفیف خرید بعدی شما: ${sale.rewardCode} (اعتبار ۳۰ روز).`);return{rewardCode:sale.rewardCode,ok:true,id:sale.id,number:sale.number,subtotal:sale.subtotal,discount:sale.discount,total:sale.total,commission:0};
 }}
];
