import { randomBytes } from 'node:crypto';
import { and,desc,eq,isNull,sql } from 'drizzle-orm';
import { db } from '@/db';
import { giftCards,giftCardEntries,posTerminals,orders,centralPosSales,sellerPosSales,returnRequests,customerBalances,customerCreditEntries } from '@/db/schema';
import { requireApi } from '../auth';
import { body,idParam,type Route } from './router';
import { HttpError,int,str } from '../util';
import { validPhone } from '../commerce-common';
import { postJournal } from '../accounting';
import { audit } from '../audit';
import { sendDirectSms } from '../sms';
import { requestReturn,processReturn } from '../returns';
export const commerceRoutes:Route[]=[
 {method:"GET",pattern:"admin/giftcards/terminals",handler:async()=>{await requireApi("PAYMENTS_MANAGE");return db.select({id:posTerminals.id,name:posTerminals.name}).from(posTerminals).where(and(isNull(posTerminals.sellerId),eq(posTerminals.enabled,true))) }},
 {method:'GET',pattern:'admin/giftcards',handler:async()=>{await requireApi('PAYMENTS_MANAGE');return db.select().from(giftCards).orderBy(desc(giftCards.id))}},
 {method:'POST',pattern:'admin/giftcards',handler:async(req,_p,m)=>{const user=await requireApi('PAYMENTS_MANAGE'),b=await body(req),amount=int(b.amount,10000,1000000000),buyerName=str(b.buyerName,100),buyerPhone=validPhone(b.buyerPhone),targetPhone=b.targetPhone?validPhone(b.targetPhone):null,message=str(b.message,500),key=str(b.idempotencyKey,100),cash=int(b.cash??0,0),card=amount-cash,terminalId=card>0?int(b.terminalId,1):null;if(!buyerName||key.length<8||card<0)throw new HttpError(400,'مشخصات خریدار یا تسویه معتبر نیست');
  const result=await db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${key}))`);const [old]=await tx.select().from(giftCards).where(eq(giftCards.idempotencyKey,key));if(old){if(old.createdBy!==user.id)throw new HttpError(409,'شناسه تکراری');return{card:old,fresh:false}}if(terminalId){const [t]=await tx.select().from(posTerminals).where(and(eq(posTerminals.id,terminalId),isNull(posTerminals.sellerId),eq(posTerminals.enabled,true)));if(!t)throw new HttpError(400,'کارتخوان معتبر نیست')}
   const [g]=await tx.insert(giftCards).values({code:`GIFT-${randomBytes(8).toString('hex').toUpperCase()}`,amount,balance:amount,buyerName,buyerPhone,targetPhone,message,paymentMethod:cash===amount?'cash':cash===0?'card':'mixed',settlement:{cash,card},terminalId,createdBy:user.id,idempotencyKey:key}).returning();await tx.insert(giftCardEntries).values({cardId:g.id,amount,reference:`sale:${g.id}`});await postJournal(tx,`فروش کارت هدیه ${g.id}`,[{code:'1101',debit:amount},{code:'2103',credit:amount}],{type:'gift_card',id:g.id},user.id);await audit(tx,{userId:user.id,...m},'gift_card.sell','gift_card',g.id,null,{amount,targetPhone});return{card:g,fresh:true};});
  const smsStatus=result.fresh&&b.sendSms===true&&targetPhone?await sendDirectSms('gift_card',targetPhone,`کارت هدیه ${amount.toLocaleString('fa-IR')} تومانی سبزینه: ${result.card.code}${message?' — '+message:''}`):null;return{...result.card,smsStatus};}},
 {method:'POST',pattern:'admin/giftcards/:id/revoke',handler:async(_req,p,m)=>{const user=await requireApi('PAYMENTS_MANAGE'),id=idParam(p.id);return db.transaction(async tx=>{const [g]=await tx.select().from(giftCards).where(eq(giftCards.id,id)).for('update');if(!g||g.revoked)throw new HttpError(409,'کارت یافت نشد یا قبلاً باطل شده است');const [pending]=await tx.select({id:orders.id}).from(orders).where(and(eq(orders.giftCardId,id),eq(orders.status,'pending_payment'))).limit(1);if(pending)throw new HttpError(409,'کارت در سفارش پرداخت‌نشده رزرو شده است؛ ابتدا سفارش تعیین تکلیف شود');await postJournal(tx,`بازپرداخت مانده کارت هدیه ${id}`,[{code:'2103',debit:g.balance},{code:'1101',credit:g.balance}],{type:'gift_card_revoke',id},user.id);await tx.update(giftCards).set({revoked:true,balance:0}).where(eq(giftCards.id,id));await tx.insert(giftCardEntries).values({cardId:id,amount:-g.balance,reference:`revoke:${id}`});await audit(tx,{userId:user.id,...m},'gift_card.revoke','gift_card',id,null,{refund:g.balance});return{ok:true,refund:g.balance}})}},
 {method:'GET',pattern:'customer/credit',handler:async()=>{const u=await requireApi();const [balance]=await db.select().from(customerBalances).where(eq(customerBalances.phone,u.phone));return{balance:balance?.balance??0,entries:await db.select().from(customerCreditEntries).where(eq(customerCreditEntries.phone,u.phone)).orderBy(desc(customerCreditEntries.id)).limit(100)}}},
 {method:'POST',pattern:'returns',handler:async(req)=>{const u=await requireApi(),b=await body(req);return requestReturn(u,str(b.kind,20)||'online',int(b.saleId,1),str(b.reason,1000))}},
 {method:'GET',pattern:'admin/returns',handler:async()=>{await requireApi('ORDERS_MANAGE');return db.select().from(returnRequests).orderBy(desc(returnRequests.id)).limit(500)}},
 {method:'GET',pattern:'seller/returns',handler:async()=>{const u=await requireApi();if(!u.sellerId)throw new HttpError(403,'فقط تأمین‌کنندگان');return db.select().from(returnRequests).where(eq(returnRequests.sellerId,u.sellerId)).orderBy(desc(returnRequests.id)).limit(500)}},
 {method:'GET',pattern:'customer/returns',handler:async()=>{const u=await requireApi();return db.select().from(returnRequests).where(eq(returnRequests.customerPhone,u.phone)).orderBy(desc(returnRequests.id)).limit(100)}},
 ...(['admin','seller'] as const).map(area=>({method:'POST',pattern:`${area}/returns/lookup`,handler:async(req)=>{const u=await requireApi(area==='admin'?'ORDERS_MANAGE':undefined);if(area==='seller'&&!u.sellerId)throw new HttpError(403,'فقط فروشنده');const b=await body(req),number=str(b.number,50),kind=area==='seller'?'seller':str(b.kind,20);let id:number|undefined;if(kind==='online'){const [o]=await db.select({id:orders.id}).from(orders).where(eq(orders.number,number));id=o?.id}else if(kind==='central'){const [o]=await db.select({id:centralPosSales.id}).from(centralPosSales).where(eq(centralPosSales.number,number));id=o?.id}else if(kind==='seller'){const [o]=await db.select({id:sellerPosSales.id}).from(sellerPosSales).where(and(eq(sellerPosSales.number,number),area==='seller'?eq(sellerPosSales.sellerId,u.sellerId!):undefined));id=o?.id}if(!id)throw new HttpError(404,'فاکتور یافت نشد');return requestReturn(u,kind,id,str(b.reason,1000))}} satisfies Route)),
 ...(['admin','seller'] as const).map(area=>({method:'POST',pattern:`${area}/returns/:id`,handler:async(req,p,m)=>{const u=await requireApi(area==='admin'?'ORDERS_MANAGE':undefined),id=idParam(p.id),b=await body(req);if(area==='seller'){if(!u.sellerId)throw new HttpError(403,'فقط فروشنده');const [r]=await db.select().from(returnRequests).where(and(eq(returnRequests.id,id),eq(returnRequests.sellerId,u.sellerId),eq(returnRequests.kind,'seller')));if(!r)throw new HttpError(404,'مرجوعی یافت نشد')}return processReturn({userId:u.id,...m},id,str(b.action,20),str(b.note,1000),str(b.refundReference,100))}} satisfies Route)),
];
