import { and, desc, eq, inArray, sql } from 'drizzle-orm';
import { db } from '@/db';
import { accessRoles, users, sessions, centralLoyaltyMembers, customerGroups, customerGroupMembers, marketingCampaigns, campaignDeliveries,customerBalances,customerCreditEntries,customerWallets,centralPosSales,discountCodes,giftCards,returnRequests } from '@/db/schema';
import { requireApi,hashPassword } from '../auth';
import { PERMISSIONS, ROLES } from '../rbac';
import { HttpError,int,str } from '../util';
import { body,idParam,type Route } from './router';
import { audience,ownerScope } from '../crm';
import { automaticTypes,CAMPAIGN_TYPES,dateOnly,validPhone } from '../commerce-common';
import { audit } from '../audit';

export const crmRoutes:Route[]=[
 {method:'GET',pattern:'admin/users',handler:async()=>{await requireApi('USERS_MANAGE');return {roles:await db.select().from(accessRoles),users:await db.select({id:users.id,name:users.name,phone:users.phone,email:users.email,role:users.role,roleId:users.roleId,birthdate:users.birthdate,smsConsent:users.smsConsent,isActive:users.isActive,extraPermissions:users.extraPermissions,createdAt:users.createdAt,orderCount:sql<number>`(select count(*)::int from orders where customer_id=${users.id} and payment_status='paid')+(select count(*)::int from central_pos_sales where customer_phone=${users.phone} and status='completed')`,totalSpent:sql<number>`(select coalesce(sum(total+credit_amount),0)::float8 from orders where customer_id=${users.id} and payment_status='paid')+(select coalesce(sum(total),0)::float8 from central_pos_sales where customer_phone=${users.phone} and status='completed')`,balance:sql<number>`coalesce((select balance::float8 from customer_wallets where user_id=${users.id}),0)`}).from(users).orderBy(desc(users.createdAt))}}},
 {method:'POST',pattern:'admin/users',handler:async(req,_p,m)=>{const actor=await requireApi('USERS_MANAGE'),b=await body(req),role=str(b.role,40)||'customer',name=str(b.name,100),phone=validPhone(b.phone),password=str(b.password,100);if(!name||password.length<8||!(role in ROLES)||role==='seller')throw new HttpError(400,'نام، نقش یا رمز معتبر نیست');if(actor.role!=='super_admin'&&role!=='customer')throw new HttpError(403,'ایجاد حساب سازمانی نیازمند دسترسی مدیر کل است');const [u]=await db.insert(users).values({name,phone,role,passwordHash:hashPassword(password),email:str(b.email,150)||null,birthdate:dateOnly(b.birthdate),smsConsent:b.smsConsent===true}).returning({id:users.id});await audit(db,{userId:actor.id,...m},'user.create','user',u.id,null,{role});return u}},
 {method:'POST',pattern:'admin/users/:id',handler:async(req,p,m)=>{const actor=await requireApi('USERS_MANAGE'),id=idParam(p.id),b=await body(req);
  await db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(99128)`);const [old]=await tx.select().from(users).where(eq(users.id,id)).for('update');if(!old)throw new HttpError(404,'کاربر یافت نشد');if(old.role==='super_admin'&&actor.role!=='super_admin')throw new HttpError(403,'ویرایش مدیر کل مجاز نیست');
   const security=['role','roleId','extraPermissions'].some(k=>k in b);if(security&&actor.role!=='super_admin')throw new HttpError(403,'تنظیم دسترسی‌ها فقط توسط مدیر کل انجام می‌شود');
   const patch:Partial<typeof users.$inferInsert>={};if('name'in b){patch.name=str(b.name,100);if(!patch.name)throw new HttpError(400,'نام الزامی است')}if('phone'in b){patch.phone=validPhone(b.phone);}
   if('email'in b){patch.email=str(b.email,150)||null;if(patch.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(patch.email))throw new HttpError(400,'ایمیل معتبر نیست')}
   if('birthdate'in b)patch.birthdate=dateOnly(b.birthdate);if('smsConsent'in b)patch.smsConsent=b.smsConsent===true;
   if('isActive'in b)patch.isActive=b.isActive===true;
   if('role'in b){const role=str(b.role,50);if(!(role in ROLES)||((old.role==='seller')!==(role==='seller')))throw new HttpError(400,'نقش نامعتبر یا با حساب فروشنده ناسازگار است');patch.role=role}
   if('roleId'in b){patch.roleId=b.roleId?int(b.roleId,1):null;if(patch.roleId){const [r]=await tx.select().from(accessRoles).where(eq(accessRoles.id,patch.roleId));if(!r)throw new HttpError(400,'نقش سفارشی یافت نشد')}}
   if('extraPermissions'in b){if(!Array.isArray(b.extraPermissions)||b.extraPermissions.some(x=>!(PERMISSIONS as readonly unknown[]).includes(x)))throw new HttpError(400,'مجوز نامعتبر');patch.extraPermissions=b.extraPermissions as string[]}
   if(id===actor.id&&(patch.isActive===false||(old.role==='super_admin'&&patch.role&&patch.role!=='super_admin')))throw new HttpError(400,'نمی‌توانید دسترسی مدیر کل خود را حذف یا حساب خود را غیرفعال کنید');
   if(old.role==='super_admin'&&(patch.isActive===false||(patch.role&&patch.role!=='super_admin'))){const admins=await tx.select({id:users.id}).from(users).where(and(eq(users.role,'super_admin'),eq(users.isActive,true)));if(admins.length<=1)throw new HttpError(400,'حداقل یک مدیر کل فعال باید باقی بماند')}
   if(str(b.password,100)){if(str(b.password,100).length<8)throw new HttpError(400,'رمز حداقل ۸ کاراکتر است');patch.passwordHash=hashPassword(str(b.password,100))}
   if(patch.phone&&patch.phone!==old.phone){
    const phone=patch.phone;
    const [existing]=await tx.select({id:users.id}).from(users).where(eq(users.phone,phone));
    const [club]=await tx.select({id:centralLoyaltyMembers.id}).from(centralLoyaltyMembers).where(eq(centralLoyaltyMembers.phone,phone));
    const [balance]=await tx.select().from(customerBalances).where(eq(customerBalances.phone,phone));
    if(existing||club||balance)throw new HttpError(409,'شماره جدید به حساب یا باشگاه دیگری تعلق دارد؛ تغییر شماره بدون ادغام مجاز نیست');
    await tx.update(customerBalances).set({phone}).where(eq(customerBalances.phone,old.phone));
    await tx.update(customerCreditEntries).set({phone}).where(eq(customerCreditEntries.phone,old.phone));
    await tx.update(centralLoyaltyMembers).set({phone}).where(eq(centralLoyaltyMembers.phone,old.phone));
    await tx.update(centralPosSales).set({customerPhone:phone}).where(eq(centralPosSales.customerPhone,old.phone));
    await tx.update(discountCodes).set({targetPhone:phone}).where(eq(discountCodes.targetPhone,old.phone));
    await tx.update(giftCards).set({targetPhone:phone}).where(eq(giftCards.targetPhone,old.phone));
    await tx.update(returnRequests).set({customerPhone:phone}).where(and(eq(returnRequests.customerPhone,old.phone),sql`${returnRequests.kind}<>'seller'`));
    const members=await tx.select({id:customerGroupMembers.id,groupId:customerGroupMembers.groupId}).from(customerGroupMembers).innerJoin(customerGroups,eq(customerGroups.id,customerGroupMembers.groupId)).where(and(eq(customerGroupMembers.phone,old.phone),sql`${customerGroups.sellerId} is null`));
    for(const member of members){await tx.insert(customerGroupMembers).values({groupId:member.groupId,phone}).onConflictDoNothing();await tx.delete(customerGroupMembers).where(eq(customerGroupMembers.id,member.id));}
    await tx.delete(sessions).where(eq(sessions.userId,id));
   }
   await tx.update(users).set(patch).where(eq(users.id,id));
   if('smsConsent'in b||'birthdate'in b||'name'in b)await tx.update(centralLoyaltyMembers).set({...('smsConsent'in b?{smsConsent:patch.smsConsent}:{}),...('birthdate'in b?{birthdate:patch.birthdate}:{}),...('name'in b?{name:patch.name}:{})}).where(eq(centralLoyaltyMembers.phone,patch.phone??old.phone));
   if(patch.passwordHash||patch.isActive===false)await tx.delete(sessions).where(eq(sessions.userId,id));
   const safe={...patch};delete safe.passwordHash;await audit(tx,{userId:actor.id,...m},'user.update','user',id,null,{...safe,passwordChanged:!!patch.passwordHash});
  });return{ok:true}}},
 {method:'GET',pattern:'admin/access/roles',handler:async()=>{await requireApi('USERS_MANAGE');return db.select().from(accessRoles).orderBy(accessRoles.id)}},
 ...(['POST','PUT','DELETE'] as const).map(method=>({method,pattern:method==='POST'?'admin/access/roles':'admin/access/roles/:id',handler:async(req,p,m)=>{const actor=await requireApi('USERS_MANAGE');if(actor.role!=='super_admin')throw new HttpError(403,'مدیریت نقش‌ها فقط برای مدیر کل است');const id=method==='POST'?null:idParam(p.id);if(method==='DELETE'){await db.transaction(async tx=>{await tx.update(users).set({roleId:null}).where(eq(users.roleId,id!));await tx.delete(accessRoles).where(eq(accessRoles.id,id!))});return{ok:true}}const b=await body(req),name=str(b.name,100);if(!name||!Array.isArray(b.permissions)||b.permissions.some(x=>!(PERMISSIONS as readonly unknown[]).includes(x)))throw new HttpError(400,'نام یا مجوزهای نقش معتبر نیست');const values={name,permissions:b.permissions as string[]};const [r]=id?await db.update(accessRoles).set(values).where(eq(accessRoles.id,id)).returning():await db.insert(accessRoles).values(values).returning();await audit(db,{userId:actor.id,...m},'role.save','role',r?.id??null,null,values);return r}} satisfies Route)),
];
for(const area of ['admin','seller'] as const){
 const scope=async()=>{const u=await requireApi(area==='admin'?'SMS_MANAGE':undefined);if(area==='seller'&&!u.sellerId)throw new HttpError(403,'فقط تأمین‌کننده');return{u,sellerId:area==='admin'?null:u.sellerId!}};
 crmRoutes.push(
  {method:'GET',pattern:`${area}/crm`,handler:async()=>{const {sellerId}=await scope();const groups=await db.select().from(customerGroups).where(ownerScope(customerGroups.sellerId,sellerId));const campaigns=await db.select().from(marketingCampaigns).where(ownerScope(marketingCampaigns.sellerId,sellerId)).orderBy(desc(marketingCampaigns.id));const ids=campaigns.map(c=>c.id);const stats=ids.length?await db.select({campaignId:campaignDeliveries.campaignId,status:campaignDeliveries.status,count:sql<number>`count(*)::int`}).from(campaignDeliveries).where(inArray(campaignDeliveries.campaignId,ids)).groupBy(campaignDeliveries.campaignId,campaignDeliveries.status):[];return{groups,members:groups.length?await db.select().from(customerGroupMembers).where(inArray(customerGroupMembers.groupId,groups.map(g=>g.id))):[],people:await audience(sellerId),campaigns,stats}}},
  {method:'POST',pattern:`${area}/crm/groups`,handler:async(req)=>{const {sellerId}=await scope();const b=await body(req),name=str(b.name,100);if(!name)throw new HttpError(400,'نام گروه الزامی است');const [g]=await db.insert(customerGroups).values({sellerId,name}).returning();return g}},
  {method:'PUT',pattern:`${area}/crm/groups/:id`,handler:async(req,p)=>{const {sellerId}=await scope(),id=idParam(p.id),b=await body(req);const [g]=await db.select().from(customerGroups).where(and(eq(customerGroups.id,id),ownerScope(customerGroups.sellerId,sellerId)));if(!g)throw new HttpError(404,'گروه یافت نشد');const name=str(b.name,100);if(!name||!Array.isArray(b.phones))throw new HttpError(400,'نام و اعضای گروه معتبر نیست');const known=new Set((await audience(sellerId)).map(p=>p.phone));const phones=[...new Set(b.phones.map(validPhone))];if(phones.some(p=>!known.has(p)))throw new HttpError(400,'یکی از مشتریان عضو باشگاه شما نیست');await db.transaction(async tx=>{await tx.update(customerGroups).set({name}).where(eq(customerGroups.id,id));await tx.delete(customerGroupMembers).where(eq(customerGroupMembers.groupId,id));if(phones.length)await tx.insert(customerGroupMembers).values(phones.map(phone=>({groupId:id,phone})))});return{ok:true}}},
  {method:'DELETE',pattern:`${area}/crm/groups/:id`,handler:async(_req,p)=>{const {sellerId}=await scope(),id=idParam(p.id);const used=await db.select({id:marketingCampaigns.id}).from(marketingCampaigns).where(eq(marketingCampaigns.groupId,id));if(used.length)throw new HttpError(409,'ابتدا گروه مخاطبان کمپین‌های مرتبط را تغییر دهید');await db.delete(customerGroups).where(and(eq(customerGroups.id,id),ownerScope(customerGroups.sellerId,sellerId)));return{ok:true}}},
  {method:'POST',pattern:`${area}/crm/campaigns`,handler:async(req)=>{const {sellerId}=await scope(),b=await body(req),name=str(b.name,100),type=str(b.type,20),message=str(b.body,800),groupId=b.groupId?int(b.groupId,1):null;if(!name||message.length<3||!(type in CAMPAIGN_TYPES)||(sellerId!==null&&type==='review'))throw new HttpError(400,'اطلاعات کمپین معتبر نیست');if(groupId){const [g]=await db.select().from(customerGroups).where(and(eq(customerGroups.id,groupId),ownerScope(customerGroups.sellerId,sellerId)));if(!g)throw new HttpError(400,'گروه مخاطبان معتبر نیست')}
   const scheduleAt=type==='scheduled'?new Date(str(b.scheduleAt,50)):null;if(scheduleAt&&(!Number.isFinite(scheduleAt.getTime())||scheduleAt<=new Date()))throw new HttpError(400,'تاریخ اجرا باید در آینده باشد');const [c]=await db.insert(marketingCampaigns).values({sellerId,name,type,body:message,groupId,scheduleAt,sendHour:int(b.sendHour??9,0,23),rewardPercent:int(b.rewardPercent??0,0,50),minOrder:int(b.minOrder??0,0),validityDays:int(b.validityDays??30,1,365)}).returning();return c}},
  {method:'POST',pattern:`${area}/crm/campaigns/:id`,handler:async(req,p)=>{const {sellerId}=await scope(),id=idParam(p.id),b=await body(req);const [c]=await db.select().from(marketingCampaigns).where(and(eq(marketingCampaigns.id,id),ownerScope(marketingCampaigns.sellerId,sellerId)));if(!c)throw new HttpError(404,'کمپین یافت نشد');const action=str(b.action,20);if(action==='retry'){await db.update(campaignDeliveries).set({status:'pending'}).where(and(eq(campaignDeliveries.campaignId,id),eq(campaignDeliveries.status,'failed')));await db.update(marketingCampaigns).set({status:'active'}).where(eq(marketingCampaigns.id,id))}else if(['pause','resume','archive'].includes(action)){if(c.status==='done'&&!automaticTypes.includes(c.type)&&action==='resume')throw new HttpError(400,'کمپین پایان‌یافته دوباره ارسال نمی‌شود');await db.update(marketingCampaigns).set({status:action==='pause'?'paused':action==='resume'?'active':'archived'}).where(eq(marketingCampaigns.id,id))}else throw new HttpError(400,'عملیات نامعتبر');return{ok:true}}},
 );
}
