import { and, desc, eq, gt, inArray, sql } from "drizzle-orm";
import { db } from "@/db";
import { customerAddresses, customerFavorites, customerWalletEntries, customerWallets, customerWalletWithdrawals, loyaltyPointEntries, products, users, sessions } from "@/db/schema";
import { currentSessionDigest, requireApi } from "../auth";
import { audit } from "../audit";
import { HttpError, int, str } from "../util";
import { body, idParam, type Route } from "./router";
import { getSettings } from "../settings";

const phone = (v: unknown) => str(v, 30).replace(/[۰-۹]/g, d => String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).replace(/\D/g, "");

function sessionDevice(ua: string | null) {
  const value = ua ?? "";
  const platform = /iphone|ipad|ipod/i.test(value) ? "iPhone یا iPad" : /android/i.test(value) ? "Android" : /windows/i.test(value) ? "Windows" : /macintosh|mac os/i.test(value) ? "Mac" : /linux/i.test(value) ? "Linux" : "دستگاه ناشناس";
  const browser = /edg\//i.test(value) ? "Edge" : /firefox\//i.test(value) ? "Firefox" : /chrome\//i.test(value) ? "Chrome" : /safari\//i.test(value) ? "Safari" : "مرورگر وب";
  return `${browser} · ${platform}`;
}

function maskedIp(ip: string | null) {
  if (!ip) return "نامشخص";
  if (ip === "::1" || ip === "127.0.0.1" || ip === "local" || ip.startsWith("::ffff:127.")) return "شبکه محلی";
  if (ip.includes(".")) return `${ip.split(".").slice(0, 2).join(".")}.***.***`;
  if (ip.includes(":")) return "IPv6 پنهان";
  return "نامشخص";
}

export const customerRoutes: Route[] = [
  { method: "GET", pattern: "customer/sessions", handler: async () => {
    const u = await requireApi(), currentId = await currentSessionDigest(), now = new Date();
    const rows = await db.select().from(sessions).where(and(eq(sessions.userId, u.id), gt(sessions.expiresAt, now))).orderBy(desc(sessions.createdAt)).limit(30);
    return rows.map((row) => ({ id: row.id, device: sessionDevice(row.userAgent), ip: maskedIp(row.ip), createdAt: row.createdAt, expiresAt: row.expiresAt, current: row.id === currentId }));
  } },
  { method: "DELETE", pattern: "customer/sessions/:id", handler: async (_req, p, meta) => {
    const u = await requireApi(), id = p.id;
    if (!/^[a-f0-9]{64}$/i.test(id)) throw new HttpError(400, "شناسه نشست معتبر نیست");
    if (id === await currentSessionDigest()) throw new HttpError(400, "برای خروج از این دستگاه از دکمه خروج استفاده کنید");
    const [old] = await db.select().from(sessions).where(and(eq(sessions.id, id), eq(sessions.userId, u.id)));
    if (!old) throw new HttpError(404, "نشست فعال پیدا نشد");
    await db.delete(sessions).where(and(eq(sessions.id, id), eq(sessions.userId, u.id)));
    await audit(db, { userId: u.id, ...meta }, "auth.session_revoke", "session", null, { device: sessionDevice(old.userAgent), ip: maskedIp(old.ip) }, { revoked: true });
    return { ok: true };
  } },
  { method: "GET", pattern: "customer/addresses", handler: async () => { const u=await requireApi(); return db.select().from(customerAddresses).where(eq(customerAddresses.userId,u.id)).orderBy(customerAddresses.id); } },
  { method: "POST", pattern: "customer/addresses", handler: async (req,_p,m) => { const u=await requireApi(), b=await body(req);const receiverName=str(b.receiverName,100),receiverPhone=phone(b.receiverPhone),city=str(b.city,80),address=str(b.address,600);if(receiverName.length<2||!/^09\d{9}$/.test(receiverPhone)||!city||address.length<8)throw new HttpError(400,"نام، موبایل، شهر و نشانی کامل را وارد کنید");const isDefault=b.isDefault===true;return db.transaction(async tx=>{if(isDefault)await tx.update(customerAddresses).set({isDefault:false,updatedAt:new Date()}).where(eq(customerAddresses.userId,u.id));const [row]=await tx.insert(customerAddresses).values({userId:u.id,title:str(b.title,80)||"خانه",receiverName,receiverPhone,city,address,postalCode:str(b.postalCode,20)||null,latitude:str(b.latitude,40)||null,longitude:str(b.longitude,40)||null,isDefault}).returning();await audit(tx,{userId:u.id,...m},"customer.address.create","customer_address",row.id,null,row);return row;}); } },
  { method: "PUT", pattern: "customer/addresses/:id", handler: async (req,p,m) => {const u=await requireApi(),id=idParam(p.id),b=await body(req),receiverName=str(b.receiverName,100),receiverPhone=phone(b.receiverPhone),city=str(b.city,80),address=str(b.address,600);if(receiverName.length<2||!/^09\d{9}$/.test(receiverPhone)||!city||address.length<8)throw new HttpError(400,"نام، موبایل، شهر و نشانی کامل را وارد کنید");const [old]=await db.select().from(customerAddresses).where(and(eq(customerAddresses.id,id),eq(customerAddresses.userId,u.id)));if(!old)throw new HttpError(404,"آدرس پیدا نشد");const isDefault=b.isDefault===true;return db.transaction(async tx=>{if(isDefault)await tx.update(customerAddresses).set({isDefault:false,updatedAt:new Date()}).where(eq(customerAddresses.userId,u.id));const [row]=await tx.update(customerAddresses).set({title:str(b.title,80)||"خانه",receiverName,receiverPhone,city,address,postalCode:str(b.postalCode,20)||null,latitude:str(b.latitude,40)||null,longitude:str(b.longitude,40)||null,isDefault,updatedAt:new Date()}).where(eq(customerAddresses.id,id)).returning();await audit(tx,{userId:u.id,...m},"customer.address.update","customer_address",id,old,row);return row;}); } },
  { method: "DELETE", pattern: "customer/addresses/:id", handler: async (_req,p,m) => {const u=await requireApi(),id=idParam(p.id);const [old]=await db.select().from(customerAddresses).where(and(eq(customerAddresses.id,id),eq(customerAddresses.userId,u.id)));if(!old)throw new HttpError(404,"آدرس پیدا نشد");await db.delete(customerAddresses).where(eq(customerAddresses.id,id));await audit(db,{userId:u.id,...m},"customer.address.delete","customer_address",id,old,null);if(old.isDefault){const [next]=await db.select({id:customerAddresses.id}).from(customerAddresses).where(eq(customerAddresses.userId,u.id)).orderBy(customerAddresses.id).limit(1);if(next)await db.update(customerAddresses).set({isDefault:true,updatedAt:new Date()}).where(eq(customerAddresses.id,next.id));}return{ok:true};} },

  { method: "GET", pattern: "customer/favorites", handler: async () => {const u=await requireApi(),fav=await db.select({id:customerFavorites.id,productId:customerFavorites.productId,createdAt:customerFavorites.createdAt}).from(customerFavorites).where(eq(customerFavorites.userId,u.id)).orderBy(desc(customerFavorites.createdAt));const ids=fav.map(x=>x.productId);const list=ids.length?await db.select().from(products).where(inArray(products.id,ids)):[];const order=new Map(fav.map((x,i)=>[x.productId,i]));return list.sort((a,b)=>(order.get(a.id)??999)-(order.get(b.id)??999));} },
  { method: "POST", pattern: "customer/favorites", handler: async (req,_p,m) => {const u=await requireApi(),b=await body(req),productId=int(b.productId,1),[product]=await db.select({id:products.id}).from(products).where(eq(products.id,productId));if(!product)throw new HttpError(404,"محصول پیدا نشد");const [old]=await db.select().from(customerFavorites).where(and(eq(customerFavorites.userId,u.id),eq(customerFavorites.productId,productId)));if(old){await db.delete(customerFavorites).where(eq(customerFavorites.id,old.id));await audit(db,{userId:u.id,...m},"customer.favorite.remove","product",productId,old,null);return{favorited:false};}await db.insert(customerFavorites).values({userId:u.id,productId});await audit(db,{userId:u.id,...m},"customer.favorite.add","product",productId,null,{userId:u.id});return{favorited:true};} },

  { method: "GET", pattern: "customer/wallet", handler: async () => {const u=await requireApi();await db.insert(customerWallets).values({userId:u.id}).onConflictDoNothing();const [wallet]=await db.select().from(customerWallets).where(eq(customerWallets.userId,u.id));const [me]=await db.select({bankInfo:users.bankInfo,marketingPoints:users.marketingPoints}).from(users).where(eq(users.id,u.id));const entries=await db.select().from(customerWalletEntries).where(eq(customerWalletEntries.userId,u.id)).orderBy(desc(customerWalletEntries.createdAt)).limit(100);const cfg=await getSettings();return{balance:wallet?.balance??0,bankInfo:me.bankInfo??{},points:me.marketingPoints,pointValue:cfg.loyaltyPointValue,entries};} },
  { method: "PUT", pattern: "customer/wallet/bank", handler: async (req,_p,m) => {const u=await requireApi(),b=await body(req),card=phone(b.cardNumber),iban=str(b.iban,34).replace(/\s|-/g,"").toUpperCase(),accountHolder=str(b.accountHolder,100),bankName=str(b.bankName,80);if(card&&!/^\d{16}$/.test(card))throw new HttpError(400,"شماره کارت باید ۱۶ رقم باشد");if(iban&&!/^IR\d{24}$/.test(iban))throw new HttpError(400,"شماره شبا باید با IR و ۲۴ رقم وارد شود");await db.update(users).set({bankInfo:{cardNumber:card,iban,accountHolder,bankName}}).where(eq(users.id,u.id));await audit(db,{userId:u.id,...m},"customer.bank.update","user",u.id,null,{cardLast4:card.slice(-4),hasIban:!!iban,bankName});return{ok:true};} },
  { method: "POST", pattern: "customer/wallet/withdraw", handler: async (req,_p,m) => {const u=await requireApi(),b=await body(req),n=Number(b.amount);if(!Number.isSafeInteger(n)||n<100000)throw new HttpError(400,"حداقل مبلغ برداشت ۱۰۰ هزار تومان است");const [me]=await db.select({bankInfo:users.bankInfo}).from(users).where(eq(users.id,u.id));const info=me.bankInfo??{};if(!info.cardNumber&&!info.iban)throw new HttpError(400,"ابتدا اطلاعات حساب بانکی را ثبت کنید");return db.transaction(async tx=>{const [w]=await tx.select().from(customerWallets).where(eq(customerWallets.userId,u.id)).for("update");if(!w||w.balance<n)throw new HttpError(400,"موجودی کیف پول کافی نیست");await tx.update(customerWallets).set({balance:sql`${customerWallets.balance}-${n}`,updatedAt:new Date()}).where(eq(customerWallets.userId,u.id));const [row]=await tx.insert(customerWalletWithdrawals).values({userId:u.id,amount:n,bankInfo:info}).returning({id:customerWalletWithdrawals.id});await tx.insert(customerWalletEntries).values({userId:u.id,amount:-n,type:"withdrawal",description:"درخواست برداشت از کیف پول",reference:`withdrawal:${row.id}`});await audit(tx,{userId:u.id,...m},"customer.wallet.withdrawal","customer_wallet_withdrawal",row.id,null,{amount:n});return{ok:true,id:row.id};});} },
  { method: "POST", pattern: "customer/wallet/convert-points", handler: async (req,_p,m) => {const u=await requireApi(),b=await body(req);const n=Number(b.points),[me]=await db.select().from(users).where(eq(users.id,u.id));const points=b.points==="all"?me.marketingPoints:n;if(!Number.isInteger(points)||points<1||points>me.marketingPoints)throw new HttpError(400,"امتیاز کافی ندارید");const cfg=await getSettings();const pointValue=Number(cfg.loyaltyPointValue)||0;if(pointValue<1)throw new HttpError(400,"ارزش هر امتیاز در تنظیمات معتبر نیست");const added=points*pointValue;await db.transaction(async tx=>{const [fresh]=await tx.update(users).set({marketingPoints:sql`${users.marketingPoints}-${points}`}).where(and(eq(users.id,u.id),sql`${users.marketingPoints}>=${points}`)).returning({id:users.id});if(!fresh)throw new HttpError(409,"امتیاز کافی نیست");await tx.insert(customerWallets).values({userId:u.id,balance:added}).onConflictDoUpdate({target:customerWallets.userId,set:{balance:sql`${customerWallets.balance}+${added}`,updatedAt:new Date()}});const reference=`points:${u.id}:${Date.now()}`;await tx.insert(customerWalletEntries).values({userId:u.id,amount:added,type:"points",description:`تبدیل ${points.toLocaleString("fa-IR")} امتیاز به اعتبار`,reference});await tx.insert(loyaltyPointEntries).values({userId:u.id,kind:"conversion",points:-points,amount:added,reference,description:"تبدیل امتیازها به اعتبار کیف پول"});await audit(tx,{userId:u.id,...m},"customer.referral.convert","user",u.id,null,{points,added});});return{ok:true,added,remaining:me.marketingPoints-points};} },
  { method: "GET", pattern: "customer/referrals", handler: async () => {const u=await requireApi();let [me]=await db.select().from(users).where(eq(users.id,u.id));if(!me)throw new HttpError(404,"حساب کاربری پیدا نشد");if(!me.referralCode){const code=`SBZ${u.id}${Math.random().toString(36).slice(2,7)}`.toUpperCase();const [updated]=await db.update(users).set({referralCode:code}).where(eq(users.id,u.id)).returning();if(updated)me=updated;}const referrals=await db.select({id:users.id,name:users.name,createdAt:users.createdAt}).from(users).where(eq(users.referredById,u.id)).orderBy(desc(users.createdAt));const cfg=await getSettings();return{code:me.referralCode,points:me.marketingPoints,pointValue:cfg.loyaltyPointValue,referrals};} },
  { method: "GET", pattern: "admin/customer-wallet-withdrawals", handler: async () => {await requireApi("WITHDRAWALS_MANAGE");return db.select({id:customerWalletWithdrawals.id,userId:users.id,name:users.name,phone:users.phone,amount:customerWalletWithdrawals.amount,bankInfo:customerWalletWithdrawals.bankInfo,status:customerWalletWithdrawals.status,note:customerWalletWithdrawals.note,createdAt:customerWalletWithdrawals.createdAt}).from(customerWalletWithdrawals).innerJoin(users,eq(users.id,customerWalletWithdrawals.userId)).orderBy(desc(customerWalletWithdrawals.createdAt)).limit(300);} },
  { method: "PUT", pattern: "admin/customer-wallet-withdrawals/:id", handler: async (req,p,m) => {const admin=await requireApi("WITHDRAWALS_MANAGE"),id=idParam(p.id),b=await body(req),action=str(b.action,20),note=str(b.note,300);if(!["paid","reject"].includes(action))throw new HttpError(400,"وضعیت درخواست معتبر نیست");return db.transaction(async tx=>{const [row]=await tx.select().from(customerWalletWithdrawals).where(eq(customerWalletWithdrawals.id,id)).for("update");if(!row)throw new HttpError(404,"درخواست برداشت پیدا نشد");if(row.status!=="pending")throw new HttpError(409,"این درخواست قبلاً بررسی شده است");if(action==="reject"){await tx.insert(customerWallets).values({userId:row.userId,balance:row.amount}).onConflictDoUpdate({target:customerWallets.userId,set:{balance:sql`${customerWallets.balance}+${row.amount}`,updatedAt:new Date()}});await tx.insert(customerWalletEntries).values({userId:row.userId,amount:row.amount,type:"withdrawal_refund",description:"بازگشت وجه درخواست برداشت ردشده",reference:`withdrawal-refund:${row.id}`});}const [updated]=await tx.update(customerWalletWithdrawals).set({status:action==="paid"?"paid":"rejected",adminNote:note||null,processedAt:new Date()}).where(eq(customerWalletWithdrawals.id,id)).returning();await audit(tx,{userId:admin.id,...m},"admin.customer_wallet_withdrawal", "customer_wallet_withdrawal",id,row,updated);return updated;});} },
];
