import { and,eq,inArray,sql } from 'drizzle-orm';
import { db } from '@/db';
import { returnRequests,orders,orderItems,orderHistory,sellerShipments,centralPosSales,centralPosItems,sellerPosSales,sellerPosItems,users,products,productVariants,sellerOffers,stockMovements,wallets,walletTransactions,journalEntries,payments,discountCodes,sellerLoyaltyRewards,centralLoyaltyMembers,sellerLoyaltyClubs,sellerLoyaltyMembers } from '@/db/schema';
import { postJournal,reverseJournal } from './accounting';
import { addCredit,restoreCredit } from './credit';
import { HttpError } from './util';
import { restoreConsignmentSale } from './services/inventory-accounting';
import { audit } from './audit';
import type { SessionUser } from './auth';
import type { Ctx,DB } from './types';
async function reverseReferences(tx:DB,type:string,id:number,userId:number){const entries=await tx.select().from(journalEntries).where(and(eq(journalEntries.refType,type),eq(journalEntries.refId,id)));for(const entry of entries)if(entry.status!=='reversed')await reverseJournal(tx,entry.id,'مرجوعی و دریافت کالا',userId)}
export async function requestReturn(user:SessionUser,kind:string,saleId:number,reason:string){
 if(!['online','central','seller'].includes(kind)||reason.length<5)throw new HttpError(400,'نوع فروش یا دلیل مرجوعی معتبر نیست');
 return db.transaction(async tx=>{let number='',phone='',name='',amount=0,sellerId:number|null=null;
 if(kind==='online'){const [o]=await tx.select().from(orders).where(eq(orders.id,saleId)).for('update');if(!o||(!user.permissions.includes('ORDERS_MANAGE')&&o.customerId!==user.id))throw new HttpError(404,'سفارش یافت نشد');const sh=await tx.select().from(sellerShipments).where(eq(sellerShipments.orderId,saleId));if(o.paymentStatus!=='paid'||!sh.length||sh.some(x=>!['shipped','delivered','returned'].includes(x.status)))throw new HttpError(400,'مرجوعی پس از پرداخت و ارسال همه اقلام امکان‌پذیر است');const [u]=await tx.select().from(users).where(eq(users.id,o.customerId));number=o.number;phone=u.phone;name=u.name;amount=o.total+o.creditAmount;
 }else if(kind==='central'){if(!user.permissions.includes('ORDERS_MANAGE'))throw new HttpError(403,'ثبت مرجوعی حضوری نیازمند دسترسی مدیریت سفارش است');const [s]=await tx.select().from(centralPosSales).where(eq(centralPosSales.id,saleId)).for('update');if(!s||s.status!=='completed')throw new HttpError(400,'فاکتور قابل مرجوعی نیست');number=s.number;phone=s.customerPhone;name=s.customerName;amount=s.total;
 }else{const [s]=await tx.select().from(sellerPosSales).where(eq(sellerPosSales.id,saleId)).for('update');if(!s||(!user.permissions.includes('ORDERS_MANAGE')&&s.sellerId!==user.sellerId))throw new HttpError(404,'فاکتور یافت نشد');if(s.status!=='completed')throw new HttpError(400,'فاکتور مرجوع شده است');number=s.number;phone=s.customerPhone;name=s.customerName;amount=s.total;sellerId=s.sellerId;}
 const [old]=await tx.select().from(returnRequests).where(and(eq(returnRequests.kind,kind),eq(returnRequests.saleId,saleId)));if(old)throw new HttpError(409,'برای این فاکتور قبلاً درخواست مرجوعی ثبت شده است');
 const [r]=await tx.insert(returnRequests).values({kind,saleId,number,customerPhone:phone,customerName:name,sellerId,reason,amount,createdBy:user.id}).returning();return r;
 });
}
export async function processReturn(ctx:Ctx&{userId:number},id:number,action:string,note:string,refundReference:string,requestedRefundMethod='wallet'){
 if(!['approve','reject'].includes(action))throw new HttpError(400,'عملیات نامعتبر');
 if(!['wallet','cash'].includes(requestedRefundMethod))throw new HttpError(400,'روش بازپرداخت معتبر نیست');
 return db.transaction(async tx=>{
 const [r]=await tx.select().from(returnRequests).where(eq(returnRequests.id,id)).for('update');if(!r)throw new HttpError(404,'درخواست یافت نشد');if(r.status!=='pending')throw new HttpError(409,'درخواست قبلاً بررسی شده است');
 if(action==='reject'){if(!note)throw new HttpError(400,'دلیل رد را وارد کنید');await tx.update(returnRequests).set({status:'rejected',adminNote:note,processedBy:ctx.userId,processedAt:new Date()}).where(eq(returnRequests.id,id));await audit(tx,ctx,'return.reject','return',id,null,{note});return{ok:true}}
 let cashCredit=0;let refundMethod='none';
 if(r.kind==='online'){
  const [o]=await tx.select().from(orders).where(eq(orders.id,r.saleId)).for('update');if(o.paymentStatus!=='paid')throw new HttpError(409,'وضعیت پرداخت تغییر کرده است');const shs=await tx.select().from(sellerShipments).where(eq(sellerShipments.orderId,o.id)).for('update');if(shs.some(sh=>!['shipped','delivered','returned'].includes(sh.status)))throw new HttpError(409,'مرسوله‌ای هنوز ارسال نشده است');
  for(const sh of shs){if(sh.sellerId){const [w]=await tx.select().from(wallets).where(eq(wallets.sellerId,sh.sellerId)).for('update');if(w){const gross=sh.itemsTotal+sh.shippingCost,net=gross-sh.commission-sh.deductions;const bucket=sh.settled?'available':'pending';const amount=sh.settled?net:gross;if((sh.settled?w.availableBalance:w.pendingBalance)<amount)throw new HttpError(409,'موجودی قابل برگشت تأمین‌کننده کافی نیست؛ ابتدا تسویه مالی فروشنده اصلاح شود');await tx.update(wallets).set(sh.settled?{availableBalance:w.availableBalance-amount}:{pendingBalance:w.pendingBalance-amount}).where(eq(wallets.id,w.id));await tx.insert(walletTransactions).values({walletId:w.id,type:'return',bucket,amount:-amount,refType:'return',refId:id,note:'بازگشت سهم فروش مرجوعی'})}if(sh.settled)await reverseReferences(tx,'shipment',sh.id,ctx.userId)}}
  const items=await tx.select().from(orderItems).where(eq(orderItems.orderId,o.id));
  for(const it of items){if(it.offerId)await tx.update(sellerOffers).set({stock:sql`${sellerOffers.stock}+${it.qty}`,updatedAt:new Date()}).where(eq(sellerOffers.id,it.offerId));else if(it.variantId)await tx.update(productVariants).set({onHand:sql`${productVariants.onHand}+${it.qty}`}).where(eq(productVariants.id,it.variantId));else await tx.update(products).set({onHand:sql`${products.onHand}+${it.qty}`,updatedAt:new Date()}).where(eq(products.id,it.productId));await tx.insert(stockMovements).values({productId:it.productId,variantId:it.variantId,offerId:it.offerId,type:'return_in',qty:it.qty,unitCost:it.unitCost,refType:'return',refId:id,userId:ctx.userId})}
  await restoreConsignmentSale(tx,'order',o.id);await reverseReferences(tx,'order',o.id,ctx.userId);await restoreCredit(tx,r.customerPhone,o.creditAmount,o.giftCardId,o.id,o.customerId);cashCredit=o.total;refundMethod='wallet';
  await tx.update(sellerShipments).set({status:'returned'}).where(eq(sellerShipments.orderId,o.id));await tx.update(orders).set({status:'returned',paymentStatus:'refunded',updatedAt:new Date()}).where(eq(orders.id,o.id));await tx.update(payments).set({status:'refunded'}).where(eq(payments.orderId,o.id));await tx.insert(orderHistory).values({orderId:o.id,status:'returned',userId:ctx.userId,note:`مرجوعی #${id}؛ بازگشت کالا و کیف پول`});
 }else if(r.kind==='central'){
  const [s]=await tx.select().from(centralPosSales).where(eq(centralPosSales.id,r.saleId)).for('update');if(s.status!=='completed')throw new HttpError(409,'فاکتور مرجوع شده است');const items=await tx.select().from(centralPosItems).where(eq(centralPosItems.saleId,s.id));for(const it of items){await tx.update(productVariants).set({onHand:sql`${productVariants.onHand}+${it.quantity}`}).where(eq(productVariants.id,it.variantId));await tx.update(products).set({onHand:sql`${products.onHand}+${it.quantity}`,updatedAt:new Date()}).where(eq(products.id,it.productId));await tx.insert(stockMovements).values({productId:it.productId,variantId:it.variantId,type:'return_in',qty:it.quantity,unitCost:it.unitCost,refType:'return',refId:id,userId:ctx.userId})}
  await restoreConsignmentSale(tx,'central_pos_sale',s.id);await reverseReferences(tx,'central_pos_sale',s.id,ctx.userId);refundMethod=requestedRefundMethod;if(refundMethod==='wallet')cashCredit=s.total;await tx.update(centralPosSales).set({status:'returned'}).where(eq(centralPosSales.id,s.id));if(s.rewardCode)await tx.update(discountCodes).set({isActive:false}).where(eq(discountCodes.code,s.rewardCode));await tx.update(centralLoyaltyMembers).set({totalSpent:sql`greatest(0,${centralLoyaltyMembers.totalSpent}-${s.total})`,visits:sql`greatest(0,${centralLoyaltyMembers.visits}-1)`}).where(eq(centralLoyaltyMembers.phone,s.customerPhone));
 }else{
  if(!refundReference)throw new HttpError(400,'شماره رسید بازپرداخت وجه توسط تأمین‌کننده الزامی است');const [s]=await tx.select().from(sellerPosSales).where(eq(sellerPosSales.id,r.saleId)).for('update');if(s.status!=='completed')throw new HttpError(409,'فاکتور مرجوع شده است');const items=await tx.select().from(sellerPosItems).where(eq(sellerPosItems.saleId,s.id));for(const it of items){await tx.update(sellerOffers).set({stock:sql`${sellerOffers.stock}+${it.quantity}`,updatedAt:new Date()}).where(and(eq(sellerOffers.id,it.offerId),eq(sellerOffers.sellerId,s.sellerId)));await tx.insert(stockMovements).values({productId:it.productId,offerId:it.offerId,type:'return_in',qty:it.quantity,refType:'return',refId:id,userId:ctx.userId})}await tx.update(sellerPosSales).set({status:'returned'}).where(eq(sellerPosSales.id,s.id));await tx.update(sellerLoyaltyRewards).set({expiresAt:new Date(0)}).where(and(eq(sellerLoyaltyRewards.saleId,s.id),eq(sellerLoyaltyRewards.sellerId,s.sellerId)));const clubs=await tx.select({id:sellerLoyaltyClubs.id}).from(sellerLoyaltyClubs).where(eq(sellerLoyaltyClubs.sellerId,s.sellerId));if(clubs.length)await tx.update(sellerLoyaltyMembers).set({totalSpent:sql`greatest(0,${sellerLoyaltyMembers.totalSpent}-${s.total})`,visits:sql`greatest(0,${sellerLoyaltyMembers.visits}-1)`}).where(and(inArray(sellerLoyaltyMembers.clubId,clubs.map(x=>x.id)),eq(sellerLoyaltyMembers.phone,s.customerPhone)));refundMethod='seller';
 }
 if(cashCredit){await addCredit(tx,r.customerPhone,cashCredit,`return:${id}`,'بازگشت وجه مرجوعی به کیف پول');await postJournal(tx,`بازپرداخت کیف پول مرجوعی ${r.number}`,[{code:'1101',debit:cashCredit},{code:'2103',credit:cashCredit,detail1:`customer:${r.customerPhone}`}],{type:'return',id},ctx.userId)}
 await tx.update(returnRequests).set({status:'refunded',adminNote:note||null,refundReference:refundReference||null,refundMethod,processedBy:ctx.userId,processedAt:new Date()}).where(eq(returnRequests.id,id));await audit(tx,ctx,'return.approve','return',id,null,{amount:r.amount,kind:r.kind,refundMethod});return{ok:true};
 });
}
