import { db } from "@/db";
import { settings } from "@/db/schema";
import type { DB } from "./types";
import { setCurrencyUnit } from "./util";
import { siteBrandText } from "./brand";

export const DEFAULT_SETTINGS = {
  siteName: "فروشگاه ارگانیک",
  siteTagline: "بازار آنلاین محصولات ارگانیک و طبیعی",
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || process.env.SITE_URL || "http://localhost:3000",
  homeSeoTitle: "{{siteName}} | خرید محصولات ارگانیک و طبیعی",
  homeSeoDescription: "خرید آنلاین محصولات ارگانیک، طبیعی و محلی مستقیم از کشاورزان و تولیدکنندگان معتبر با تضمین کیفیت.",
  homeSeoKeywords: "محصولات ارگانیک، خرید عسل طبیعی، روغن ارگانیک، غذای سالم",
  shopSeoTitle: "فروشگاه محصولات ارگانیک و طبیعی",
  shopSeoDescription: "فروشگاه آنلاین محصولات ارگانیک، طبیعی و محلی؛ مقایسه، انتخاب و خرید مستقیم از تولیدکنندگان منتخب.",
  shopSeoKeywords: "فروشگاه ارگانیک، محصولات طبیعی، خرید آنلاین محصولات سالم",
  blogSeoTitle: "مجله {{siteName}} | راهنمای زندگی سالم و محصولات ارگانیک",
  blogSeoDescription: "مقالات تخصصی درباره تغذیه سالم، محصولات ارگانیک، کشاورزی پایدار و سبک زندگی طبیعی.",
  blogSeoKeywords: "مجله سلامت، تغذیه سالم، محصولات ارگانیک، سبک زندگی سالم",
  robotsUserAgents: "*",
  robotsAllowPaths: "/",
  robotsDisallowPaths: "/admin/\n/seller/\n/customer/\n/api/\n/login",
  robotsSitemapEnabled: 1,
  defaultOgImageId: 0,
  currency: "تومان",
  appearanceMode: "light",
  appearancePalette: "sunshine",
  siteLogoMediaId: 0,
  taxRate: 10,
  defaultCommission: 8,
  minWithdrawal: 500000,
  releasePolicy: "on_customer_confirm",
  paymentGateway: "zarinpal",
  paymentGatewaysConfigured: 0,
  paymentManualEnabled: 1,
  paymentZarinpalEnabled: 0,
  paymentZibalEnabled: 0,
  paymentTorobpayEnabled: 0,
  paymentNextpayEnabled: 0,
  paymentDigipayEnabled: 0,
  paymentSnappayEnabled: 0,
  paymentBehpardakhtEnabled: 0,
  paymentPasargadEnabled: 0,
  paymentVandarEnabled: 0,
  paymentZarinpalIconId: 0,
  paymentZibalIconId: 0,
  paymentTorobpayIconId: 0,
  paymentNextpayIconId: 0,
  paymentDigipayIconId: 0,
  paymentSnappayIconId: 0,
  paymentBehpardakhtIconId: 0,
  paymentPasargadIconId: 0,
  paymentVandarIconId: 0,
  zarinpalMerchantId: "",
  zarinpalSandbox: 0,
  zibalMerchant: "",
  torobpayClientId: "",
  torobpayClientSecret: "",
  torobpayUsername: "",
  torobpayPassword: "",
  nextpayApiKey: "",
  digipayClientId: "",
  digipayClientSecret: "",
  digipayUsername: "",
  digipayPassword: "",
  digipaySandbox: 0,
  digipayAmountMultiplier: 10,
  digipayPreferredGateway: 2,
  snappayApiBaseUrl: "",
  snappayClientId: "",
  snappayClientSecret: "",
  snappayUsername: "",
  snappayPassword: "",
  behpardakhtTerminalId: "",
  behpardakhtUsername: "",
  behpardakhtPassword: "",
  pasargadUsername: "",
  pasargadPassword: "",
  pasargadTerminalId: "",
  vandarApiKey: "",
  watermarkEnabled: 0,
  watermarkText: "{{siteName}}",
  watermarkImageId: 0,
  watermarkPosition: "southeast",
  watermarkOpacity: 45,
  smsProvider: "kavenegar",
  smsSender: "10008663",
  smsApiKey: "",
  smsUsername: "",
  smsPassword: "",
  smsirParameterMap: "",
  inventoryPolicy: "reserve_on_order",
  supplyDefaultMargin: 15,
  supplyShippingCost: 90000,
  centralShippingCost: 85000,
  senderName: "انبار مرکزی {{siteName}}",
  senderAddress: "تهران، خیابان امین‌حضور، پلاک ۱۲",
  marketplaceRules: "فروشندگان موظف به ارسال کالای اصل و مطابق مشخصات هستند.",
  economicCode: "411111111111",
  orderExpiryMinutes: 120,
  multiVendor: 1,
  allowSellerSignup: 1,
  productLiveViewers: 0,
  heroType: "image",
  heroMediaId: 0,
  heroTitle: "طعم واقعی طبیعت، ارگانیک و بی‌واسطه",
  heroSubtitle: "عسل طبیعی، روغن‌های پرس سرد، ادویه، خشکبار و سبزیجات تازه از کشاورزان و تولیدکنندگان منتخب با گواهی معتبر.",
  supportPhone: "021-91000000",
  supportEmail: "info@example.com",
  supportHours: "همه روزه ۱۰ تا ۲۱",
  footerScripts: "",
  returnDays: 10,
  freeShippingOver: 2000000,
  reviewAutoApprove: 0,
  loyaltyPointValue: 1000,
  loyaltyTiersEnabled: 0,
  loyaltyTierRules: [
    { code: "bronze", name: "برنزی", minimumSpend: 0, pointsMultiplierBps: 10000 },
    { code: "silver", name: "نقره‌ای", minimumSpend: 5000000, pointsMultiplierBps: 12500 },
    { code: "gold", name: "طلایی", minimumSpend: 20000000, pointsMultiplierBps: 15000 },
  ] as { code: string; name: string; minimumSpend: number; pointsMultiplierBps: number }[],
  birthdayRewardPercent: 10,
  birthdayRewardMinOrder: 0,
  birthdayRewardValidityDays: 30,
  senderPhone: "021-91000000",
  senderPostalCode: "1136914311",
  senderCity: "تهران",
  bankAccountInfo: "بانک ملت — کارت ۶۱۰۴-۳۳۷۸-۱۲۳۴-۵۶۷۸ — شبا IR120120000000001234567890 — به نام شرکت {{siteName}}",
  labelShowLogo: 1,
  labelShowOrderBarcode: 1,
  labelBorderStyle: "solid",
  invoiceFooter: "کالای فروخته‌شده تا ۷ روز با حفظ شرایط اولیه قابل مرجوع است.",
  productTypes: [] as { name: string; parameters: string[] }[],
  organicBadgeLabel: "ارگانیک گواهی‌شده",
  invoiceWidth: 210,
  invoiceFontSize: 13,
  invoicePadding: 8,
  invoiceHeaderTemplate: "صورتحساب فروش کالا\nشماره: {invoiceNumber}  |  تاریخ: {date}",
  invoiceBorderStyle: "solid",
  invoiceBorderColor: "#64748b",
  invoiceAccentColor: "#166534",
  invoiceShowLogo: 1,
  invoiceShowSiteName: 1,
  invoiceShowTagline: 1,
  invoiceShowHeaderTemplate: 1,
  invoiceShowInvoiceBarcode: 1,
  invoiceShowSeller: 1,
  invoiceShowBuyer: 1,
  invoiceShowOfficialInfo: 1,
  invoiceShowItems: 1,
  invoiceShowTax: 1,
  invoiceShowShipping: 1,
  invoiceShowPayments: 1,
  invoiceShowFooter: 1,
  invoiceShowSignatures: 1,
  barcodeLabelWidth: 50,
  barcodeLabelHeight: 30,
  barcodeFontSize: 10,
  barcodeShowProductName: 1,
  barcodeShowSku: 1,
  labelWidth: 100,
  labelHeight: 150,
  labelFontSize: 12,
  labelShowBarcode: 1,
  labelShowSender: 1,
  labelShowItems: 1,
  labelTemplate: "# گیرنده: {receiver}\nتلفن: {phone}\nآدرس: {city} - {address}\nکد پستی: {postalCode}\n---\nسفارش: {order} | مرسوله: {shipment}\nحامل: {carrier} | تعداد بسته: {packages}\n! شکستنی — با احتیاط حمل شود",
};
export type SettingsShape = typeof DEFAULT_SETTINGS;

export async function getSettings(tx: DB = db): Promise<SettingsShape> {
  const rows = await tx.select().from(settings);
  const out = { ...DEFAULT_SETTINGS } as Record<string, unknown>;
  for (const r of rows) out[r.key] = r.value;
  const siteName = String(out.siteName || DEFAULT_SETTINGS.siteName);
  for (const [key, value] of Object.entries(out)) if (typeof value === "string" && key !== "siteName" && key !== "footerScripts") out[key] = siteBrandText(value, siteName);
  setCurrencyUnit(String(out.currency ?? DEFAULT_SETTINGS.currency));
  return out as SettingsShape;
}
