ALTER TABLE users ADD COLUMN IF NOT EXISTS role_id integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS birthdate timestamptz;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sms_consent boolean NOT NULL DEFAULT false;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS credit_amount bigint NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS gift_card_id integer;
ALTER TABLE discount_codes ADD COLUMN IF NOT EXISTS target_phone text;
ALTER TABLE central_pos_sales ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'completed';
ALTER TABLE central_pos_sales ADD COLUMN IF NOT EXISTS reward_code text;
ALTER TABLE seller_pos_sales ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'completed';
CREATE TABLE IF NOT EXISTS access_roles (id serial PRIMARY KEY,name text NOT NULL UNIQUE,permissions jsonb NOT NULL DEFAULT '[]',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customer_groups (id serial PRIMARY KEY,seller_id integer,name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customer_group_members (id serial PRIMARY KEY,group_id integer NOT NULL REFERENCES customer_groups(id) ON DELETE CASCADE,phone text NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS customer_group_phone ON customer_group_members(group_id,phone);
CREATE TABLE IF NOT EXISTS marketing_campaigns (id serial PRIMARY KEY,seller_id integer,name text NOT NULL,type text NOT NULL,body text NOT NULL,group_id integer REFERENCES customer_groups(id),status text NOT NULL DEFAULT 'active',schedule_at timestamptz,send_hour integer NOT NULL DEFAULT 9,reward_percent integer NOT NULL DEFAULT 0,min_order bigint NOT NULL DEFAULT 0,validity_days integer NOT NULL DEFAULT 30,last_run_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS campaign_deliveries (id serial PRIMARY KEY,campaign_id integer NOT NULL REFERENCES marketing_campaigns(id),phone text NOT NULL,name text NOT NULL,event_key text NOT NULL,status text NOT NULL DEFAULT 'pending',body text NOT NULL,reward_code text,created_at timestamptz NOT NULL DEFAULT now(),processed_at timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS campaign_delivery_event ON campaign_deliveries(campaign_id,event_key,phone);
CREATE INDEX IF NOT EXISTS campaign_delivery_pending ON campaign_deliveries(status);
CREATE TABLE IF NOT EXISTS customer_balances (phone text PRIMARY KEY,balance bigint NOT NULL DEFAULT 0 CHECK (balance>=0),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customer_credit_entries (id serial PRIMARY KEY,phone text NOT NULL,amount bigint NOT NULL,reference text NOT NULL UNIQUE,note text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS gift_cards (id serial PRIMARY KEY,code text NOT NULL UNIQUE,amount bigint NOT NULL CHECK(amount>0),balance bigint NOT NULL CHECK(balance>=0),buyer_name text NOT NULL,buyer_phone text NOT NULL,target_phone text,message text,payment_method text NOT NULL,settlement jsonb NOT NULL,terminal_id integer,revoked boolean NOT NULL DEFAULT false,created_by integer NOT NULL,idempotency_key text NOT NULL UNIQUE,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS gift_card_entries (id serial PRIMARY KEY,card_id integer NOT NULL REFERENCES gift_cards(id),amount bigint NOT NULL,reference text NOT NULL UNIQUE,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS return_requests (id serial PRIMARY KEY,kind text NOT NULL,sale_id integer NOT NULL,number text NOT NULL,customer_phone text NOT NULL,customer_name text NOT NULL,seller_id integer,reason text NOT NULL,status text NOT NULL DEFAULT 'pending',amount bigint NOT NULL DEFAULT 0,admin_note text,refund_reference text,created_by integer NOT NULL,processed_by integer,created_at timestamptz NOT NULL DEFAULT now(),processed_at timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS return_sale_unique ON return_requests(kind,sale_id);
