import Link from 'next/link';
import { notFound } from 'next/navigation';
import { eq } from 'drizzle-orm';
import { db } from '@/db';
import { inventoryDocuments, users } from '@/db/schema';
import { requirePage } from '@/lib/auth';
import { getSettings } from '@/lib/settings';
import { faNum, jdate, toman } from '@/lib/util';
import { PrintButton } from '@/components/PrintButton';
export const metadata={title:'چاپ سند انبار'};
export default async function Page({params}:{params:Promise<{id:string}>}){
 await requirePage({perm:'INVENTORY_MANAGE'});
 const {id}=await params;if(!/^\d+$/.test(id))notFound();
 const [d]=await db.select().from(inventoryDocuments).where(eq(inventoryDocuments.id,Number(id)));if(!d)notFound();
 const s=await getSettings();
 const [creator]=d.createdBy?await db.select({name:users.name}).from(users).where(eq(users.id,d.createdBy)):[];
 const [receiver]=d.receivedBy?await db.select({name:users.name}).from(users).where(eq(users.id,d.receivedBy)):[];
 const transfer=d.type==='transfer',received=!!d.receivedAt;
 const title=transfer?'حواله انتقال بین انبارها':d.type==='purchase'?'صورتحساب خرید':d.type==='consignment'?'رسید دریافت کالای امانی':'سند تعدیل موجودی';
 return <><div className="no-print mx-auto mb-4 flex max-w-4xl justify-between"><Link className="btn-ghost" href="/admin/inventory/documents">بازگشت</Link><PrintButton label="چاپ سند"/></div><article className="warehouse-document invoice-sheet" dir="rtl"><header><div><h1>{s.siteName}</h1><h2>{title}</h2></div><div>شماره سند: <b dir="ltr">{d.number}</b><br/>تاریخ: {jdate(d.documentDate)}<br/>{received?'پذیرش شده':transfer?'در انتظار پذیرش مقصد':'ثبت شده'}</div></header><section className="info">{transfer?<><p>انبار مبدأ: <b>{d.fromWarehouseName}</b></p><p>انبار مقصد: <b>{d.toWarehouseName}</b></p><p>مسئول انتقال: <b>{d.responsibleName}</b></p><p>تلفن مسئول انتقال: {d.responsiblePhone||'—'}</p></>:<><p>تولیدکننده / صاحب کالا: <b>{d.partyName||'—'}</b></p><p>شماره فاکتور فروشنده: <b>{d.invoiceNumber||'—'}</b></p><p>انبار دریافت‌کننده: {d.toWarehouseName}</p><p>ثبت‌کننده: {creator?.name||'—'}</p></>}</section><table><thead><tr><th>ردیف</th><th>کالا / تنوع و کد</th><th>واحد</th><th>{transfer?'ارسال‌شده':'مقدار'}</th>{transfer?<><th>مشاهده‌شده</th><th>پذیرفته‌شده</th><th>مغایرت / توضیح</th></>:<><th>بهای واحد</th><th>هزینه سهم قلم</th><th>مبلغ کل</th></>}</tr></thead><tbody>{d.items.map((i,index)=><tr key={`${i.productId}:${i.variantId}`}><td>{faNum(index+1)}</td><td><b>{i.title}</b><small dir="ltr">{i.sku}</small></td><td>{i.unit}</td><td>{faNum(i.quantity)}</td>{transfer?<><td>{received?faNum(i.receivedQuantity??0):' '}</td><td>{received?faNum(i.acceptedQuantity??0):' '}</td><td>{received?`${faNum((i.receivedQuantity??0)-i.quantity)} ${i.discrepancyNote||''}`:' '}</td></>:<><td>{toman(i.unitCost)}</td><td>{toman(i.freight+i.customs)}</td><td>{toman(i.total)}</td></>}</tr>)}</tbody></table>{!transfer&&<section className="totals"><p>جمع اقلام: {toman(d.subtotal)}</p><p>حمل: {toman(d.freight)} · سایر هزینه‌ها: {toman(d.customs)}</p><p><b>جمع صورتحساب: {toman(d.total)}</b></p><p>پرداخت اولیه: {toman(d.paidAmount)}</p>{d.type==='purchase'&&<p>مانده هنگام ثبت: {toman(d.total-d.paidAmount)}</p>}<p>محل پرداخت: {d.paymentLocation||'—'} · پیگیری پرداخت: {d.paymentTrackingNumber||'—'}</p></section>}<p className="notes">توضیحات: {d.note||'—'}</p>{received&&<p className="notes">پذیرش توسط {receiver?.name||'—'} در {jdate(d.receivedAt!,true)} — {d.receiptNote||'بدون توضیح'}</p>}{transfer&&<p className="notes">اختلاف تعداد باید هنگام تحویل ثبت و به مسئول انتقال اعلام شود. این برگه به همراه کالا به مقصد ارسال شود.</p>}<footer><div>امضا و مهر {transfer?'تحویل‌دهنده مبدأ':'ثبت‌کننده'}<br/>{creator?.name}</div><div>امضای {transfer?'مسئول انتقال':'صاحب کالا'}<br/>{transfer?d.responsibleName:d.partyName}</div><div>امضا و مهر تحویل‌گیرنده<br/>{receiver?.name}</div></footer></article><style>{`
 @page{size:A4 landscape;margin:12mm} .warehouse-document{background:#fff!important;color:#111!important;width:100%;max-width:1100px;margin:auto;padding:28px;font-size:12px;line-height:1.8;box-sizing:border-box}.warehouse-document *{color:#111!important}.warehouse-document header{display:flex;justify-content:space-between;border-bottom:2px solid #111;padding-bottom:15px}.warehouse-document h1{font-size:22px;font-weight:900}.warehouse-document h2{font-size:17px;font-weight:700}.warehouse-document .info{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:16px 0}.warehouse-document table{width:100%;border-collapse:collapse}.warehouse-document th,.warehouse-document td{border:1px solid #888;padding:8px;text-align:right}.warehouse-document th{background:#eee!important}.warehouse-document small{display:block}.warehouse-document .totals{margin-top:15px;text-align:left}.warehouse-document .notes{margin-top:15px;white-space:pre-wrap}.warehouse-document footer{display:grid;grid-template-columns:repeat(3,1fr);margin-top:24px;gap:16px}.warehouse-document footer div{border:1px solid #aaa;min-height:100px;padding:12px;text-align:center}.warehouse-document tr{break-inside:avoid}.warehouse-document thead{display:table-header-group}@media print{.warehouse-document{padding:0;max-width:none} .warehouse-document footer{break-inside:avoid}}
 `}</style></>;
}
