"use client";
import { JalaliDatePicker } from "@/components/JalaliDatePicker";
import { useMemo, useState, type FormEvent } from "react";
import { Cake, MessageSquare, Plus, Search, Trash2, Users } from "lucide-react";
import { api, toast } from "./client";
import { faNum, jdate, toman } from "@/lib/util";

type Member={id:number;name:string;phone:string;birthdate:string|null;smsConsent:boolean;visits:number;totalSpent:number;lastPurchaseAt:string|null;updatedAt:string};
const todayInTehran=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tehran",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const defaultBirthday="{{name}} عزیز، زادروزتان مبارک! از طرف خانواده سبزینه برای شما سلامتی و شادی آرزو می‌کنیم. 🌱";
export default function AdminLoyaltyClient({initial}:{initial:Member[]}){
 const [members,setMembers]=useState(initial),[tab,setTab]=useState<"members"|"birthday">("members"),[search,setSearch]=useState(""),[name,setName]=useState(""),[phone,setPhone]=useState(""),[birthdate,setBirthdate]=useState(""),[consent,setConsent]=useState(false),[date,setDate]=useState(todayInTehran),[message,setMessage]=useState(defaultBirthday),[preview,setPreview]=useState<{total:number;alreadySent:number;recipients:number;members:{id:number;name:string;phone:string}[]}|null>(null),[busy,setBusy]=useState(false);
 const filtered=useMemo(()=>members.filter(m=>`${m.name} ${m.phone}`.includes(search.trim())),[members,search]);const opted=members.filter(m=>m.smsConsent).length;const withBirthdate=members.filter(m=>m.birthdate).length;
 const refresh=async()=>setMembers(await api<Member[]>("/api/admin/loyalty","GET"));
 const add=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await api("/api/admin/loyalty/members","POST",{name,phone,birthdate:birthdate||null,smsConsent:consent});setName("");setPhone("");setBirthdate("");setConsent(false);toast("عضویت مشتری ثبت شد");await refresh()}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
 const toggle=async(m:Member)=>{try{await api(`/api/admin/loyalty/members/${m.id}/consent`,`POST`,{smsConsent:!m.smsConsent});toast(m.smsConsent?"رضایت پیامکی لغو شد":"رضایت پیامکی ثبت شد");await refresh()}catch(e){toast((e as Error).message,false)}};
 const remove=async(m:Member)=>{if(!window.confirm(`عضویت ${m.name} حذف شود؟`))return;try{await api(`/api/admin/loyalty/members/${m.id}`,"DELETE");toast("عضویت حذف شد");await refresh()}catch(e){toast((e as Error).message,false)}};
 const check=async()=>{setBusy(true);try{setPreview(await api(`/api/admin/loyalty/birthdays?date=${encodeURIComponent(date)}`,"GET"))}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
 const send=async(e:FormEvent)=>{e.preventDefault();if(!preview||!preview.recipients)return toast("گیرنده‌ای برای این تاریخ آماده ارسال نیست",false);if(!window.confirm(`پیام تبریک برای ${faNum(preview.recipients)} مشتری رضایت‌داده ارسال شود؟`))return;setBusy(true);try{const r=await api<{success:number;failed:number;skipped:number}>("/api/admin/loyalty/birthday-campaign","POST",{date,message});toast(`ارسال پایان یافت · موفق ${faNum(r.success)} · ناموفق ${faNum(r.failed)} · تکراری/ردشده ${faNum(r.skipped)}`,r.failed===0);await check()}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
 return <div className="mt-5 space-y-5"><section className="grid gap-3 sm:grid-cols-3">{[[Users,members.length,"عضو باشگاه"],[MessageSquare,opted,"رضایت پیامکی"],[Cake,withBirthdate,"دارای تاریخ تولد"]].map(([Icon,value,label]:any)=><div key={label} className="flex items-center gap-3 rounded-2xl border bg-white p-4"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="size-5"/></span><div><b className="block text-xl">{faNum(value)}</b><small className="text-xs text-slate-500">{label}</small></div></div>)}</section>
 <nav className="flex gap-2"><button onClick={()=>setTab("members")} className={`btn-sm ${tab==="members"?"!bg-emerald-700 !text-white":""}`}><Users className="size-4"/>اعضای باشگاه</button><button onClick={()=>{setTab("birthday");if(!preview)void check()}} className={`btn-sm ${tab==="birthday"?"!bg-emerald-700 !text-white":""}`}><Cake className="size-4"/>پیامک مناسبتی · تولد</button></nav>
 {tab==="members"&&<div className="grid items-start gap-5 xl:grid-cols-[.75fr_1.25fr]"><form onSubmit={add} className="rounded-2xl border bg-white p-5"><h2 className="font-black">افزودن عضو باشگاه</h2><label className="mt-4 block text-xs font-bold">نام مشتری<input required className="input mt-1" value={name} onChange={e=>setName(e.target.value)}/></label><label className="mt-3 block text-xs font-bold">شماره همراه<input required dir="ltr" className="input mt-1" inputMode="numeric" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="0912…"/></label><label className="mt-3 block text-xs font-bold">تاریخ تولد<div className="mt-1"><JalaliDatePicker value={birthdate} onChange={setBirthdate} allowEmpty placeholder="انتخاب تاریخ تولد"/></div></label><label className="mt-3 flex items-start gap-2 text-xs leading-6 text-slate-600"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1 accent-emerald-700"/>مشتری برای پیامک‌های باشگاه و تبریک تولد رضایت داده است</label><button disabled={busy} className="btn-primary mt-4 w-full"><Plus className="size-4"/>ثبت عضو</button></form>
 <section className="rounded-2xl border bg-white p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><h2 className="font-black">فهرست اعضا</h2><div className="relative"><Search className="absolute right-3 top-2.5 size-4 text-slate-400"/><input className="input h-9 w-52 pr-9" placeholder="جست‌وجوی نام یا تلفن" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[670px] text-right text-xs"><thead><tr className="border-b text-slate-500"><th className="p-3">مشتری</th><th className="p-3">تولد</th><th className="p-3">مراجعه</th><th className="p-3">مجموع خرید حضوری</th><th className="p-3">پیامک</th><th/></tr></thead><tbody>{filtered.map(m=><tr key={m.id} className="border-b last:border-0"><td className="p-3 font-bold">{m.name}<span dir="ltr" className="mt-1 block font-normal text-slate-500">{m.phone}</span></td><td className="p-3">{m.birthdate?jdate(m.birthdate):"—"}</td><td className="p-3">{faNum(m.visits)}</td><td className="p-3">{toman(m.totalSpent)}</td><td className="p-3"><button onClick={()=>toggle(m)} className={m.smsConsent?"font-bold text-emerald-700":"text-slate-400"}>{m.smsConsent?"رضایت ثبت شده":"بدون رضایت"}</button></td><td className="p-3"><button onClick={()=>remove(m)} aria-label={`حذف ${m.name}`} className="text-rose-600"><Trash2 className="size-4"/></button></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-8 text-center text-sm text-slate-500">عضوی پیدا نشد.</p>}</div></section></div>}
 {tab==="birthday"&&<form onSubmit={send} className="max-w-3xl rounded-2xl border bg-white p-5"><div className="flex items-start gap-3"><Cake className="mt-1 size-5 text-emerald-700"/><div><h2 className="font-black">ارسال پیام تبریک تولد</h2><p className="mt-1 text-xs leading-6 text-slate-500">گیرندگان فقط اعضای دارای تاریخ تولد و رضایت پیامکی هستند. برای جلوگیری از ارسال تکراری، برای هر عضو و هر تاریخ فقط یک بار ارسال ثبت می‌شود.</p></div></div><label className="mt-4 block max-w-xs text-xs font-bold">تاریخ تولد موردنظر<div className="mt-1"><JalaliDatePicker value={date} onChange={v=>{setDate(v);setPreview(null)}}/></div></label><label className="mt-4 block text-xs font-bold">متن پیام<textarea required maxLength={800} className="input mt-1 min-h-28 leading-7" value={message} onChange={e=>setMessage(e.target.value)}/></label><p className="mt-2 text-[11px] text-slate-500">متغیر قابل استفاده: <code dir="ltr">{"{{name}}"}</code> نام مشتری</p><div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" onClick={check} disabled={busy} className="btn-sm">بررسی گیرندگان</button>{preview&&<span className="text-xs text-slate-600">تولد این تاریخ: {faNum(preview.total)} · ارسال‌نشده: {faNum(preview.recipients)} · قبلاً ارسال‌شده: {faNum(preview.alreadySent)}</span>}</div><button disabled={busy||!preview?.recipients} className="btn-primary mt-4"><MessageSquare className="size-4"/>{busy?"در حال ارسال…":"ارسال پیامک تولد"}</button></form>}
 </div>;
}
