"use client";
import { useState, type FormEvent } from "react";
import { Search, X, Plus } from "lucide-react";
import { useRouter } from "next/navigation";
import { api, toast } from "./client";
type Customer={id:number;name:string;phone:string};
export function AdminTicketCreate({departments}:{departments:{key:string;name:string}[]}){
 const router=useRouter();const [open,setOpen]=useState(false),[query,setQuery]=useState(""),[customers,setCustomers]=useState<Customer[]>([]),[customer,setCustomer]=useState<Customer|null>(null),[busy,setBusy]=useState(false);
 async function search(value:string){setQuery(value);setCustomer(null);if(value.trim().length<2){setCustomers([]);return}try{setCustomers(await api<Customer[]>(`/api/admin/tickets/customers?q=${encodeURIComponent(value)}`,"GET"))}catch(e){toast((e as Error).message,false)}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!customer)return toast("ابتدا مشتری را انتخاب کنید",false);setBusy(true);const f=new FormData(e.currentTarget);try{const r=await api<{id:number}>("/api/admin/tickets","POST",{customerId:customer.id,subject:f.get("subject"),message:f.get("message"),department:f.get("department"),priority:f.get("priority")});toast("تیکت برای مشتری ایجاد شد");setOpen(false);router.push(`/admin/tickets/${r.id}`);router.refresh()}catch(err){toast((err as Error).message,false)}finally{setBusy(false)}}
 return <><button className="btn-primary" onClick={()=>setOpen(true)}><Plus className="size-4"/>ایجاد تیکت</button>{open&&<div className="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto bg-slate-950/50 p-3 sm:items-center"><form onSubmit={submit} className="modal-scroll-panel my-auto w-full max-w-xl space-y-3 rounded-2xl bg-white p-5 shadow-2xl"><header className="flex items-center justify-between"><h2 className="font-black">ایجاد تیکت برای مشتری</h2><button type="button" onClick={()=>setOpen(false)} className="btn-ghost"><X className="size-4"/></button></header><label className="relative block text-xs font-bold">جست‌وجوی مشتری<input value={query} onChange={e=>void search(e.target.value)} className="input mt-1 pr-9" placeholder="نام یا شماره همراه"/><Search className="absolute right-3 top-9 size-4 text-slate-400"/></label>{customers.length>0&&!customer&&<div className="max-h-36 overflow-y-auto rounded-lg border">{customers.map(c=><button type="button" key={c.id} onClick={()=>{setCustomer(c);setQuery(`${c.name} · ${c.phone}`);setCustomers([])}} className="block w-full border-b p-2 text-right text-sm hover:bg-emerald-50">{c.name}<span className="mr-2 text-slate-500" dir="ltr">{c.phone}</span></button>)}</div>}{customer&&<p className="text-xs text-emerald-700">مشتری: {customer.name} · {customer.phone}</p>}<label className="block text-xs font-bold">موضوع<input name="subject" required minLength={3} className="input mt-1"/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold">دپارتمان<select name="department" className="input mt-1">{departments.map(d=><option key={d.key} value={d.key}>{d.name}</option>)}</select></label><label className="text-xs font-bold">اولویت<select name="priority" className="input mt-1"><option value="normal">عادی</option><option value="low">کم</option><option value="high">زیاد</option><option value="urgent">فوری</option></select></label></div><label className="block text-xs font-bold">متن پیام<textarea name="message" required minLength={5} className="input mt-1 min-h-28"/></label><div className="flex justify-end gap-2"><button type="button" className="btn-ghost" onClick={()=>setOpen(false)}>انصراف</button><button disabled={busy||!customer} className="btn-primary">{busy?"در حال ثبت…":"ایجاد تیکت"}</button></div></form></div>}</>;
}
