"use client";
import { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import { Heart, MapPin, Copy, Wallet, Trash2, Star, Loader2 } from "lucide-react";
import { api, toast } from "./client";
import { Card, PageHeader } from "./ui";

const toman = (n: number) => `${Number(n || 0).toLocaleString("fa-IR")} تومان`;
const MapPicker = dynamic(() => import("./MapPicker"), { ssr: false, loading: () => <div className="skeleton h-64 rounded-xl" /> });
let favoriteIdsRequest: Promise<number[]> | null = null;

type Address = { id:number; title:string; receiverName:string; receiverPhone:string; city:string; address:string; postalCode:string|null; latitude:string|null; longitude:string|null; isDefault:boolean };

export function AddressManager({ initial }: { initial: Address[] }) {
  const [rows,setRows]=useState(initial),[busy,setBusy]=useState(false),[edit,setEdit]=useState<Address|null>(null),[loc,setLoc]=useState<[number,number]>([35.6892,51.389]);
  const blank:Address={id:0,title:"خانه",receiverName:"",receiverPhone:"",city:"تهران",address:"",postalCode:"",latitude:"",longitude:"",isDefault:rows.length===0};
  const start=(a?:Address)=>{const v=a??blank;setEdit(v);setLoc([Number(v.latitude)||35.6892,Number(v.longitude)||51.389]);};
  const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const payload=Object.fromEntries(f);payload.latitude=String(loc[0]);payload.longitude=String(loc[1]);try{const row=await api<Address>(edit?.id?`/api/customer/addresses/${edit.id}`:"/api/customer/addresses",edit?.id?"PUT":"POST",payload);setRows(x=>edit?.id?x.map(a=>a.id===row.id?row:a):[row,...x].map(a=>row.isDefault?{...a,isDefault:a.id===row.id}:a));setEdit(null);toast("نشانی ذخیره شد");}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
  const remove=async(id:number)=>{try{await api(`/api/customer/addresses/${id}`,"DELETE",{});setRows(x=>x.filter(a=>a.id!==id));toast("نشانی حذف شد")}catch(e){toast((e as Error).message,false)}};
  return <div className="space-y-5"><PageHeader title="آدرس‌های من" subtitle="نشانی‌های ذخیره‌شده برای تکمیل سریع‌تر سفارش" actions={<button onClick={()=>start()} className="btn-primary">افزودن آدرس</button>}/>{edit&&<Card title={edit.id?"ویرایش نشانی":"نشانی جدید"}><form key={edit.id||"new"} onSubmit={save} className="grid gap-3 md:grid-cols-2"><input name="title" defaultValue={edit.title} className="input" placeholder="عنوان مثل خانه یا محل کار" required/><input name="receiverName" defaultValue={edit.receiverName} className="input" placeholder="نام تحویل‌گیرنده" required/><input name="receiverPhone" defaultValue={edit.receiverPhone} className="input" placeholder="موبایل تحویل‌گیرنده" required/><input name="city" defaultValue={edit.city} className="input" placeholder="شهر" required/><input name="postalCode" defaultValue={edit.postalCode??""} className="input" placeholder="کد پستی"/><textarea name="address" defaultValue={edit.address} className="input min-h-24 md:col-span-2" placeholder="نشانی کامل" required minLength={8}/><div className="md:col-span-2"><div className="mb-2 text-sm font-bold">موقعیت روی نقشه را انتخاب کنید</div><MapPicker value={loc} onChange={setLoc}/><div className="mt-1 text-xs text-slate-500">مختصات: {loc[0].toFixed(5)}, {loc[1].toFixed(5)}</div></div><label className="flex items-center gap-2 text-sm md:col-span-2"><input type="checkbox" name="isDefault" value="true" defaultChecked={edit.isDefault}/> نشانی پیش‌فرض من باشد</label><div className="flex gap-2 md:col-span-2"><button disabled={busy} className="btn-primary">{busy&&<Loader2 className="h-4 w-4 animate-spin"/>}ذخیره نشانی</button><button type="button" className="btn-ghost" onClick={()=>setEdit(null)}>انصراف</button></div></form></Card>}
    {!rows.length?<Card><div className="py-8 text-center text-sm text-slate-500">هنوز نشانی ذخیره‌شده‌ای ندارید.</div></Card>:<div className="grid gap-3 md:grid-cols-2">{rows.map(a=><Card key={a.id} className="relative"><div className="flex items-start gap-3"><span className="rounded-xl bg-emerald-50 p-3 text-emerald-700"><MapPin/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2 font-bold">{a.title}{a.isDefault&&<span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] text-emerald-700">پیش‌فرض</span>}</div><div className="mt-1 text-sm text-slate-600">{a.city}، {a.address}</div><div className="mt-1 text-xs text-slate-500">{a.receiverName} · {a.receiverPhone}</div>{a.latitude&&a.longitude&&<a className="mt-2 inline-block text-xs text-emerald-700 underline" target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${a.latitude}&mlon=${a.longitude}#map=16/${a.latitude}/${a.longitude}`}>مشاهده موقعیت</a>}</div></div><div className="mt-4 flex gap-2 border-t pt-3"><button onClick={()=>start(a)} className="btn-sm">ویرایش</button><button onClick={()=>remove(a.id)} className="btn-sm text-rose-600"><Trash2 className="h-3.5 w-3.5"/>حذف</button></div></Card>)}</div>}</div>
}

export function WalletPanel({ initial }: { initial: {balance:number;bankInfo:Record<string,string>;points:number;pointValue:number;entries:{id:number;amount:number;type:string;description:string;createdAt:string}[]} }) {
  const [data,setData]=useState(initial),[amount,setAmount]=useState("500000"),[withdrawAmount,setWithdrawAmount]=useState(""),[busy,setBusy]=useState(false);
  const saveBank=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.currentTarget));try{await api("/api/customer/wallet/bank","PUT",payload);toast("اطلاعات حساب بانکی ذخیره شد")}catch(e){toast((e as Error).message,false)}};
  const charge=async()=>{setBusy(true);try{const r=await api<{url:string}>("/api/customer/wallet/gateway","POST",{amount:Number(amount)});window.location.href=r.url}catch(e){toast((e as Error).message,false);setBusy(false)}};
  const convert=async()=>{try{const r=await api<{added:number}>("/api/customer/wallet/convert-points","POST",{points:"all"});const fresh=await api<typeof data>("/api/customer/wallet","GET");setData(fresh);toast(`${toman(r.added)} به کیف پول اضافه شد`)}catch(e){toast((e as Error).message,false)}};
  const withdraw=async()=>{try{await api("/api/customer/wallet/withdraw","POST",{amount:Number(withdrawAmount)});const fresh=await api<typeof data>("/api/customer/wallet","GET");setData(fresh);setWithdrawAmount("");toast("درخواست برداشت برای بررسی ثبت شد")}catch(e){toast((e as Error).message,false)}};
  return <div className="space-y-5"><PageHeader title="کیف پول و حساب بانکی" subtitle="اعتبار کیف پول، گردش حساب و اطلاعات واریز"/><div className="grid gap-4 md:grid-cols-3"><Card className="bg-gradient-to-br from-emerald-700 to-emerald-500 text-white"><div className="flex items-center gap-3"><Wallet/><div><div className="text-sm opacity-80">موجودی کیف پول</div><b className="text-2xl">{toman(data.balance)}</b></div></div><div className="mt-5 flex gap-2"><input value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,""))} className="input min-w-0 bg-white text-slate-900" inputMode="numeric" placeholder="مبلغ شارژ به تومان"/><button onClick={charge} disabled={busy} className="rounded-xl bg-white px-3 font-bold text-emerald-800">{busy?"…":"شارژ"}</button></div><div className="mt-2 text-[11px] text-white/80">حداقل شارژ ۱۰٬۰۰۰ تومان · پرداخت از درگاه فعال سایت</div><div className="mt-4 flex gap-2 border-t border-white/20 pt-3"><input value={withdrawAmount} onChange={e=>setWithdrawAmount(e.target.value.replace(/\D/g,""))} className="input min-w-0 bg-white text-slate-900" inputMode="numeric" placeholder="مبلغ برداشت"/><button onClick={withdraw} className="rounded-xl border border-white/70 px-3 text-sm font-bold">درخواست برداشت</button></div><div className="mt-1 text-[10px] text-white/80">حداقل ۱۰۰٬۰۰۰ تومان؛ نیازمند ثبت حساب بانکی</div></Card><Card title="امتیاز بازاریابی"><div className="text-3xl font-black text-amber-600">{Number(data.points).toLocaleString("fa-IR")} <span className="text-sm">امتیاز</span></div><p className="mt-2 text-xs text-slate-500">هر امتیاز معادل {toman(data.pointValue)} اعتبار کیف پول است.</p><button disabled={!data.points} onClick={convert} className="btn-primary mt-4">تبدیل امتیاز به کیف پول</button></Card><Card title="گردش کیف پول"><div className="max-h-44 space-y-2 overflow-auto">{data.entries.length?data.entries.map(x=><div key={x.id} className="flex justify-between gap-2 border-b pb-2 text-xs"><span>{x.description}</span><b className={x.amount<0?"text-rose-600":"text-emerald-700"}>{x.amount>0?"+":""}{toman(x.amount)}</b></div>):<p className="text-sm text-slate-400">تراکنشی ثبت نشده است.</p>}</div></Card></div><Card title="اطلاعات حساب بانکی"><p className="mb-4 text-xs text-slate-500">برای برداشت وجه یا تطبیق پرداخت‌ها، مشخصات حساب به نام خود را وارد کنید.</p><form onSubmit={saveBank} className="grid gap-3 md:grid-cols-2"><input name="accountHolder" defaultValue={data.bankInfo.accountHolder??""} className="input" placeholder="نام صاحب حساب"/><input name="bankName" defaultValue={data.bankInfo.bankName??""} className="input" placeholder="نام بانک"/><input name="cardNumber" defaultValue={data.bankInfo.cardNumber??""} className="input" placeholder="شماره کارت ۱۶ رقمی" dir="ltr"/><input name="iban" defaultValue={data.bankInfo.iban??""} className="input" placeholder="شماره شبا IR..." dir="ltr"/><button className="btn-primary md:col-span-2 md:w-fit">ذخیره اطلاعات بانکی</button></form></Card></div>
}

export function ReferralPanel({ initial }: { initial:{code:string;points:number;pointValue:number;referrals:{id:number;name:string;createdAt:string}[]} }) {
  const [data,setData]=useState(initial),link=`/login?ref=${data.code}`;
  const copy=async()=>{await navigator.clipboard.writeText(new URL(link,window.location.origin).toString());toast("لینک دعوت کپی شد")};
  return <div className="space-y-5"><PageHeader title="دعوت دوستان و امتیاز بازاریابی" subtitle="با خرید موفق دوستانی که دعوت می‌کنید، امتیاز دریافت کنید"/><div className="grid gap-4 md:grid-cols-3"><Card className="md:col-span-2" title="لینک اختصاصی دعوت"><p className="mb-3 text-sm text-slate-500">۵٪ مبلغ هر سفارش پرداخت‌شده دوستان شما، به ازای هر ۱٬۰۰۰ تومان یک امتیاز می‌شود.</p><div className="flex gap-2"><input readOnly value={link} dir="ltr" className="input min-w-0"/><button onClick={copy} className="btn-primary shrink-0"><Copy className="h-4 w-4"/>کپی لینک</button></div><p className="mt-2 text-xs text-slate-400">کد دعوت شما: <b dir="ltr">{data.code}</b></p></Card><Card title="امتیاز شما"><div className="flex items-center gap-3"><Star className="h-8 w-8 fill-amber-400 text-amber-500"/><b className="text-3xl">{Number(data.points).toLocaleString("fa-IR")}</b></div><Link href="/customer/wallet" className="mt-4 inline-block text-sm font-bold text-emerald-700 underline">تبدیل امتیاز در کیف پول</Link></Card></div><Card title={`دوستان دعوت‌شده (${data.referrals.length.toLocaleString("fa-IR")})`}>{data.referrals.length?data.referrals.map(u=><div key={u.id} className="flex items-center gap-3 border-b py-3 last:border-0"><span className="rounded-full bg-emerald-100 p-2 text-emerald-700"><Heart className="h-4 w-4"/></span><div><b className="text-sm">{u.name}</b><div className="text-xs text-slate-500">عضویت {new Date(u.createdAt).toLocaleDateString("fa-IR")}</div></div></div>):<p className="py-5 text-center text-sm text-slate-500">هنوز دوستی با لینک شما ثبت‌نام نکرده است.</p>}</Card></div>
}

export function FavoriteButton({ productId }: { productId:number }) {
  const [favorite,setFavorite]=useState(false),[ready,setReady]=useState(false),[busy,setBusy]=useState(false);
  useEffect(()=>{favoriteIdsRequest??=api<{id:number}[]>("/api/customer/favorites","GET").then(x=>x.map(p=>p.id));favoriteIdsRequest.then(ids=>setFavorite(ids.includes(productId))).catch(()=>{}).finally(()=>setReady(true))},[productId]);
  return <button aria-label={favorite?"حذف از علاقه‌مندی‌ها":"افزودن به علاقه‌مندی‌ها"} aria-pressed={favorite} title={favorite?"در علاقه‌مندی‌ها":"افزودن به علاقه‌مندی‌ها"} disabled={busy} onClick={async e=>{e.preventDefault();e.stopPropagation();setBusy(true);try{const r=await api<{favorited:boolean}>("/api/customer/favorites","POST",{productId});setFavorite(r.favorited);favoriteIdsRequest=null;toast(r.favorited?"به علاقه‌مندی‌ها اضافه شد":"از علاقه‌مندی‌ها حذف شد")}catch(err){toast((err as Error).message,false)}finally{setBusy(false)}}} className={`grid size-10 place-items-center rounded-full border border-slate-200 bg-white/95 shadow-md backdrop-blur transition hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-500 ${favorite?"text-rose-600":"text-slate-500"}`}><Heart className={`size-5 ${favorite?"fill-rose-500":""}`}/></button>
}

export function FavoritesGrid({ initial }: {initial: {id:number;slug:string;nameFa:string;mainImageId:number|null;brand:string;basePrice:number}[]}) {
  const [rows,setRows]=useState(initial);
  const remove=async(productId:number)=>{try{await api("/api/customer/favorites","POST",{productId});setRows(x=>x.filter(p=>p.id!==productId))}catch(e){toast((e as Error).message,false)}};
  return <div className="space-y-5"><PageHeader title="علاقه‌مندی‌های من" subtitle="محصولاتی که برای خرید بعدی ذخیره کرده‌اید"/>{rows.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{rows.map(p=><Card key={p.id} className="overflow-hidden !p-0"><Link href={`/products/${p.slug}`}><div className="aspect-square bg-slate-50">{p.mainImageId&&<img className="h-full w-full object-cover" src={`/api/media/${p.mainImageId}`} alt={p.nameFa}/>}</div><div className="p-4"><div className="text-xs text-emerald-700">{p.brand}</div><b className="mt-1 line-clamp-2 block min-h-10">{p.nameFa}</b><div className="mt-2 text-sm font-black">{p.basePrice? toman(p.basePrice):"مشاهده قیمت"}</div></div></Link><button onClick={()=>remove(p.id)} className="m-3 mt-0 flex items-center gap-1 text-xs text-rose-600"><Trash2 className="h-3.5 w-3.5"/>حذف از علاقه‌مندی‌ها</button></Card>)}</div>:<Card><div className="py-10 text-center text-sm text-slate-500">هنوز محصولی ذخیره نکرده‌اید. <Link href="/shop" className="text-emerald-700 underline">مشاهده فروشگاه</Link></div></Card>}</div>
}
