"use client";
import { useState, type FormEvent } from "react";
import { JalaliDatePicker } from "@/components/JalaliDatePicker";
import { api, toast } from "./client";
export type CustomerIdentity={name:string;email:string|null;birthdate:string|null;nationalId:string|null;smsConsent:boolean;companyName:string|null;companyNationalId:string|null;companyManager:string|null};
export function CustomerIdentityForm({initial,onSaved,submitLabel="ذخیره اطلاعات"}:{initial:CustomerIdentity;onSaved?:(value:CustomerIdentity)=>void;submitLabel?:string}){
 const [form,setForm]=useState(initial),[birthdate,setBirthdate]=useState(initial.birthdate?.slice(0,10)??""),[busy,setBusy]=useState(false);
 const set=(key:keyof CustomerIdentity,value:string|boolean|null)=>setForm(old=>({...old,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await api("/api/me/profile","POST",{...form,birthdate:birthdate||null});const next={...form,birthdate:birthdate||null};setForm(next);onSaved?.(next);toast("اطلاعات پروفایل ذخیره شد")}catch(error){toast((error as Error).message,false)}finally{setBusy(false)}}
 return <form onSubmit={submit} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">نام و نام خانوادگی<input required className="input mt-1" value={form.name} onChange={e=>set("name",e.target.value)}/></label><label className="text-sm">ایمیل<input type="email" dir="ltr" className="input mt-1" value={form.email??""} onChange={e=>set("email",e.target.value||null)}/></label><label className="text-sm">تاریخ تولد (شمسی)<div className="mt-1"><JalaliDatePicker value={birthdate} onChange={setBirthdate} allowEmpty/></div></label><label className="text-sm">کد ملی<input inputMode="numeric" dir="ltr" maxLength={10} className="input mt-1" value={form.nationalId??""} onChange={e=>set("nationalId",e.target.value)}/></label></div><label className="flex items-start gap-2 text-xs leading-6 text-slate-600"><input type="checkbox" checked={form.smsConsent} onChange={e=>set("smsConsent",e.target.checked)} className="mt-1 accent-emerald-700"/>مایلم پیامک‌های مناسبتی و باشگاه مشتریان، از جمله هدیه تولد، را دریافت کنم.</label><section className="space-y-3 rounded-xl border border-slate-200 p-4"><div><b className="text-sm">اطلاعات شخص حقوقی (اختیاری)</b><p className="mt-1 text-xs text-slate-500">برای صدور صورتحساب رسمی شرکت، این موارد را تکمیل کنید.</p></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">نام شرکت<input className="input mt-1" value={form.companyName??""} onChange={e=>set("companyName",e.target.value||null)}/></label><label className="text-sm">شناسه ملی شرکت<input inputMode="numeric" dir="ltr" maxLength={11} className="input mt-1" value={form.companyNationalId??""} onChange={e=>set("companyNationalId",e.target.value)}/></label><label className="text-sm sm:col-span-2">نام مدیرعامل<input className="input mt-1" value={form.companyManager??""} onChange={e=>set("companyManager",e.target.value||null)}/></label></div></section><button disabled={busy} className="btn-primary">{busy?"در حال ذخیره…":submitLabel}</button></form>;
}
