"use client";
import { useMemo, useState, type FormEvent } from "react";
import { Search, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { api, toast } from "./client";
import { JalaliDatePicker } from "./JalaliDatePicker";

type Product = {id:number; name:string; sku:string};
export function FestivalCreateForm({ products, categories }: { products:Product[]; categories:{id:number;name:string}[] }) {
  const router=useRouter();const [selected,setSelected]=useState<number[]>([]);const [open,setOpen]=useState(false);const [search,setSearch]=useState("");const [busy,setBusy]=useState(false);const [startsAt,setStartsAt]=useState("");const [endsAt,setEndsAt]=useState("");
  const filtered=useMemo(()=>products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(search.trim().toLowerCase())).slice(0,100),[products,search]);
  const toggle=(id:number)=>setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);if(!startsAt||!endsAt)return toast("تاریخ شروع و پایان جشنواره را انتخاب کنید",false);if(endsAt<startsAt)return toast("تاریخ پایان نباید پیش از شروع باشد",false);setBusy(true);try{await api("/api/admin/festivals","POST",{title:fd.get("title"),description:fd.get("description"),discountPercent:Number(fd.get("discountPercent")),color:fd.get("color"),startsAt,endsAt,categoryIds:fd.get("categoryId")?[Number(fd.get("categoryId"))]:[],productIds:selected});toast("جشنواره ایجاد شد");router.refresh();e.currentTarget.reset();setSelected([]);setStartsAt("");setEndsAt("")}catch(err){toast((err as Error).message,false)}finally{setBusy(false)}}
  return <><form onSubmit={submit} className="space-y-3">
    <label className="block text-xs font-bold">عنوان<input name="title" required className="input mt-1" placeholder="جشنواره یلدا"/></label>
    <label className="block text-xs font-bold">توضیح کوتاه<input name="description" className="input mt-1"/></label>
    <div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold">درصد تخفیف<input name="discountPercent" type="number" min="1" max="90" required className="input mt-1"/></label><label className="text-xs font-bold">رنگ<input name="color" type="color" defaultValue="#e11d48" className="input mt-1 h-10"/></label><label className="text-xs font-bold">شروع<div className="mt-1"><JalaliDatePicker name="startsAt" value={startsAt} onChange={setStartsAt} allowEmpty placeholder="انتخاب تاریخ شروع"/></div></label><label className="text-xs font-bold">پایان<div className="mt-1"><JalaliDatePicker name="endsAt" value={endsAt} onChange={setEndsAt} allowEmpty placeholder="انتخاب تاریخ پایان"/></div></label></div>
    <label className="block text-xs font-bold">دسته‌بندی (اختیاری)<select name="categoryId" className="input mt-1"><option value="">— همه دسته‌ها —</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
    <div className="rounded-xl border border-slate-200 p-3"><div className="flex items-center justify-between gap-2"><span className="text-xs font-bold">محصولات منتخب</span><button type="button" className="btn-sm" onClick={()=>setOpen(true)}>انتخاب محصول ({selected.length})</button></div>{selected.length>0&&<p className="mt-2 text-xs text-slate-500">{selected.map(id=>products.find(p=>p.id===id)?.name).filter(Boolean).join("، ")}</p>}<input type="hidden" name="productIds" value={selected.join(",")}/></div>
    <button disabled={busy} className="btn-primary w-full">{busy?"در حال ثبت…":"ایجاد جشنواره"}</button>
  </form>
  {open&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/50 p-3" role="dialog" aria-modal="true" aria-label="انتخاب محصولات"><section className="flex max-h-[85vh] w-full max-w-xl flex-col rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b p-4"><b>انتخاب محصولات جشنواره</b><button onClick={()=>setOpen(false)} aria-label="بستن" className="btn-ghost"><X className="size-4"/></button></header><div className="p-4"><div className="relative"><Search className="absolute right-3 top-3 size-4 text-slate-400"/><input autoFocus className="input pr-9" placeholder="جست‌وجوی نام یا کد محصول" value={search} onChange={e=>setSearch(e.target.value)}/></div><p className="mt-2 text-xs text-slate-500">انتخاب‌شده: {selected.length} محصول</p></div><div className="min-h-0 flex-1 overflow-y-auto px-4">{filtered.map(p=><label key={p.id} className="flex cursor-pointer items-center gap-3 border-b py-3 text-sm"><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)} className="accent-emerald-700"/><span className="flex-1">{p.name}<small className="block text-slate-400" dir="ltr">{p.sku}</small></span></label>)}{!filtered.length&&<p className="py-8 text-center text-sm text-slate-500">محصولی پیدا نشد.</p>}</div><footer className="flex justify-between border-t p-4"><button onClick={()=>setSelected([])} className="btn-ghost">پاک‌کردن انتخاب</button><button onClick={()=>setOpen(false)} className="btn-primary">تأیید انتخاب</button></footer></section></div>}</>;
}
