"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowDown, ArrowUp, Plus, Trash2, Copy, Save, Monitor, Smartphone, Undo2, Code2, LayoutPanelTop } from "lucide-react";
import { api, toast, uid, ImageUploader } from "./client";
import { FooterLayout } from "./FooterLayout";
import { footerTypeLabels, type FooterConfig, type FooterBlock, type FooterColumn, type FooterSection, type FooterBrandData, type FooterItemType } from "@/lib/footer-builder";

const makeItem = (type: FooterItemType): FooterBlock => ({ id: uid(), type, enabled: true, title: "", content: "", href: "", src: "", alt: "", width: 120, height: 120, newTab: false });
const makeColumn = (): FooterColumn => ({ id: uid(), title: "", align: "right", layout: "stack", items: [] });
function moved<T>(list: T[], index: number, delta: number) { const next = [...list]; if (index + delta >= 0 && index + delta < next.length) [next[index], next[index + delta]] = [next[index + delta], next[index]]; return next; }
export function FooterBuilder({ initial, initialRevision, brand }: { initial: FooterConfig; initialRevision: number; brand: FooterBrandData }) {
  const [config, setConfig] = useState(initial), [revision, setRevision] = useState(initialRevision);
  const [error, setError] = useState("");
  const [saved, setSaved] = useState(JSON.stringify(initial)), [busy, setBusy] = useState(false);
  const [history, setHistory] = useState<FooterConfig[]>([]), [active, setActive] = useState<string | null>(null);
  const [mobile, setMobile] = useState(false), [tab, setTab] = useState<"edit" | "preview">("edit");
  const [previewDark, setPreviewDark] = useState(false);
  const inspector = useRef<HTMLElement>(null);
  useEffect(() => { const root = document.documentElement; const sync = () => setPreviewDark(root.getAttribute("data-theme") === "dark"); sync(); const observer = new MutationObserver(sync); observer.observe(root, { attributes: true, attributeFilter: ["data-theme"] }); return () => observer.disconnect(); }, []);
  useEffect(() => { if (active && window.matchMedia("(max-width: 1279px)").matches) inspector.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }, [active]);
  const dirty = JSON.stringify(config) !== saved;
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (dirty) { e.preventDefault(); e.returnValue = ""; } }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  const change = (fn: (c: FooterConfig) => void) => { const next = structuredClone(config); fn(next); setHistory(h => [...h.slice(-19), config]); setConfig(next); };
  const item = config.sections.flatMap(s => s.columns.flatMap(c => c.items)).find(i => i.id === active);
  const patchItem = (patch: Partial<FooterBlock>) => change(c => { const i = c.sections.flatMap(s => s.columns.flatMap(col => col.items)).find(i => i.id === active); if (i) Object.assign(i, patch); });
  const publish = async () => { setError(""); setBusy(true); try { const value = await api<{config: FooterConfig; revision: number}>("/api/admin/footer-builder", "POST", { config, revision }); setConfig(value.config); setRevision(value.revision); setSaved(JSON.stringify(value.config)); setHistory([]); toast("فوتر ذخیره و در سایت منتشر شد"); } catch(e) { setError((e as Error).message); toast((e as Error).message, false); } finally { setBusy(false); } };
  const addSection = (template = false) => change(c => {
    if (c.sections.length >= 16) return;
    const section: FooterSection = { id: uid(), title: "", enabled: true, border: true, columns: [makeColumn()] };
    if (template) {
      section.title = "همراه شما";
      section.columns = ["راهنمای خرید", "درباره فروشگاه", "مجوزها و نشان‌ها", "شبکه‌های اجتماعی و اپلیکیشن"].map(title => ({ ...makeColumn(), title }));
      section.columns[0].items = [ { ...makeItem("link"), title: "پرسش‌های متداول", href: "/faq" }, { ...makeItem("link"), title: "شرایط استفاده", href: "/terms" } ];
      section.columns[1].items = [ { ...makeItem("link"), title: "درباره ما", href: "/about" }, { ...makeItem("link"), title: "تماس با ما", href: "/contact" } ];
      section.columns[2].layout = "row";
    }
    c.sections.push(section);
  });
  const orderButtons = (index: number, count: number, move: (delta: number) => void, remove: () => void, name: string) => <div className="flex shrink-0 gap-1"><button type="button" className="btn-sm" aria-label={`بالا بردن ${name}`} disabled={index === 0} onClick={() => move(-1)}><ArrowUp size={14}/></button><button type="button" className="btn-sm" aria-label={`پایین بردن ${name}`} disabled={index === count - 1} onClick={() => move(1)}><ArrowDown size={14}/></button><button type="button" className="btn-sm text-rose-600" aria-label={`حذف ${name}`} onClick={remove}><Trash2 size={14}/></button></div>;
  return <div className="space-y-5">
    <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950 dark:border-amber-900 dark:bg-amber-950/20 dark:text-amber-100"><div className="flex items-center gap-2 font-black"><LayoutPanelTop size={22}/>فوتر، مطابق چیدمان شما</div><p className="mt-2 text-sm leading-7">بخش بسازید، ستون اضافه کنید و داخل هر ستون متن، تصویر، پیوند یا HTML قرار دهید. نام و اطلاعات تماس فروشگاه از تنظیمات عمومی خوانده می‌شود. تغییرات پس از «ذخیره و انتشار» در سایت دیده می‌شوند.</p></div>
    <div className="sticky top-20 z-20 flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-3 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap gap-2"><button className={tab === "edit" ? "btn-primary" : "btn"} onClick={() => setTab("edit")}>ویرایش چیدمان</button><button className={tab === "preview" ? "btn-primary" : "btn"} onClick={() => setTab("preview")}>پیش‌نمایش</button><button className="btn" disabled={!history.length || busy} onClick={() => { setConfig(history[history.length - 1]); setHistory(h => h.slice(0, -1)); }}><Undo2 size={16}/>برگشت تغییر</button></div><div className="flex flex-wrap items-center gap-3"><Link href="/#site-footer" target="_blank" className="btn">مشاهده در سایت</Link><small className="text-slate-500">{dirty ? "تغییرات ذخیره‌نشده" : revision ? "ذخیره‌شده" : "چیدمان اولیه از فوتر فعلی"}</small><button className="btn-primary" disabled={busy} onClick={() => void publish()}><Save size={16}/>{busy ? "در حال ذخیره…" : "ذخیره و انتشار"}</button></div></div>
    {error && <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-200">{error}</p>}
    <fieldset disabled={busy} className="min-w-0 space-y-5">
      <div className="grid gap-4 rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-900 sm:grid-cols-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={config.enabled} onChange={e => change(c => { c.enabled = e.target.checked; })}/>استفاده از فوترساز در سایت</label><label className="text-sm">پوسته<select className="input mt-2" value={config.theme} onChange={e => change(c => { c.theme = e.target.value as FooterConfig["theme"]; })}><option value="system">هماهنگ با روشن / دارک سایت</option><option value="light">روشن</option><option value="dark">تیره</option></select></label><label className="text-sm">متن حقوق سایت<input className="input mt-2" value={config.copyright} onChange={e => change(c => { c.copyright = e.target.value; })}/></label></div>
      {!config.enabled && <p className="text-sm text-amber-700 dark:text-amber-300">با انتشار این وضعیت، فوتر قبلی با منوهای ذخیره‌شده نمایش داده می‌شود.</p>}
      {tab === "preview" ? <section className="space-y-3"><div className="flex items-center gap-2"><button className="btn" onClick={() => setMobile(false)} aria-pressed={!mobile}><Monitor size={16}/>دسکتاپ</button><button className="btn" onClick={() => setMobile(true)} aria-pressed={mobile}><Smartphone size={16}/>موبایل</button><span className="text-xs text-slate-500">HTML در قاب مستقل پیش‌نمایش داده می‌شود؛ لینک‌ها و اسکریپت‌ها در این قاب اجرا نمی‌شوند.</span></div><div className="overflow-auto rounded-2xl border bg-slate-100 p-3 dark:bg-slate-950"><div className="mx-auto overflow-hidden rounded-xl" style={{ width: mobile ? 390 : "100%", maxWidth: "100%" }}><div className={mobile ? "footer-preview-mobile" : ""}><FooterLayout config={config} brand={brand} preview previewDark={config.theme === "dark" || (config.theme === "system" && previewDark)}/></div></div></div></section> : <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
        <div className="min-w-0 space-y-4">{config.sections.map((s, si) => <section key={s.id} className={`overflow-hidden rounded-2xl border bg-white dark:border-slate-700 dark:bg-slate-900 ${!s.enabled ? "opacity-60" : ""}`}>
          <div className="flex flex-wrap items-center gap-3 border-b bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800"><span className="rounded-lg bg-amber-100 px-2 py-1 text-xs font-bold text-amber-900">بخش {(si + 1).toLocaleString("fa-IR")}</span><input aria-label={`عنوان بخش ${si + 1}`} className="input min-w-32 flex-1" placeholder="عنوان بخش (اختیاری)" value={s.title} onChange={e => change(c => { c.sections[si].title = e.target.value; })}/>{orderButtons(si, config.sections.length, d => change(c => { c.sections = moved(c.sections, si, d); }), () => change(c => { c.sections.splice(si, 1); }), `بخش ${si + 1}`)}<label className="flex gap-1 text-xs"><input type="checkbox" checked={s.enabled} onChange={e => change(c => { c.sections[si].enabled = e.target.checked; })}/>نمایش</label><label className="flex gap-1 text-xs"><input type="checkbox" checked={s.border} onChange={e => change(c => { c.sections[si].border = e.target.checked; })}/>خط جداکننده</label></div>
          <div className="grid gap-3 p-4 md:grid-cols-2">{s.columns.map((col, ci) => <div key={col.id} className="min-w-0 space-y-3 rounded-xl border border-dashed p-3 dark:border-slate-600"><div className="flex items-center justify-between gap-2"><b className="text-xs">ستون {(ci + 1).toLocaleString("fa-IR")}</b>{orderButtons(ci, s.columns.length, d => change(c => { c.sections[si].columns = moved(c.sections[si].columns, ci, d); }), () => change(c => { if (c.sections[si].columns.length > 1) c.sections[si].columns.splice(ci, 1); else toast("هر بخش حداقل یک ستون دارد", false); }), `ستون ${ci + 1}`)}</div><input aria-label="عنوان ستون" className="input" placeholder="عنوان ستون (اختیاری)" value={col.title} onChange={e => change(c => { c.sections[si].columns[ci].title = e.target.value; })}/><div className="grid grid-cols-2 gap-2"><select aria-label="تراز ستون" className="input" value={col.align} onChange={e => change(c => { c.sections[si].columns[ci].align = e.target.value as FooterColumn["align"]; })}><option value="right">راست‌چین</option><option value="center">وسط‌چین</option><option value="left">چپ‌چین</option></select><select aria-label="چیدمان آیتم‌ها" className="input" value={col.layout} onChange={e => change(c => { c.sections[si].columns[ci].layout = e.target.value as FooterColumn["layout"]; })}><option value="stack">زیر هم</option><option value="row">کنار هم (نشان‌ها)</option></select></div>
            {col.items.map((i, ii) => <div key={i.id} className={`rounded-xl border p-2 ${active === i.id ? "border-amber-400 bg-amber-50 dark:bg-amber-950/30" : "dark:border-slate-700"}`}><button className="w-full text-right" onClick={() => setActive(i.id)}><span className="block truncate text-sm font-bold">{i.title || footerTypeLabels[i.type]}</span><small className="text-slate-500">{footerTypeLabels[i.type]}{!i.enabled ? " · مخفی" : ""}</small></button><div className="mt-2 flex justify-between gap-1">{orderButtons(ii, col.items.length, d => change(c => { c.sections[si].columns[ci].items = moved(c.sections[si].columns[ci].items, ii, d); }), () => change(c => { c.sections[si].columns[ci].items.splice(ii, 1); }), `آیتم ${ii + 1}`)}<button aria-label="تکثیر آیتم" className="btn-sm" disabled={col.items.length >= 30} onClick={() => change(c => { const copy = { ...i, id: uid() }; c.sections[si].columns[ci].items.splice(ii + 1, 0, copy); setActive(copy.id); })}><Copy size={14}/></button></div></div>)}
            <select aria-label="افزودن آیتم" className="input" value="" disabled={col.items.length >= 30} onChange={e => { const value = makeItem(e.target.value as FooterItemType); change(c => { c.sections[si].columns[ci].items.push(value); }); setActive(value.id); }}><option value="" disabled>＋ افزودن آیتم…</option>{Object.entries(footerTypeLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>
          </div>)}</div><div className="px-4 pb-4"><button className="btn" disabled={s.columns.length >= 4} onClick={() => change(c => { c.sections[si].columns.push(makeColumn()); })}><Plus size={16}/>افزودن ستون</button></div>
        </section>)}<div className="flex flex-wrap gap-3"><button className="btn-primary" disabled={config.sections.length >= 16} onClick={() => addSection()}><Plus size={16}/>افزودن بخش</button><button className="btn" disabled={config.sections.length >= 16} onClick={() => addSection(true)}>افزودن الگوی فروشگاهی چهارستونه</button></div></div>
        <aside ref={inspector} className="scroll-mt-44 space-y-4 rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-900 xl:sticky xl:top-44"><h2 className="font-black">تنظیمات آیتم</h2>{!item ? <p className="text-sm leading-7 text-slate-500">یک آیتم را از ستون‌ها انتخاب کنید؛ یا با «افزودن آیتم» محتوای جدید بسازید.</p> : <div className="space-y-4">
          <div className="rounded-xl bg-slate-100 p-3 text-sm dark:bg-slate-800">{footerTypeLabels[item.type]}</div><label className="flex gap-2 text-sm"><input type="checkbox" checked={item.enabled} onChange={e => patchItem({ enabled: e.target.checked })}/>نمایش آیتم</label><label className="block text-sm">{item.type === "html" || item.type === "image" ? "نام آیتم در مدیریت" : "عنوان"}<input className="input mt-2" value={item.title} onChange={e => patchItem({ title: e.target.value })}/></label>
          {item.type === "text" && <label className="block text-sm">متن<textarea className="input mt-2 min-h-40" value={item.content} onChange={e => patchItem({ content: e.target.value })}/><small className="mt-2 block text-slate-500">از {'{{siteName}}'} و {'{{siteTagline}}'} برای نام و شعار داینامیک استفاده کنید.</small></label>}
          {item.type === "html" && <label className="block text-sm"><span className="flex items-center gap-2"><Code2 size={16}/>کد HTML</span><textarea aria-label="کد HTML فوتر" className="mt-2 min-h-64 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-xs leading-6 text-slate-100" dir="ltr" spellCheck={false} value={item.content} onChange={e => patchItem({ content: e.target.value })}/><small className="mt-2 block leading-6 text-slate-500">تگ تصویر، لینک، متن و چیدمان در همین محل نمایش داده می‌شوند. کدهای اجرایی از <Link href="/admin/settings" className="underline">تنظیمات کدهای فوتر</Link> مدیریت می‌شوند.</small></label>}
          {item.type === "image" && <><div className="text-sm"><p className="mb-2">تصویر از مرکز فایل</p><ImageUploader max={1} value={/^\/api\/media\/\d+$/.test(item.src) ? [Number(item.src.split("/").pop())] : []} onChange={ids => patchItem({ src: ids[0] ? `/api/media/${ids[0]}` : "" })}/></div><label className="block text-sm">یا نشانی تصویر<input className="input mt-2" dir="ltr" value={item.src} onChange={e => patchItem({ src: e.target.value })}/></label><label className="block text-sm">متن جایگزین تصویر<input className="input mt-2" value={item.alt} onChange={e => patchItem({ alt: e.target.value })}/></label><div className="grid grid-cols-2 gap-2"><label className="text-sm">عرض (پیکسل)<input type="number" min={16} max={1200} className="input mt-2" value={item.width} onChange={e => patchItem({ width: Number(e.target.value) })}/></label><label className="text-sm">ارتفاع (پیکسل)<input type="number" min={16} max={1200} className="input mt-2" value={item.height} onChange={e => patchItem({ height: Number(e.target.value) })}/></label></div></>}
          {(item.type === "link" || item.type === "image") && <><label className="block text-sm">نشانی مقصد {item.type === "image" && "(اختیاری)"}<input className="input mt-2" dir="ltr" placeholder="/about یا https://…" value={item.href} onChange={e => patchItem({ href: e.target.value })}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={item.newTab} onChange={e => patchItem({ newTab: e.target.checked })}/>بازشدن در زبانه جدید</label></>}
          {(item.type === "brand" || item.type === "contact") && <p className="text-sm leading-7 text-slate-500">اطلاعات این آیتم از تنظیمات عمومی فروشگاه خوانده می‌شود و با تغییر تنظیمات به‌روز می‌شود.</p>}
          <label className="block text-sm">انتقال آیتم به ستون دیگر<select className="input mt-2" value="" onChange={e => { const destination = e.target.value; change(c => { const columns = c.sections.flatMap(s => s.columns); const source = columns.find(col => col.items.some(i => i.id === item.id)), target = columns.find(col => col.id === destination); if (source && target && source.id !== target.id && target.items.length < 30) { source.items = source.items.filter(i => i.id !== item.id); target.items.push(item); } }); }}><option value="">انتخاب ستون…</option>{config.sections.flatMap((s, si) => s.columns.map((col, ci) => <option key={col.id} value={col.id}>بخش {si + 1} / {col.title || `ستون ${ci + 1}`}</option>))}</select></label>
        </div>}</aside>
      </div>}
    </fieldset>
  </div>;
}
