"use client";
import { useState } from "react";
import { ArrowDown, ArrowUp, Copy, Plus, Trash2 } from "lucide-react";
import type { SitePageBlock, SitePageBlockItem } from "@/db/schema";
import { builderId } from "@/lib/page-builder";
import { HOME_SECTION_LABELS } from "@/lib/home-page-builder";
import { ImageUploader } from "./client";

export function Field({ label, value, onChange, multiline = false, placeholder = "", dir }: { label: string; value?: string; onChange: (v: string) => void; multiline?: boolean; placeholder?: string; dir?: "ltr" }) {
  return <label className="block text-xs font-bold text-slate-600">{label}{multiline ? <textarea className="input mt-1 min-h-28 !text-sm" value={value || ""} onChange={e => onChange(e.target.value)} placeholder={placeholder} /> : <input dir={dir} className="input mt-1 !text-sm" value={value || ""} onChange={e => onChange(e.target.value)} placeholder={placeholder}/>}</label>;
}
function NumberField({ label, value, onChange, min = 0, max = 160 }: { label: string; value?: number; onChange: (v: number | undefined) => void; min?: number; max?: number }) {
  return <label className="block text-xs font-bold text-slate-600">{label}<input type="number" dir="ltr" className="input mt-1" min={min} max={max} placeholder="پیش‌فرض" value={value ?? ""} onChange={e => onChange(e.target.value === "" ? undefined : Math.max(min, Math.min(max, Number(e.target.value))))}/></label>;
}
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (v: boolean) => void }) { return <label className="flex items-center justify-between gap-2 rounded-xl border p-3 text-xs"><span>{label}</span><input type="checkbox" checked={value} onChange={e => onChange(e.target.checked)} className="size-4 accent-amber-500"/></label>; }

export function HomeBuilderInspector({ block, patch, categories, pickProducts }: { block: SitePageBlock; patch: (value: Partial<SitePageBlock>) => void; categories: { id: number; name: string }[]; pickProducts: () => void }) {
  const [tab, setTab] = useState("content");
  const style = block.style || {}, options = block.options || {};
  const setStyle = (values: Partial<NonNullable<SitePageBlock["style"]>>) => patch({ style: { ...style, ...values } });
  const setOptions = (values: Partial<NonNullable<SitePageBlock["options"]>>) => patch({ options: { ...options, ...values } });
  const items = block.items || [];
  const updateItem = (i: number, values: Partial<SitePageBlockItem>) => patch({ items: items.map((it, j) => i === j ? { ...it, ...values } : it) });
  const isHero = block.type === "hero" || block.sectionId === "hero";
  const hasItems = ["grid", "slider", "features", "faq"].includes(block.type) || ["trust", "testimonials", "why", "promo"].includes(block.sectionId || "");
  const hasProducts = ["popular", "fresh", "deals", "festival"].includes(block.sectionId || "");
  return <><div className="sticky top-0 z-10 grid grid-cols-3 gap-1 border-b bg-white p-2">{[["content", "محتوا"], ["design", "طراحی"], ["responsive", "نمایش"]].map(([key, label]) => <button key={key} className={`rounded-lg py-2 text-xs font-bold ${tab === key ? "bg-amber-100 text-amber-950" : "text-slate-500"}`} onClick={() => setTab(key)}>{label}</button>)}</div><div className="space-y-4 p-4">
    {tab === "content" && <>
      <Field label="نام لایه (فقط در ویرایشگر)" value={block.name} onChange={name => patch({ name })}/>
      {block.type === "store_section" && <p className="rounded-lg bg-amber-50 p-3 text-xs leading-6">{HOME_SECTION_LABELS[block.sectionId || ""]} · محتوای فروشگاه به‌صورت زنده نمایش داده می‌شود.</p>}
      <Field label="عنوان" value={block.title} placeholder="عنوان فعلی بخش" onChange={title => patch({ title })}/>
      <Field label="متن / توضیحات" value={block.body} placeholder="توضیحات بخش" multiline onChange={body => patch({ body })}/>
      {(isHero || block.type === "image") && <div><b className="mb-2 block text-xs">تصویر</b><ImageUploader value={block.mediaId ? [block.mediaId] : []} max={1} onChange={ids => patch({ mediaId: ids[0] || null })}/><Field label="توضیح تصویر (Alt)" value={block.caption} onChange={caption => patch({ caption })}/></div>}
      {(!hasProducts && !hasItems || isHero) && <><Field label="متن دکمه" value={block.buttonLabel} onChange={buttonLabel => patch({ buttonLabel })}/><Field label="پیوند دکمه" dir="ltr" value={block.href} placeholder="/shop" onChange={href => patch({ href })}/></>}
      {isHero && <><Field label="برچسب بالای بنر" value={options.badge} onChange={badge => setOptions({ badge })}/><Field label="متن دکمه دوم" value={options.secondaryLabel} onChange={secondaryLabel => setOptions({ secondaryLabel })}/><Field label="پیوند دکمه دوم" dir="ltr" value={options.secondaryHref} onChange={secondaryHref => setOptions({ secondaryHref })}/>{block.type === "store_section" && <><Toggle label="نمایش جست‌وجوی محصولات" value={options.showSearch !== false} onChange={showSearch => setOptions({ showSearch })}/><Toggle label="نمایش آمار زیر بنر" value={options.showStats !== false} onChange={showStats => setOptions({ showStats })}/></>}</>}
      {block.type === "slider" && <><Toggle label="پخش خودکار اسلایدها" value={!!options.autoplay} onChange={autoplay => setOptions({ autoplay })}/><NumberField label="فاصله پخش (ثانیه)" value={options.interval ?? 5} min={3} max={30} onChange={interval => setOptions({ interval })}/></>}
      {hasProducts && <><NumberField label="تعداد محصولات" value={options.limit} min={1} max={24} onChange={limit => setOptions({ limit })}/><label className="block text-xs">دسته محصولات<select className="input mt-1" value={options.categoryId || ""} onChange={e => setOptions({ categoryId: Number(e.target.value) || undefined, productIds: [] })}><option value="">همه دسته‌ها</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="btn-ghost w-full" onClick={pickProducts}>انتخاب محصولات دلخواه ({options.productIds?.length || 0})</button>{!!options.productIds?.length && <button className="text-xs text-rose-600" onClick={() => setOptions({ productIds: [] })}>بازگشت به انتخاب خودکار</button>}</>}
      {["blog", "categories", "farms"].includes(block.sectionId || "") && <NumberField label="تعداد نمایش" value={options.limit} min={1} max={24} onChange={limit => setOptions({ limit })}/>}
      {hasItems && <div className="space-y-3 border-t pt-4"><div className="flex items-center justify-between"><b className="text-sm">{block.type === "slider" ? "اسلایدها" : "آیتم‌های بخش"}</b><button disabled={items.length >= 30} className="btn-sm" onClick={() => patch({ items: [...items, { id: builderId(), kind: "image", title: "عنوان جدید", body: "" }] })}><Plus className="size-4"/>افزودن</button></div>{items.map((it, i) => <details key={it.id || i} className="rounded-xl border bg-slate-50 p-3" open={items.length === 1 ? true : undefined}><summary className="cursor-pointer text-xs font-bold">{i + 1}. {it.title || "آیتم بدون عنوان"}</summary><div className="mt-3 space-y-3"><div className="flex gap-1"><button title="بالا" className="btn-sm" disabled={!i} onClick={() => { const next = [...items]; [next[i - 1], next[i]] = [next[i], next[i - 1]]; patch({ items: next }); }}><ArrowUp className="size-3"/></button><button title="پایین" className="btn-sm" disabled={i === items.length - 1} onClick={() => { const next = [...items]; [next[i + 1], next[i]] = [next[i], next[i + 1]]; patch({ items: next }); }}><ArrowDown className="size-3"/></button><button title="تکثیر" disabled={items.length >= 30} className="btn-sm" onClick={() => patch({ items: [...items.slice(0, i + 1), { ...it, id: builderId() }, ...items.slice(i + 1)] })}><Copy className="size-3"/></button><button title="حذف آیتم" className="btn-sm text-rose-600" onClick={() => patch({ items: items.filter((_, j) => j !== i) })}><Trash2 className="size-3"/></button></div><Field label={block.type === "faq" ? "پرسش" : "عنوان"} value={it.title} onChange={title => updateItem(i, { title })}/><Field label={block.type === "faq" ? "پاسخ" : "توضیحات"} value={it.body} multiline onChange={body => updateItem(i, { body })}/>{block.type !== "faq" && <><ImageUploader value={it.mediaId ? [it.mediaId] : []} max={1} onChange={ids => updateItem(i, { mediaId: ids[0] || null })}/><Field label="توضیح تصویر" value={it.caption} onChange={caption => updateItem(i, { caption })}/><Field label="متن دکمه" value={it.buttonLabel} onChange={buttonLabel => updateItem(i, { buttonLabel })}/><Field label="پیوند" dir="ltr" value={it.href} onChange={href => updateItem(i, { href })}/>{block.type === "grid" && <NumberField label="تعداد ستون اشغال‌شده" min={1} max={Math.min(4, style.columns || 3)} value={it.colSpan || 1} onChange={colSpan => updateItem(i, { colSpan })}/>}</>}</div></details>)}</div>}
    </>}
    {tab === "design" && <>
      {([["background", "رنگ پس‌زمینه"], ["color", "رنگ متن"], ["accent", "رنگ دکمه‌ها"]] as const).map(([key, label]) => <label key={key} className="flex items-center justify-between gap-2 text-xs">{label}<div className="flex items-center gap-2"><button className="text-slate-400" onClick={() => setStyle({ [key]: undefined })}>پیش‌فرض</button><input type="color" aria-label={label} value={style[key] || (key === "color" ? "#0f172a" : "#facc15")} onChange={e => setStyle({ [key]: e.target.value })} className="size-9 rounded border"/></div></label>)}
      <label className="block text-xs">تراز متن<select className="input mt-1" value={style.align || ""} onChange={e => setStyle({ align: e.target.value as typeof style.align || undefined })}><option value="">پیش‌فرض</option><option value="right">راست</option><option value="center">وسط</option><option value="left">چپ</option></select></label>
      <label className="block text-xs">عرض سکشن<select className="input mt-1" value={style.width || ""} onChange={e => setStyle({ width: e.target.value as typeof style.width || undefined })}><option value="">پیش‌فرض</option><option value="contained">داخل کادر صفحه</option><option value="full">تمام عرض</option></select></label>
      <div className="grid grid-cols-2 gap-3"><NumberField label="فاصله داخلی (px)" value={style.padding} onChange={padding => setStyle({ padding })}/><NumberField label="فاصله پایین (px)" value={style.marginBottom} onChange={marginBottom => setStyle({ marginBottom })}/><NumberField label="گردی گوشه (px)" value={style.radius} max={100} onChange={radius => setStyle({ radius })}/><NumberField label="حداقل ارتفاع (px)" value={style.minHeight} max={1200} onChange={minHeight => setStyle({ minHeight })}/><NumberField label="ستون دسکتاپ" value={style.columns} min={1} max={6} onChange={columns => setStyle({ columns })}/><NumberField label="فاصله کارت‌ها (px)" value={style.gap} max={80} onChange={gap => setStyle({ gap })}/></div>
      <button className="btn-ghost w-full" onClick={() => patch({ style: {} })}>بازنشانی طراحی این بخش</button>
    </>}
    {tab === "responsive" && <><Toggle label="فعال بودن سکشن" value={block.enabled !== false} onChange={enabled => patch({ enabled })}/><Toggle label="نمایش در دسکتاپ و تبلت" value={!style.hideDesktop} onChange={v => setStyle({ hideDesktop: !v })}/><Toggle label="نمایش در موبایل" value={!style.hideMobile} onChange={v => setStyle({ hideMobile: !v })}/><NumberField label="ستون‌های موبایل" min={1} max={2} value={style.mobileColumns} onChange={mobileColumns => setStyle({ mobileColumns })}/><NumberField label="فاصله داخلی موبایل (px)" value={style.paddingMobile} max={80} onChange={paddingMobile => setStyle({ paddingMobile })}/><Field label="شناسه لنگر (انگلیسی؛ مثلاً offers)" dir="ltr" value={block.anchor} onChange={anchor => patch({ anchor })}/><p className="text-xs leading-6 text-slate-500">برای پیوند مستقیم به این بخش از #شناسه استفاده کنید. با تغییر دستگاه در نوار بالا، نمایش واقعی همان اندازه را ببینید.</p></>}
  </div></>;
}
