"use client";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { ArrowRightLeft, MapPin, Plus, RefreshCw, Warehouse } from "lucide-react";
import { api, toast } from "./client";
import { faNum } from "@/lib/util";
import { Badge, Card } from "./ui";

type Location={id:number;name:string;code:string;address:string|null;enabled:boolean;isDefault:boolean};
type Item={productId:number;variantId:number|null;label:string;sku:string;unit:string;centralAvailable:number};
type Stock={id:number;warehouseId:number;productId:number;variantId:number|null;onHand:number;reserved:number};
type Data={warehouses:Location[];stock:Stock[];items:Item[]};

export function InventoryWarehousesClient(){
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const [name,setName]=useState(""),[code,setCode]=useState(""),[address,setAddress]=useState("");
  const [fromId,setFromId]=useState(""),[toId,setToId]=useState(""),[itemKey,setItemKey]=useState(""),[query,setQuery]=useState(""),[quantity,setQuantity]=useState(1),[note,setNote]=useState("");
  const refresh=async()=>{setLoading(true);try{const next=await api<Data>("/api/admin/inventory/warehouses","GET");setData(next);const main=next.warehouses.find(x=>x.isDefault);if(main){setFromId(old=>old||String(main.id));const alt=next.warehouses.find(x=>x.id!==main.id&&x.enabled);setToId(old=>old||String(alt?.id??""));}}catch(e){toast((e as Error).message,false)}finally{setLoading(false)}};
  useEffect(()=>{void refresh()},[]);
  const selectedItem=data?.items.find(x=>`${x.productId}:${x.variantId??0}`===itemKey);
  const available=useMemo(()=>{if(!data||!selectedItem)return 0;const source=data.warehouses.find(x=>x.id===Number(fromId));if(source?.isDefault)return Math.max(0,selectedItem.centralAvailable);const stock=data.stock.find(x=>x.warehouseId===Number(fromId)&&x.productId===selectedItem.productId&&x.variantId===selectedItem.variantId);return Math.max(0,(stock?.onHand??0)-(stock?.reserved??0));},[data,selectedItem,fromId]);
  const filteredItems=(data?.items??[]).filter(x=>`${x.label} ${x.sku}`.toLowerCase().includes(query.trim().toLowerCase()));
  const create=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await api("/api/admin/inventory/warehouses","POST",{name,code,address});toast("انبار جدید ثبت شد");setName("");setCode("");setAddress("");await refresh()}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
  const transfer=async(e:FormEvent)=>{e.preventDefault();if(!selectedItem)return toast("کالا را انتخاب کنید",false);if(Number(fromId)===Number(toId))return toast("مبدأ و مقصد باید متفاوت باشند",false);if(quantity>available)return toast(`موجودی آزاد مبدأ ${faNum(available)} ${selectedItem.unit} است`,false);setBusy(true);try{await api("/api/admin/inventory/warehouses/transfers","POST",{fromWarehouseId:Number(fromId),toWarehouseId:Number(toId),productId:selectedItem.productId,variantId:selectedItem.variantId,quantity,note});toast("انتقال انبار با دو گردش ورود و خروج ثبت شد");setQuantity(1);setNote("");setItemKey("");await refresh()}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
  const toggle=async(w:Location)=>{if(w.isDefault)return;setBusy(true);try{await api(`/api/admin/inventory/warehouses/${w.id}`,"PUT",{name:w.name,address:w.address??"",enabled:!w.enabled});toast(w.enabled?"انبار غیرفعال شد":"انبار فعال شد");await refresh()}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
  return <div className="space-y-5">
    <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs leading-6 text-amber-950">موجودی انبار اصلی در فروش آنلاین و حضوری فعلی استفاده می‌شود. موجودی انبارهای دیگر مستقل نگهداری می‌شود و پس از انتقال به انبار اصلی قابل فروش خواهد بود؛ رزرو و ارسال سفارش از شعبهٔ فرعی در این مرحله فعال نیست.</div>
    <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
      <Card title="تعریف انبار جدید"><form onSubmit={create} className="space-y-3"><label className="block text-xs font-bold">نام انبار<input required maxLength={100} className="input mt-1" value={name} onChange={e=>setName(e.target.value)} placeholder="مثلاً انبار شمال"/></label><label className="block text-xs font-bold">کد یکتا<input required maxLength={20} dir="ltr" className="input mt-1" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,""))} placeholder="NORTH-01"/></label><label className="block text-xs font-bold">نشانی<input maxLength={300} className="input mt-1" value={address} onChange={e=>setAddress(e.target.value)} placeholder="نشانی یا توضیح محل نگهداری"/></label><button disabled={busy} className="btn-primary w-full"><Plus className="size-4"/>ثبت انبار</button></form></Card>
      <Card title="انتقال موجودی بین انبارها"><form onSubmit={transfer} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">مبدأ<select className="input mt-1" required value={fromId} onChange={e=>setFromId(e.target.value)}><option value="">انتخاب انبار</option>{data?.warehouses.filter(x=>x.enabled).map(x=><option key={x.id} value={x.id}>{x.name}{x.isDefault?" · انبار فروش آنلاین":""}</option>)}</select></label><label className="text-xs font-bold">مقصد<select className="input mt-1" required value={toId} onChange={e=>setToId(e.target.value)}><option value="">انتخاب انبار</option>{data?.warehouses.filter(x=>x.enabled).map(x=><option key={x.id} value={x.id}>{x.name}{x.isDefault?" · انبار فروش آنلاین":""}</option>)}</select></label></div><label className="block text-xs font-bold">جست‌وجوی کالا<input className="input mt-1" value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام یا کد کالا"/></label><label className="block text-xs font-bold">کالا / تنوع<select className="input mt-1" required value={itemKey} onChange={e=>setItemKey(e.target.value)}><option value="">انتخاب کالا</option>{filteredItems.map(x=><option key={`${x.productId}:${x.variantId??0}`} value={`${x.productId}:${x.variantId??0}`}>{x.label} · {x.sku}</option>)}</select></label><div className="rounded-xl bg-slate-50 px-3 py-2 text-xs text-slate-600">موجودی آزاد مبدأ: <b>{faNum(available)} {selectedItem?.unit??""}</b></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">تعداد انتقال<input type="number" required min="1" max={Math.max(1,available)} className="input mt-1" value={quantity} onChange={e=>setQuantity(Math.max(1,Number(e.target.value)||1))}/></label><label className="text-xs font-bold">توضیح<input maxLength={300} className="input mt-1" value={note} onChange={e=>setNote(e.target.value)} placeholder="اختیاری"/></label></div><button disabled={busy||!data?.warehouses.some(x=>x.id===Number(fromId))||!data?.warehouses.some(x=>x.id===Number(toId))} className="btn-primary w-full"><ArrowRightLeft className="size-4"/>ثبت انتقال دوطرفه</button></form></Card>
    </div>
    <Card title="فهرست انبارها"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data?.warehouses.map(w=>{const rows=data.stock.filter(x=>x.warehouseId===w.id&&x.onHand>0);const units=rows.reduce((sum,x)=>sum+x.onHand,0);return <article key={w.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-2"><div className="flex items-start gap-2"><Warehouse className="mt-0.5 size-4 text-amber-700"/><div><b className="text-sm">{w.name}</b><div className="mt-1 font-mono text-[11px] text-slate-500" dir="ltr">{w.code}</div></div></div><Badge tone={w.isDefault?"green":w.enabled?"blue":"gray"}>{w.isDefault?"انبار اصلی":w.enabled?"فعال":"غیرفعال"}</Badge></div>{w.address&&<p className="mt-2 flex gap-1 text-xs text-slate-500"><MapPin className="size-3 shrink-0"/>{w.address}</p>}<div className="mt-3 border-t pt-3 text-xs text-slate-600">{faNum(rows.length)} ردیف کالا · {faNum(units)} واحد موجود</div>{!w.isDefault&&<button disabled={busy} onClick={()=>void toggle(w)} className="btn-sm mt-3 w-full">{w.enabled?"غیرفعال‌سازی":"فعال‌سازی"}</button>}</article>})}</div>{data?.warehouses.length===0&&<p className="p-5 text-center text-sm text-slate-500">هنوز انباری تعریف نشده است.</p>}{loading&&<p className="mt-3 text-center text-xs text-slate-400">در حال دریافت فهرست انبارها…</p>}</Card>
    <Card title="موجودی تفکیک‌شده به انبار"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3">انبار</th><th className="p-3">کالا / تنوع</th><th className="p-3">کد کالا</th><th className="p-3">واحد</th><th className="p-3">موجود</th><th className="p-3">رزرو</th><th className="p-3">آزاد</th></tr></thead><tbody>{data?.stock.filter(x=>x.onHand||x.reserved).map(x=>{const w=data.warehouses.find(i=>i.id===x.warehouseId),item=data.items.find(i=>i.productId===x.productId&&i.variantId===x.variantId);return <tr key={x.id} className="border-b last:border-0"><td className="p-3 font-bold">{w?.name??"—"}</td><td className="p-3">{item?.label??`کالای ${faNum(x.productId)}`}</td><td className="p-3 font-mono" dir="ltr">{item?.sku??"—"}</td><td className="p-3">{item?.unit??"—"}</td><td className="p-3">{faNum(x.onHand)}</td><td className="p-3">{faNum(x.reserved)}</td><td className="p-3 font-bold">{faNum(x.onHand-x.reserved)}</td></tr>})}</tbody></table>{!loading&&!data?.stock.some(x=>x.onHand||x.reserved)&&<p className="p-8 text-center text-sm text-slate-500">موجودی انبار ثبت نشده است.</p>}</div></Card>
    <div className="flex justify-end"><button disabled={loading} onClick={()=>void refresh()} className="btn-ghost"><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/>به‌روزرسانی</button></div>
  </div>;
}
