"use client";
import { useEffect, useState, type FormEvent } from "react";
import { Download, MapPin, Plus, Printer, RefreshCw, Warehouse } from "lucide-react";
import { InventoryDocumentsClient } from "./InventoryDocumentsClient";
import { api, toast } from "./client";
import { faNum } from "@/lib/util";
import { Badge, Card } from "./ui";

type Location={id:number;name:string;code:string;address:string|null;enabled:boolean;isDefault:boolean;sellerId:number|null};
type Item={productId:number;variantId:number|null;label:string;sku:string;unit:string;centralAvailable:number};
type Stock={id:number;warehouseId:number;productId:number;variantId:number|null;onHand:number;reserved:number};
type Data={warehouses:Location[];stock:Stock[];items:Item[]};
const normalize=(value:string)=>value.toLocaleLowerCase().replace(/ي/g,"ی").replace(/ك/g,"ک").replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d)));

export function InventoryWarehousesClient(){
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const [selectedWarehouseId,setSelectedWarehouseId]=useState(""),[stockQuery,setStockQuery]=useState("");
  const [name,setName]=useState(""),[code,setCode]=useState(""),[address,setAddress]=useState("");
  const refresh=async()=>{setLoading(true);try{const next=await api<Data>("/api/admin/inventory/warehouses","GET");setData(next);setSelectedWarehouseId(old=>old||String(next.warehouses.find(w=>w.isDefault)?.id??next.warehouses.find(w=>w.enabled)?.id??""))}catch(e){toast((e as Error).message,false)}finally{setLoading(false)}};
  useEffect(()=>{void refresh()},[]);
  const create=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await api("/api/admin/inventory/warehouses","POST",{name,code,address});toast("انبار جدید ثبت شد");setName("");setCode("");setAddress("");await refresh()}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
  const toggle=async(w:Location)=>{if(w.isDefault)return;setBusy(true);try{await api(`/api/admin/inventory/warehouses/${w.id}`,"PUT",{name:w.name,address:w.address??"",enabled:!w.enabled});toast(w.enabled?"انبار غیرفعال شد":"انبار فعال شد");await refresh()}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
  const selectedWarehouse=data?.warehouses.find(w=>w.id===Number(selectedWarehouseId));
  const stockRows=(data?.stock??[]).filter(x=>x.warehouseId===Number(selectedWarehouseId)&&(x.onHand!==0||x.reserved!==0)).map(row=>({row,item:data?.items.find(i=>i.productId===row.productId&&i.variantId===row.variantId)})).filter(({row,item})=>!stockQuery||normalize(`${item?.label??""} ${item?.sku??""} ${row.productId}`).includes(normalize(stockQuery)));
  return <div className="space-y-5">
    <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs leading-6 text-amber-950">موجودی انبار اصلی در فروش آنلاین و حضوری فعلی استفاده می‌شود. موجودی انبارهای دیگر مستقل نگهداری می‌شود و پس از انتقال به انبار اصلی قابل فروش خواهد بود؛ رزرو و ارسال سفارش از شعبهٔ فرعی در این مرحله فعال نیست.</div>
    <div className="grid gap-5 xl:grid-cols-[300px_minmax(0,1fr)]">
      <Card title="تعریف انبار جدید"><form onSubmit={create} className="space-y-3"><label className="block text-xs font-bold">نام انبار<input required maxLength={100} className="input mt-1" value={name} onChange={e=>setName(e.target.value)} placeholder="مثلاً انبار شمال"/></label><label className="block text-xs font-bold">کد یکتا<input required maxLength={20} dir="ltr" className="input mt-1" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,""))} placeholder="NORTH-01"/></label><label className="block text-xs font-bold">نشانی<input maxLength={300} className="input mt-1" value={address} onChange={e=>setAddress(e.target.value)} placeholder="نشانی یا توضیح محل نگهداری"/></label><button disabled={busy} className="btn-primary w-full"><Plus className="size-4"/>ثبت انبار</button></form></Card>
      <Card title="حواله‌های انتقال و پذیرش"><InventoryDocumentsClient mode="transfers" onChanged={()=>void refresh()}/></Card>
    </div>
    <Card title="فهرست انبارها"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data?.warehouses.map(w=>{const rows=data.stock.filter(x=>x.warehouseId===w.id&&(x.onHand!==0||x.reserved!==0));return <article key={w.id} className={`rounded-xl border p-4 ${selectedWarehouseId===String(w.id)?"border-amber-500 ring-1 ring-amber-500":"border-slate-200"}`}><div className="flex items-start justify-between gap-2"><div className="flex items-start gap-2"><Warehouse className="mt-0.5 size-4 text-amber-700"/><div><b className="text-sm">{w.name}</b><div className="mt-1 font-mono text-[11px] text-slate-500" dir="ltr">{w.code}</div></div></div><Badge tone={w.isDefault?"green":w.enabled?"blue":"gray"}>{w.isDefault?"انبار اصلی":w.enabled?"فعال":"غیرفعال"}</Badge></div>{w.address&&<p className="mt-2 flex gap-1 text-xs text-slate-500"><MapPin className="size-3 shrink-0"/>{w.address}</p>}<div className="mt-3 border-t pt-3 text-xs text-slate-600">{faNum(rows.length)} ردیف کالا با موجودی یا رزرو</div><button onClick={()=>setSelectedWarehouseId(String(w.id))} className="btn-sm mt-3 w-full">مشاهده فهرست کالاها</button>{!w.isDefault&&!w.sellerId&&<button disabled={busy} onClick={()=>void toggle(w)} className="btn-sm mt-2 w-full">{w.enabled?"غیرفعال‌سازی":"فعال‌سازی"}</button>}</article>})}</div>{data?.warehouses.length===0&&<p className="p-5 text-center text-sm text-slate-500">هنوز انباری تعریف نشده است.</p>}{loading&&<p className="mt-3 text-center text-xs text-slate-400">در حال دریافت فهرست انبارها…</p>}</Card>
    <Card title="فهرست کالاهای انبار"><div className="mb-4 grid gap-3 md:grid-cols-[minmax(220px,1fr)_minmax(220px,2fr)_auto_auto] md:items-end"><label className="text-xs font-bold">انبار<select className="input mt-1" value={selectedWarehouseId} onChange={e=>setSelectedWarehouseId(e.target.value)}><option value="">انتخاب انبار</option>{data?.warehouses.map(w=><option disabled={!w.enabled} key={w.id} value={w.id}>{w.name}{w.isDefault?" · اصلی":w.sellerId?" · تأمین‌کننده":""}</option>)}</select></label><label className="text-xs font-bold">جست‌وجوی کالا<input className="input mt-1" placeholder="نام، تنوع یا کد کالا" value={stockQuery} onChange={e=>setStockQuery(e.target.value)}/></label>{selectedWarehouse&&<><a className="btn-ghost justify-center" href={`/api/admin/inventory/warehouses/${selectedWarehouse.id}/stock.xlsx?q=${encodeURIComponent(stockQuery)}`}><Download className="size-4"/>خروجی اکسل</a><a className="btn-ghost justify-center" target="_blank" rel="noreferrer" href={`/print/warehouse-stock/${selectedWarehouse.id}?q=${encodeURIComponent(stockQuery)}`}><Printer className="size-4"/>پیش‌نمایش / چاپ</a></>}</div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-right text-xs"><thead className="bg-slate-50 text-slate-500 dark:bg-slate-800"><tr>{["کالا / تنوع","کد کالا","واحد","موجود","رزرو","آزاد"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{stockRows.map(({row,item})=><tr key={`${row.warehouseId}:${row.productId}:${row.variantId??0}`} className="border-b last:border-0"><td className="p-3 font-bold">{item?.label??`کالای ${faNum(row.productId)}`}</td><td className="p-3 font-mono" dir="ltr">{item?.sku??"—"}</td><td className="p-3">{item?.unit??"—"}</td><td className="p-3">{faNum(row.onHand)}</td><td className="p-3">{faNum(row.reserved)}</td><td className="p-3 font-bold">{faNum(row.onHand-row.reserved)}</td></tr>)}</tbody></table>{!loading&&selectedWarehouseId&&!stockRows.length&&<p className="p-8 text-center text-sm text-slate-500">برای این انبار کالایی با موجودی ثبت‌شده پیدا نشد.</p>}{!selectedWarehouseId&&<p className="p-8 text-center text-sm text-slate-500">یک انبار را برای مشاهدهٔ فهرست موجودی انتخاب کنید.</p>}</div><p className="mt-3 text-xs text-slate-500">{faNum(stockRows.length)} قلم نمایش داده می‌شود. خروجی اکسل فقط همین انبار و جست‌وجوی اعمال‌شده را شامل می‌شود.</p></Card>
    <div className="flex justify-end"><button disabled={loading} onClick={()=>void refresh()} className="btn-ghost"><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/>به‌روزرسانی</button></div>
  </div>;
}
