"use client";
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Plus, Search, Trash2, Printer, PackageCheck, FileText } from 'lucide-react';
import { api, toast, uid } from './client';
import { Modal } from './Modal';
import { InvoiceModal } from './InvoiceModal';
import { InventoryPartyForm } from './InventoryPartyForm';
import { JalaliDatePicker } from './JalaliDatePicker';
import { todayIso } from '@/lib/jalali';
import { faNum, jdate, toman } from '@/lib/util';
import type { InventoryDocumentItem } from '@/db/schema';

type Location={id:number;name:string;enabled:boolean;isDefault:boolean};
type Choice={productId:number;variantId:number|null;label:string;sku:string;unit:string;unitCost:number;centralAvailable:number};
type Options={warehouses:Location[];items:Choice[];parties:{id:number;name:string}[];stock:{warehouseId:number;productId:number;variantId:number|null;onHand:number;reserved:number}[]};
type Line=Choice&{quantity:number};
type Doc={id:number;number:string;type:string;status:string;invoiceNumber:string|null;partyName:string|null;documentDate:string;createdAt:string;items:InventoryDocumentItem[];total:number;subtotal:number;freight:number;customs:number;paidAmount:number;paymentLocation:string|null;paymentTrackingNumber:string|null;responsibleName:string|null;responsiblePhone:string|null;fromWarehouseName:string|null;toWarehouseName:string|null;toWarehouseId:number|null;note:string|null;receiptNote:string|null;receivedAt:string|null;creatorName?:string;receiverName?:string;journalEntryId:number|null};
const key=(x:{productId:number;variantId:number|null})=>`${x.productId}:${x.variantId??0}`;
const labels:Record<string,string>={purchase:'صورتحساب خرید',consignment:'دریافت امانی',adjust:'تعدیل ورود / خروج',transfer:'حواله انتقال',posted:'ثبت‌شده',issued:'در راه / در انتظار پذیرش',received:'پذیرش کامل',received_with_difference:'پذیرش با مغایرت'};
const normalize=(s:string)=>s.toLowerCase().replace(/ي/g,'ی').replace(/ك/g,'ک').replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d)));
function Amount({value,onChange,label}:{value:number;onChange:(n:number)=>void;label:string}){return <input aria-label={label} inputMode="numeric" className="input min-w-28 text-left" dir="ltr" value={value.toLocaleString('en-US')} onChange={e=>{const n=Number(normalize(e.target.value).replace(/[,٬\s]/g,''));if(Number.isSafeInteger(n)&&n>=0)onChange(n)}}/>}
const blank=(mode:string)=>({type:mode==='transfers'?'transfer':'purchase',partyId:'',invoiceNumber:'',documentDate:todayIso(),freight:0,customs:0,paidAmount:0,paymentLocation:'',paymentTrackingNumber:'',note:'',fromWarehouseId:'',toWarehouseId:'',responsibleName:'',responsiblePhone:''});
export function InventoryDocumentsClient({mode='receipts',onChanged}:{mode?:'receipts'|'transfers';onChanged?:()=>void}){
 const router=useRouter();
 const [options,setOptions]=useState<Options|null>(null),[rows,setRows]=useState<Doc[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [editor,setEditor]=useState(false),[form,setForm]=useState(()=>blank(mode)),[lines,setLines]=useState<Line[]>([]),[search,setSearch]=useState(''),[pickPage,setPickPage]=useState(1),[picker,setPicker]=useState(true),[partyOpen,setPartyOpen]=useState(false),[busy,setBusy]=useState(false),[token,setToken]=useState(''),[printId,setPrintId]=useState<number|null>(null);
 const [detail,setDetail]=useState<Doc|null>(null),[accept,setAccept]=useState(false),[reports,setReports]=useState<Record<string,{receivedQuantity:number;discrepancyNote:string}>>({}),[receiptNote,setReceiptNote]=useState(''),[toId,setToId]=useState('');
 const loadOptions=async()=>{const v=await api<Options>('/api/admin/inventory/warehouses','GET');setOptions(v);return v};
 useEffect(()=>{void loadOptions().catch(e=>setError(e.message))},[revision]);
 useEffect(()=>{let active=true;setLoading(true);const t=setTimeout(()=>{api<{rows:Doc[];total:number}>(`/api/admin/inventory/documents?mode=${mode}&page=${page}&q=${encodeURIComponent(q)}&status=${status}`,'GET').then(d=>{if(active){setRows(d.rows);setTotal(d.total);setError('')}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)})},250);return()=>{active=false;clearTimeout(t)}},[mode,page,q,status,revision]);
 const patch=(name:string,value:string|number)=>setForm(f=>({...f,[name]:value}));
 const refresh=()=>{setRevision(n=>n+1);onChanged?.();router.refresh()};
 const begin=()=>{setForm({...blank(mode),fromWarehouseId:String(options?.warehouses.find(w=>w.isDefault)?.id??'')});setLines([]);setToken(uid().replace(/[^a-zA-Z0-9-]/g,''));setSearch('');setPickPage(1);setPicker(true);setEditor(true)};
 const available=(item:Choice)=>{if(form.type!=='transfer')return item.centralAvailable;const w=options?.warehouses.find(x=>x.id===Number(form.fromWarehouseId));if(w?.isDefault)return item.centralAvailable;const s=options?.stock.find(x=>x.warehouseId===w?.id&&x.productId===item.productId&&x.variantId===item.variantId);return (s?.onHand??0)-(s?.reserved??0)};
 const filtered=(options?.items??[]).filter(i=>normalize(i.label+' '+i.sku).includes(normalize(search.trim())));
 const add=(item:Choice)=>setLines(old=>old.some(i=>key(i)===key(item))?old:old.length>=100?old:[...old,{...item,quantity:1}]);
 const changeLine=(k:string,values:Partial<Line>)=>setLines(old=>old.map(i=>{if(key(i)!==k)return i;const next={...i,...values};if(form.type==='adjust'&&next.quantity<0)next.unitCost=options?.items.find(x=>key(x)===k)?.unitCost??i.unitCost;return next}));
 const subtotal=lines.reduce((s,i)=>s+i.quantity*i.unitCost,0),grandTotal=subtotal+(form.type==='purchase'?form.freight+form.customs:0);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!lines.length)return toast('حداقل یک کالا انتخاب کنید',false);if(form.type==='transfer'&&lines.some(i=>i.quantity>available(i)))return toast('موجودی مبدأ برای بعضی اقلام کافی نیست',false);setBusy(true);try{const doc=await api<Doc>('/api/admin/inventory/documents','POST',{...form,freight:form.type==='purchase'?form.freight:0,customs:form.type==='purchase'?form.customs:0,paidAmount:form.type==='purchase'?form.paidAmount:0,idempotencyKey:token,items:lines.map(i=>({productId:i.productId,variantId:i.variantId,quantity:i.quantity,unitCost:i.unitCost}))});setEditor(false);setPrintId(doc.id);setPage(1);refresh();toast(`سند ${doc.number} ثبت شد`)}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
 const inspect=async(id:number,forAcceptance=false)=>{try{const d=await api<Doc>(`/api/admin/inventory/documents/${id}`,'GET');setDetail(d);setAccept(forAcceptance);setToId(String(d.toWarehouseId??''));setReceiptNote('');setReports(Object.fromEntries(d.items.map(i=>[key(i),{receivedQuantity:i.quantity,discrepancyNote:''}])))}catch(e){toast((e as Error).message,false)}};
 const receive=async(e:React.FormEvent)=>{e.preventDefault();if(!detail)return;setBusy(true);try{const d=await api<Doc>(`/api/admin/inventory/documents/${detail.id}/accept`,'POST',{toWarehouseId:Number(toId),note:receiptNote,items:detail.items.map(i=>({productId:i.productId,variantId:i.variantId,quantity:i.quantity,...reports[key(i)]}))});setDetail(null);refresh();setPrintId(d.id);toast(d.status==='received_with_difference'?'پذیرش و گزارش مغایرت ثبت شد':'پذیرش کامل ثبت شد')}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
 return <div className="space-y-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black">{mode==='transfers'?'حواله‌های انتقال و پذیرش انبار':'صورتحساب‌های خرید، امانی و تعدیل'}</h2><p className="mt-1 text-xs leading-6 text-slate-500">{mode==='transfers'?'شماره حواله صادرشده را جست‌وجو و در مقصد پذیرش کنید؛ یا یک حواله چندقلمی جدید بسازید.':'شماره فاکتور و طرف حساب را یک‌بار وارد کنید؛ همه کالاها و تنوع‌ها در یک سند ثبت می‌شوند.'}</p></div><button className="btn-primary" disabled={!options} onClick={begin}><Plus size={16}/>{mode==='transfers'?'صدور حواله چندقلمی':'ثبت صورتحساب / تعدیل'}</button></div>
  <div className="flex flex-wrap gap-3"><label className="relative min-w-52 flex-1"><Search className="absolute right-3 top-3 size-4 text-slate-400"/><input className="input pr-10" aria-label="جست‌وجوی اسناد" placeholder={mode==='transfers'?'شماره حواله یا نام مسئول انتقال…':'شماره داخلی، شماره فاکتور یا نام صاحب کالا…'} value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></label>{mode==='transfers'&&<select aria-label="وضعیت حواله" className="input sm:w-60" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">همه وضعیت‌ها</option>{['issued','received','received_with_difference'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select>}</div>
  {error&&<div role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}<button className="btn-sm mr-3" onClick={refresh}>تلاش دوباره</button></div>}
  <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><table className="w-full min-w-[760px] text-right text-sm"><thead className="bg-slate-50 text-xs text-slate-500 dark:bg-slate-800"><tr>{['شماره / تاریخ','نوع / وضعیت',mode==='transfers'?'مبدأ ← مقصد / مسئول':'طرف حساب / شماره فاکتور','اقلام',mode==='transfers'?'مغایرت':'مبلغ / پرداخت اولیه','عملیات'].map(s=><th className="p-3" key={s}>{s}</th>)}</tr></thead><tbody>{rows.map(d=><tr key={d.id} className="border-t border-slate-100 dark:border-slate-800"><td className="p-3"><b dir="ltr">{d.number}</b><small className="mt-1 block text-slate-500">{jdate(d.documentDate)}</small></td><td className="p-3"><span className="block">{labels[d.type]}</span><small className={d.status==='received_with_difference'?'text-rose-600':'text-slate-500'}>{labels[d.status]}</small></td><td className="p-3">{mode==='transfers'?<>{d.fromWarehouseName} ← {d.toWarehouseName}<small className="block text-slate-500">مسئول: {d.responsibleName}</small></>:<>{d.partyName??'تعدیل موجودی'}<small className="block text-slate-500">فاکتور: {d.invoiceNumber||'—'}</small></>}</td><td className="p-3">{faNum(d.items.length)}</td><td className="p-3">{mode==='transfers'?<span className="text-xs">{d.status==='issued'?'در انتظار شمارش':d.items.some(i=>i.receivedQuantity!==i.quantity)?d.items.filter(i=>i.receivedQuantity!==i.quantity).map(i=><span key={key(i)} className="block text-rose-600">{i.title}: {faNum((i.receivedQuantity??0)-i.quantity)} {i.unit}</span>):'بدون مغایرت'}</span>:<>{toman(d.total)}<small className="block text-slate-500">پرداخت: {toman(d.paidAmount)}</small></>}</td><td className="p-3"><div className="flex flex-wrap gap-1"><button className="btn-sm" onClick={()=>void inspect(d.id)}><FileText size={14}/>جزئیات</button><button className="btn-sm" aria-label={`چاپ ${d.number}`} onClick={()=>setPrintId(d.id)}><Printer size={14}/></button>{d.status==='issued'&&<button className="btn-sm" onClick={()=>void inspect(d.id,true)}><PackageCheck size={14}/>پذیرش مقصد</button>}</div></td></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-sm text-slate-500">{loading?'در حال دریافت اسناد…':'سندی پیدا نشد.'}</p>}</div>
  <div className="flex items-center justify-between text-xs text-slate-500"><span>{faNum(total)} سند · صفحه {faNum(page)} از {faNum(Math.max(1,Math.ceil(total/20)))}</span><div className="flex gap-2"><button className="btn-sm" disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>قبلی</button><button className="btn-sm" disabled={loading||page*20>=total} onClick={()=>setPage(p=>p+1)}>بعدی</button></div></div>
  {editor&&!partyOpen&&<Modal wide title={mode==='transfers'?'صدور حواله انتقال چندقلمی':'ثبت سند خرید / امانی / تعدیل'} onClose={()=>{if(!busy)setEditor(false)}}><form onSubmit={submit} className="space-y-5"><fieldset disabled={busy} className="space-y-5">
    <div className="grid gap-3 rounded-2xl border bg-white p-4 dark:border-slate-700 dark:bg-slate-900 sm:grid-cols-2 lg:grid-cols-3">
      {mode!=='transfers'&&<label className="text-xs font-bold">نوع عملیات<select className="input mt-1" value={form.type} onChange={e=>{patch('type',e.target.value);if(e.target.value!=='adjust')setLines(ls=>ls.map(i=>({...i,quantity:Math.max(1,i.quantity)})))}}>{['purchase','consignment','adjust'].map(t=><option key={t} value={t}>{labels[t]}</option>)}</select></label>}
      <label className="text-xs font-bold">تاریخ سند<div className="mt-1"><JalaliDatePicker value={form.documentDate} onChange={v=>patch('documentDate',v)}/></div></label>
      {mode==='transfers'?<><label className="text-xs font-bold">انبار مبدأ<select required className="input mt-1" value={form.fromWarehouseId} onChange={e=>patch('fromWarehouseId',e.target.value)}><option value="">انتخاب کنید</option>{options?.warehouses.filter(w=>w.enabled).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="text-xs font-bold">انبار مقصد<select required className="input mt-1" value={form.toWarehouseId} onChange={e=>patch('toWarehouseId',e.target.value)}><option value="">انتخاب کنید</option>{options?.warehouses.filter(w=>w.enabled&&String(w.id)!==form.fromWarehouseId).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="text-xs font-bold">نام مسئول انتقال *<input required maxLength={120} className="input mt-1" value={form.responsibleName} onChange={e=>patch('responsibleName',e.target.value)}/></label><label className="text-xs font-bold">تلفن مسئول انتقال<input maxLength={30} className="input mt-1" dir="ltr" value={form.responsiblePhone} onChange={e=>patch('responsiblePhone',e.target.value)}/></label></>:<>
      {form.type!=='adjust'&&<label className="text-xs font-bold"><span className="flex items-center justify-between gap-2">تولیدکننده / صاحب کالا (آمر) *<button type="button" className="btn-sm" onClick={()=>setPartyOpen(true)}>+ ثبت شخص</button></span><select required className="input mt-1" value={form.partyId} onChange={e=>patch('partyId',e.target.value)}><option value="">انتخاب کنید</option>{options?.parties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
      <label className="text-xs font-bold">{form.type==='purchase'?'شماره فاکتور خرید *':'شماره مرجع / قرارداد'}<input required={form.type==='purchase'} maxLength={100} className="input mt-1" value={form.invoiceNumber} onChange={e=>patch('invoiceNumber',e.target.value)}/></label></>}
    </div>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><h3 className="font-bold">اقلام سند ({faNum(lines.length)})</h3><button type="button" className="btn-sm" onClick={()=>setPicker(v=>!v)}><Plus size={14}/>{picker?'بستن انتخاب کالا':'انتخاب چند کالا'}</button></div>
     {picker&&<div className="mt-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><input aria-label="جست‌وجوی اقلام" className="input" placeholder="نام کالا، تنوع یا کد کالا…" value={search} onChange={e=>{setSearch(e.target.value);setPickPage(1)}}/><div className="mt-2 grid max-h-64 gap-1 overflow-y-auto sm:grid-cols-2">{filtered.slice((pickPage-1)*24,pickPage*24).map(i=>{const selected=lines.some(l=>key(l)===key(i));return <label key={key(i)} className={`flex cursor-pointer items-center gap-2 rounded-lg border p-2 text-xs ${selected?'border-amber-400 bg-amber-50 dark:bg-amber-950/30':'border-transparent hover:bg-slate-100 dark:hover:bg-slate-700'}`}><input type="checkbox" checked={selected} onChange={()=>selected?setLines(ls=>ls.filter(l=>key(l)!==key(i))):add(i)}/><span className="min-w-0"><b className="block">{i.label}</b><small className="text-slate-500">{i.sku} · آزاد: {faNum(available(i))} {i.unit}</small></span></label>})}</div><div className="mt-2 flex flex-wrap justify-between gap-2 text-xs"><span>{faNum(filtered.length)} نتیجه</span><button type="button" className="btn-sm" onClick={()=>setLines(old=>{const map=new Map(old.map(i=>[key(i),i]));for(const i of filtered.slice((pickPage-1)*24,pickPage*24))if(!map.has(key(i))&&map.size<100)map.set(key(i),{...i,quantity:1});return [...map.values()]})}>انتخاب همهٔ این صفحه</button><div className="flex gap-2"><button type="button" className="btn-sm" disabled={pickPage===1} onClick={()=>setPickPage(p=>p-1)}>قبلی</button><button type="button" className="btn-sm" disabled={pickPage*24>=filtered.length} onClick={()=>setPickPage(p=>p+1)}>بعدی</button></div></div></div>}
     <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-right text-xs"><thead><tr className="border-b text-slate-500">{['کالا / تنوع','واحد','مقدار',mode==='transfers'?'آزاد مبدأ':'بهای واحد','جمع',''].map((s,i)=><th key={i} className="p-2">{s}</th>)}</tr></thead><tbody>{lines.map(i=><tr key={key(i)} className="border-b last:border-0"><td className="p-2"><b>{i.label}</b><small className="block text-slate-500">{i.sku}</small></td><td className="p-2">{i.unit}</td><td className="w-28 p-2"><input aria-label={`مقدار ${i.label}`} type="number" required step="1" min={form.type==='adjust'?-100000:1} max={100000} className="input w-24" value={i.quantity} onChange={e=>changeLine(key(i),{quantity:Number(e.target.value)})}/></td><td className="p-2">{mode==='transfers'?<span className={i.quantity>available(i)?'text-rose-600 font-bold':''}>{faNum(available(i))}</span>:form.type==='adjust'&&i.quantity<0?<span>{toman(i.unitCost)}</span>:<Amount label={`بهای ${i.label}`} value={i.unitCost} onChange={n=>changeLine(key(i),{unitCost:n})}/>}</td><td className="p-2 whitespace-nowrap">{mode==='transfers'?`${faNum(i.quantity)} ${i.unit}`:toman(i.quantity*i.unitCost)}</td><td className="p-2"><button type="button" aria-label={`حذف ${i.label}`} className="text-rose-600" onClick={()=>setLines(ls=>ls.filter(l=>key(l)!==key(i)))}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{!lines.length&&<p className="py-8 text-center text-sm text-slate-500">کالاهای سند را از فهرست بالا انتخاب کنید.</p>}</div>
     {form.type==='adjust'&&<p className="mt-2 text-xs text-slate-500">عدد مثبت برای ورود و عدد منفی برای خروج است. خروج با بهای جاری انبار ثبت می‌شود.</p>}
    </section>
    {form.type==='purchase'&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(['freight','customs','paidAmount'] as const).map((k,i)=><label key={k} className="text-xs font-bold">{['هزینه حمل کل فاکتور','هزینه گمرک / جانبی کل','پرداخت اولیه'][i]}<div className="mt-1"><Amount label={k} value={form[k]} onChange={v=>patch(k,v)}/></div></label>)}<label className="text-xs font-bold">محل پرداخت<input required={form.paidAmount>0} maxLength={120} className="input mt-1" value={form.paymentLocation} onChange={e=>patch('paymentLocation',e.target.value)} placeholder="بانک / صندوق"/></label><label className="text-xs font-bold">شماره پیگیری رسید پرداخت<input maxLength={100} className="input mt-1" value={form.paymentTrackingNumber} onChange={e=>patch('paymentTrackingNumber',e.target.value)}/></label></div>}
    <label className="block text-xs font-bold">توضیحات سند<textarea maxLength={1000} className="input mt-1 min-h-20" value={form.note} onChange={e=>patch('note',e.target.value)}/></label>
    <div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-amber-50 p-4 text-sm dark:bg-amber-950/30"><div><b>{faNum(lines.length)} قلم</b>{mode!=='transfers'&&<><b className="mr-4">مجموع: {toman(grandTotal)}</b>{form.type==='purchase'&&<span className="mt-1 block text-xs">مانده اولیه: {toman(grandTotal-form.paidAmount)} · حمل و هزینه جانبی بین اقلام توزیع می‌شود.</span>}</>}{mode==='transfers'&&<p className="mt-1 text-xs">پس از صدور، کالا از مبدأ کسر می‌شود؛ ورود مقصد پس از پذیرش ثبت خواهد شد.</p>}{form.type==='consignment'&&<p className="mt-1 text-xs">مالکیت کالا و بهای توافقی برای هر قلم ثبت می‌شود. بدهی خرید ایجاد نمی‌شود.</p>}</div><button disabled={busy||!lines.length} className="btn-primary">{busy?'در حال ثبت…':mode==='transfers'?'صدور و چاپ حواله':'ثبت صورتحساب و چاپ'}</button></div>
  </fieldset></form></Modal>}
  {partyOpen&&<Modal title="ثبت تولیدکننده / صاحب کالا" onClose={()=>setPartyOpen(false)}><InventoryPartyForm onCreated={id=>{void loadOptions().then(()=>{patch('partyId',String(id));setPartyOpen(false)}).catch(e=>toast(e.message,false))}}/></Modal>}
  {detail&&<Modal wide title={`${accept?'پذیرش حواله':'جزئیات سند'} ${detail.number}`} onClose={()=>{if(!busy)setDetail(null)}}><form onSubmit={receive} className="space-y-4"><div className="grid gap-3 rounded-2xl border bg-white p-4 text-sm dark:border-slate-700 dark:bg-slate-900 sm:grid-cols-3"><div>{labels[detail.type]} · {labels[detail.status]}<small className="block text-slate-500">{jdate(detail.documentDate)}</small></div>{detail.type==='transfer'?<><div>{detail.fromWarehouseName} ← {detail.toWarehouseName}</div><div>مسئول انتقال: <b>{detail.responsibleName}</b><small className="block" dir="ltr">{detail.responsiblePhone}</small></div></>:<><div>صاحب کالا: {detail.partyName??'—'}</div><div>شماره فاکتور: {detail.invoiceNumber||'—'}</div></>}<div>ثبت‌کننده: {detail.creatorName||'—'}</div>{detail.receivedAt&&<div>پذیرش: {detail.receiverName||'—'} · {jdate(detail.receivedAt,true)}</div>}</div>
   {accept&&<><label className="block text-sm font-bold">تأیید انبار پذیرنده<select required className="input mt-1" value={toId} onChange={e=>setToId(e.target.value)}>{options?.warehouses.filter(w=>w.enabled).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><p className="rounded-xl bg-amber-50 p-3 text-xs leading-6 text-amber-950 dark:bg-amber-950/30 dark:text-amber-200">تعداد شمارش‌شده را برای همه اقلام وارد کنید؛ برای کالای دریافت‌نشده صفر بزنید. کسری و اضافه به نام مسئول انتقال گزارش می‌شود. اضافهٔ تحویل‌شده بیشتر از حواله، تا ثبت سند تعدیل جداگانه به موجودی اضافه نمی‌شود. کسری در گزارش کالای در راه باقی می‌ماند.</p></>}
   <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-right text-xs"><thead><tr className="border-b">{['کالا / تنوع','واحد','مقدار سند',detail.type==='transfer'?'شمارش مقصد':'بهای واحد',detail.type==='transfer'?'اختلاف / توضیح':'جمع'].map(s=><th key={s} className="p-3">{s}</th>)}</tr></thead><tbody>{detail.items.map(i=>{const r=reports[key(i)];const delta=(accept?r?.receivedQuantity:i.receivedQuantity)??i.quantity;return <tr className="border-b" key={key(i)}><td className="p-3"><b>{i.title}</b><small className="block text-slate-500">{i.sku}</small></td><td className="p-3">{i.unit}</td><td className="p-3">{faNum(i.quantity)}</td><td className="p-3">{detail.type!=='transfer'?toman(i.unitCost):accept?<input aria-label={`شمارش ${i.title}`} required type="number" min={0} max={100000} step={1} className="input w-28" value={r?.receivedQuantity??0} onChange={e=>setReports(rs=>({...rs,[key(i)]:{...rs[key(i)],receivedQuantity:Number(e.target.value)}}))}/>:i.receivedQuantity===undefined?'در انتظار':faNum(i.receivedQuantity)}</td><td className="p-3">{detail.type!=='transfer'?toman(i.total):<><b className={delta!==i.quantity?'text-rose-600':''}>{faNum(delta-i.quantity)} {i.unit}</b>{accept?<input aria-label={`علت اختلاف ${i.title}`} required={delta!==i.quantity} maxLength={500} className="input mt-1" placeholder="علت / شرح مغایرت" value={r?.discrepancyNote??''} onChange={e=>setReports(rs=>({...rs,[key(i)]:{...rs[key(i)],discrepancyNote:e.target.value}}))}/>:<p className="mt-1 text-slate-500">{i.discrepancyNote}</p>}</>}</td></tr>})}</tbody></table></div>
   {detail.type!=='transfer'&&<div className="rounded-xl bg-slate-100 p-3 text-sm dark:bg-slate-800">جمع کالا: {toman(detail.subtotal)} · حمل: {toman(detail.freight)} · جانبی: {toman(detail.customs)}<b className="mt-2 block">مجموع: {toman(detail.total)} · پرداخت اولیه: {toman(detail.paidAmount)}</b><p className="mt-1 text-xs">محل پرداخت: {detail.paymentLocation||'—'} · پیگیری: {detail.paymentTrackingNumber||'—'}</p></div>}
   {detail.note&&<p className="text-sm">توضیحات: {detail.note}</p>}{detail.receiptNote&&<p className="text-sm">توضیح پذیرش: {detail.receiptNote}</p>}
   {accept?<><label className="block text-sm">توضیح نهایی پذیرش<textarea maxLength={1000} className="input mt-1" value={receiptNote} onChange={e=>setReceiptNote(e.target.value)}/></label><button disabled={busy} className="btn-primary w-full">{busy?'در حال ثبت…':'تأیید شمارش و ثبت نهایی پذیرش'}</button></>:<button type="button" className="btn-primary" onClick={()=>{setPrintId(detail.id);setDetail(null)}}><Printer size={16}/>چاپ سند</button>}
  </form></Modal>}
  {printId&&<InvoiceModal title={mode==='transfers'?'پیش‌نمایش و چاپ حواله انتقال':'پیش‌نمایش و چاپ سند انبار'} src={`/print/inventory-document/${printId}`} onClose={()=>setPrintId(null)}/>}
 </div>;
}
