"use client";
import { useMemo, useRef, useState, type FormEvent } from "react";
import { Check, Copy, File, FileText, Folder, FolderPlus, Image as ImageIcon, Loader2, Pencil, Search, Trash2, Upload, Video, X } from "lucide-react";
import { api, toast } from "./client";

type FolderRow={id:number;name:string;slug:string;parentId:number|null;color:string|null;legacyId:number|null};
type MediaRow={id:number;filename:string;alt:string|null;folderId:number|null;mime:string;size:number;externalUrl:string|null;legacySource:string|null;isPublic:boolean;createdAt:string|Date};
const sizeLabel=(n:number)=>n<1048576?`${Math.max(1,Math.round(n/1024)).toLocaleString("fa-IR")} کیلوبایت`:`${(n/1048576).toLocaleString("fa-IR",{maximumFractionDigits:1})} مگابایت`;

export default function MediaLibraryClient({initialFolders,initialFiles}:{initialFolders:FolderRow[];initialFiles:MediaRow[]}){
 const [folders,setFolders]=useState(initialFolders),[files,setFiles]=useState(initialFiles),[folderId,setFolderId]=useState<number|null>(null),[q,setQ]=useState(""),[type,setType]=useState("all"),[selected,setSelected]=useState<MediaRow|null>(null),[busy,setBusy]=useState(false),[folderName,setFolderName]=useState("");
 const inputRef=useRef<HTMLInputElement>(null);
 const visible=useMemo(()=>files.filter(f=>(folderId===null||f.folderId===folderId)&&(!q.trim()||`${f.filename} ${f.alt??""}`.toLowerCase().includes(q.trim().toLowerCase()))&&(type==="all"||f.mime.startsWith(`${type}/`)||(type==="document"&&f.mime==="application/pdf"))),[files,folderId,q,type]);
 const upload=async(list:FileList|null)=>{if(!list?.length)return;setBusy(true);try{for(const file of Array.from(list)){const fd=new FormData();fd.append("file",file);fd.append("kind","library");if(folderId)fd.append("folderId",String(folderId));const r=await fetch("/api/media",{method:"POST",headers:{"x-csrf":"1"},body:fd}),j=await r.json();if(!r.ok)throw new Error(j.error??"خطا در بارگذاری");setFiles(rows=>[{id:j.id,filename:file.name,alt:null,folderId,mime:j.mime,size:file.size,externalUrl:null,legacySource:null,isPublic:true,createdAt:new Date().toISOString()},...rows])}toast("فایل‌ها به مرکز فایل افزوده شدند")}catch(e){toast((e as Error).message,false)}finally{setBusy(false);if(inputRef.current)inputRef.current.value=""}};
 const addFolder=async(e:FormEvent)=>{e.preventDefault();if(!folderName.trim())return;setBusy(true);try{const row=await api<FolderRow>("/api/admin/media/folders","POST",{name:folderName,parentId:folderId});setFolders(x=>[...x,row]);setFolderName("");toast("پوشه ساخته شد")}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
 const renameFolder=async(f:FolderRow)=>{const name=prompt("نام جدید پوشه",f.name)?.trim();if(!name||name===f.name)return;try{const row=await api<FolderRow>(`/api/admin/media/folders/${f.id}`,"POST",{...f,name});setFolders(x=>x.map(y=>y.id===f.id?row:y));toast("نام پوشه تغییر کرد")}catch(e){toast((e as Error).message,false)}};
 const deleteFolder=async(f:FolderRow)=>{if(!confirm(`پوشه «${f.name}» حذف شود؟`))return;try{await api(`/api/admin/media/folders/${f.id}`,"POST",{delete:true});setFolders(x=>x.filter(y=>y.id!==f.id));if(folderId===f.id)setFolderId(null);toast("پوشه حذف شد")}catch(e){toast((e as Error).message,false)}};
 const saveFile=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;const fd=new FormData(e.currentTarget);setBusy(true);try{const row=await api<MediaRow>(`/api/admin/media/${selected.id}`,"POST",{filename:fd.get("filename"),alt:fd.get("alt"),folderId:fd.get("folderId")||null,isPublic:fd.get("isPublic")==="on"});setFiles(x=>x.map(y=>y.id===row.id?row:y));setSelected(row);toast("اطلاعات فایل ذخیره شد")}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
 const deleteFile=async()=>{if(!selected||!confirm(`فایل «${selected.filename}» حذف شود؟`))return;try{await api(`/api/admin/media/${selected.id}`,"POST",{delete:true});setFiles(x=>x.filter(y=>y.id!==selected.id));setSelected(null);toast("فایل حذف شد")}catch(e){toast((e as Error).message,false)}};
 const icon=(mime:string)=>mime.startsWith("image/")?<ImageIcon className="size-6"/>:mime.startsWith("video/")?<Video className="size-6"/>:mime==="application/pdf"?<FileText className="size-6"/>:<File className="size-6"/>;
 return <div className="grid min-w-0 gap-5 xl:grid-cols-[260px_minmax(0,1fr)]">
  <aside className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><form onSubmit={addFolder} className="flex gap-2"><input className="input min-w-0" value={folderName} onChange={e=>setFolderName(e.target.value)} placeholder="پوشه جدید"/><button disabled={busy} className="btn-sm shrink-0"><FolderPlus className="size-4"/></button></form><button onClick={()=>setFolderId(null)} className={`mt-4 flex w-full items-center gap-2 rounded-xl px-3 py-2 text-right text-sm ${folderId===null?"bg-emerald-50 font-bold text-emerald-700":"hover:bg-slate-50"}`}><Folder className="size-4"/>همه فایل‌ها <span className="mr-auto text-xs text-slate-400">{files.length.toLocaleString("fa-IR")}</span></button><div className="mt-1 space-y-1">{folders.map(f=><div key={f.id} className={`group flex items-center rounded-xl ${folderId===f.id?"bg-emerald-50 text-emerald-700":"hover:bg-slate-50"}`}><button onClick={()=>setFolderId(f.id)} className="flex min-w-0 flex-1 items-center gap-2 px-2 py-2 text-right text-sm"><Folder className="size-4 shrink-0"/><span className="truncate">{f.name}</span><span className="mr-auto text-[10px] text-slate-400">{files.filter(x=>x.folderId===f.id).length.toLocaleString("fa-IR")}</span></button><button onClick={()=>renameFolder(f)} className="p-1 text-slate-400 opacity-0 group-hover:opacity-100"><Pencil className="size-3"/></button><button onClick={()=>deleteFolder(f)} className="p-1 text-rose-400 opacity-0 group-hover:opacity-100"><Trash2 className="size-3"/></button></div>)}</div></aside>
  <section className="min-w-0 space-y-4"><div className="flex flex-wrap items-center gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><div className="relative min-w-48 flex-1"><Search className="absolute right-3 top-2.5 size-4 text-slate-400"/><input className="input h-10 pr-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="جست‌وجوی فایل"/></div><select className="input w-full sm:w-40" value={type} onChange={e=>setType(e.target.value)}><option value="all">همه نوع‌ها</option><option value="image">تصویر</option><option value="video">ویدیو</option><option value="document">سند</option></select><label className="btn-primary cursor-pointer">{busy?<Loader2 className="size-4 animate-spin"/>:<Upload className="size-4"/>}بارگذاری<input ref={inputRef} type="file" multiple hidden accept="image/jpeg,image/png,image/webp,image/gif,application/pdf,video/mp4,video/webm" onChange={e=>upload(e.target.files)}/></label></div>
  {visible.length?<div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 2xl:grid-cols-5">{visible.map(f=><button key={f.id} onClick={()=>setSelected(f)} className="group min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white text-right shadow-sm transition hover:border-emerald-300 hover:shadow-md"><div className="relative aspect-square bg-slate-100">{f.mime.startsWith("image/")?<img src={`/api/media/${f.id}`} alt={f.alt??f.filename} className="h-full w-full object-cover" loading="lazy"/>:<div className="grid h-full place-items-center text-slate-400">{icon(f.mime)}</div>}{f.legacySource&&<span className="absolute left-2 top-2 rounded-full bg-slate-900/70 px-2 py-0.5 text-[10px] text-white">قدیمی</span>}</div><div className="p-3"><b className="block truncate text-xs">{f.filename}</b><span className="mt-1 block text-[10px] text-slate-400">{sizeLabel(f.size)} · #{f.id.toLocaleString("fa-IR")}</span></div></button>)}</div>:<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500">فایلی پیدا نشد.</div>}</section>
  {selected&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-slate-950/50 sm:items-center sm:p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:rounded-3xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-5 py-4"><div><b>مدیریت فایل</b><small className="mr-2 text-slate-400">#{selected.id.toLocaleString("fa-IR")}</small></div><button onClick={()=>setSelected(null)}><X className="size-5"/></button></header><div className="grid gap-5 p-5 md:grid-cols-[260px_1fr]"><div>{selected.mime.startsWith("image/")?<img src={`/api/media/${selected.id}`} alt="" className="aspect-square w-full rounded-2xl bg-slate-100 object-contain"/>:selected.mime.startsWith("video/")?<video src={`/api/media/${selected.id}`} controls className="aspect-video w-full rounded-2xl bg-black"/>:<a href={`/api/media/${selected.id}`} target="_blank" className="grid aspect-square place-items-center rounded-2xl bg-slate-100 text-slate-400">{icon(selected.mime)}</a>}<button onClick={()=>{navigator.clipboard.writeText(`${location.origin}/api/media/${selected.id}`);toast("نشانی کپی شد")}} className="btn-ghost mt-3 w-full"><Copy className="size-4"/>کپی نشانی</button></div><form onSubmit={saveFile} className="space-y-3"><label className="block text-xs font-bold">نام فایل<input name="filename" defaultValue={selected.filename} className="input mt-1" required/></label><label className="block text-xs font-bold">متن جایگزین<input name="alt" defaultValue={selected.alt??""} className="input mt-1"/></label><label className="block text-xs font-bold">پوشه<select name="folderId" defaultValue={selected.folderId??""} className="input mt-1"><option value="">بدون پوشه</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input name="isPublic" type="checkbox" defaultChecked={selected.isPublic}/>قابل نمایش عمومی</label><div className="rounded-xl bg-slate-50 p-3 text-xs text-slate-500">{selected.mime} · {sizeLabel(selected.size)}{selected.legacySource&&<p className="mt-1 text-amber-700">واردشده از سایت قبلی</p>}</div><div className="flex flex-wrap justify-between gap-2"><button type="button" onClick={deleteFile} className="btn-ghost text-rose-600"><Trash2 className="size-4"/>حذف</button><button disabled={busy} className="btn-primary">{busy?<Loader2 className="size-4 animate-spin"/>:<Check className="size-4"/>}ذخیره</button></div></form></div></div></div>}
 </div>;
}
