"use client";
import { useMemo, useState } from "react";
import { Check, Clock3, MapPin, PackageCheck, Pencil, Plus, X } from "lucide-react";
import { api, toast } from "./client";
import { Card } from "./ui";
import { toman } from "@/lib/util";

type Hours = { day: number; open: string; close: string; closed?: boolean };
type Center = { id: number; name: string; slug: string; city: string; address: string; phone: string | null; latitude: string | null; longitude: string | null; openingHours: Hours[]; dailyCapacity: number; isActive: boolean; createdAt?: Date; updatedAt?: Date };
type PickupOrder = { id: number; number: string; status: string; paymentStatus: string; total: number | null; pickupCenterId: number | null; pickupCenterName: string | null; pickupDate: string | null; pickupTime: string | null; pickupCode: string | null; pickupStatus: string | null; pickupReadyAt: Date | null; pickupCompletedAt: Date | null; customerName: string; customerPhone: string; createdAt: Date };
const days = ["یکشنبه", "دوشنبه", "سه‌شنبه", "چهارشنبه", "پنجشنبه", "جمعه", "شنبه"];
const defaults = (): Hours[] => days.map((_, day) => ({ day, open: "09:00", close: "17:00", closed: day === 5 }));
const blank = (): Omit<Center, "id"> => ({ name: "", slug: "", city: "", address: "", phone: "", latitude: "", longitude: "", openingHours: defaults(), dailyCapacity: 30, isActive: true });
const formatDate = (date: string | null) => date ? new Intl.DateTimeFormat("fa-IR", { dateStyle: "medium", timeZone: "Asia/Tehran" }).format(new Date(`${date}T12:00:00+03:30`)) : "—";

export function PickupManager({ initialCenters, initialOrders, databaseReady }: { initialCenters: Center[]; initialOrders: PickupOrder[]; databaseReady: boolean }) {
  const [centers, setCenters] = useState(initialCenters), [orders, setOrders] = useState(initialOrders);
  const [editing, setEditing] = useState<Center | null>(null), [form, setForm] = useState<Omit<Center, "id">>(blank()), [saving, setSaving] = useState(false);
  const canSave = databaseReady && !saving;
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setSaving(true);
    try {
      const saved = await api<Center>(editing ? `/api/admin/pickup-centers/${editing.id}` : "/api/admin/pickup-centers", "POST", { ...form, slug: form.slug || form.name });
      setCenters((list) => editing ? list.map((item) => item.id === saved.id ? saved : item) : [saved, ...list]); setEditing(null); setForm(blank()); toast("مرکز دریافت ذخیره شد");
    } catch (error) { toast((error as Error).message, false); } finally { setSaving(false); }
  };
  const updateHour = (day: number, patch: Partial<Hours>) => setForm((value) => ({ ...value, openingHours: value.openingHours.map((item) => item.day === day ? { ...item, ...patch } : item) }));
  const mark = async (order: PickupOrder, status: "ready" | "completed") => {
    try { await api(`/api/admin/pickup-orders/${order.id}`, "POST", { status }); setOrders((list) => list.map((item) => item.id === order.id ? { ...item, pickupStatus: status } : item)); toast(status === "ready" ? "سفارش آماده تحویل شد" : "تحویل سفارش ثبت شد"); }
    catch (error) { toast((error as Error).message, false); }
  };
  const activeCount = useMemo(() => centers.filter((center) => center.isActive).length, [centers]);
  return <div className="space-y-6">
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-4"><div className="text-xs text-slate-500">مراکز فعال</div><b className="mt-2 block text-2xl">{activeCount.toLocaleString("fa-IR")}</b></div><div className="rounded-2xl border bg-white p-4"><div className="text-xs text-slate-500">سفارش‌های دریافت حضوری</div><b className="mt-2 block text-2xl">{orders.length.toLocaleString("fa-IR")}</b></div><div className="rounded-2xl border bg-white p-4"><div className="text-xs text-slate-500">رزرو در انتظار</div><b className="mt-2 block text-2xl">{orders.filter((item) => item.pickupStatus === "awaiting").length.toLocaleString("fa-IR")}</b></div></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_420px]">
      <div className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-lg font-black">مراکز ثبت‌شده</h2><button disabled={!databaseReady} className="btn-primary" onClick={() => { setEditing(null); setForm(blank()); }}><Plus className="size-4"/>مرکز جدید</button></div>
        {centers.length ? centers.map((center) => <Card key={center.id} title={<span className="flex flex-wrap items-center gap-2">{center.name}<span className={`rounded-full px-2 py-0.5 text-[10px] ${center.isActive ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{center.isActive ? "فعال" : "غیرفعال"}</span></span>} action={<button className="btn-sm" disabled={!databaseReady} onClick={() => { setEditing(center); setForm({ ...center }); }}><Pencil className="size-3.5"/>ویرایش</button>}><div className="space-y-2 text-sm text-slate-600"><div className="flex items-start gap-2"><MapPin className="mt-0.5 size-4 shrink-0 text-amber-600"/>{center.city}، {center.address}</div><div className="flex flex-wrap gap-3 text-xs"><span>ظرفیت روزانه: {center.dailyCapacity.toLocaleString("fa-IR")} سفارش</span>{center.phone && <span>تلفن: {center.phone}</span>}{center.latitude && center.longitude && <a className="text-amber-700 underline" target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${center.latitude}&mlon=${center.longitude}#map=16/${center.latitude}/${center.longitude}`}>نمایش روی نقشه</a>}</div><div className="flex flex-wrap gap-1">{center.openingHours.map((hour) => <span key={hour.day} className="rounded-lg bg-slate-50 px-2 py-1 text-[10px]">{days[hour.day]}: {hour.closed ? "تعطیل" : `${hour.open}–${hour.close}`}</span>)}</div></div></Card>) : <div className="rounded-2xl border border-dashed p-8 text-center text-sm text-slate-500">هنوز مرکزی تعریف نشده است.</div>}
      </div>
      <Card title={editing ? "ویرایش مرکز دریافت" : "افزودن مرکز دریافت"} action={editing && <button className="btn-ghost" onClick={() => { setEditing(null); setForm(blank()); }}><X className="size-4"/></button>}>
        <form className="space-y-3" onSubmit={submit}>
          <div className="grid gap-2 sm:grid-cols-2"><input className="input" placeholder="نام مرکز" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required/><input className="input" placeholder="شناسه URL (اختیاری)" dir="ltr" value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })}/><input className="input" placeholder="شهر" value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} required/><input className="input" placeholder="شماره تماس" dir="ltr" value={form.phone ?? ""} onChange={(e) => setForm({ ...form, phone: e.target.value })}/></div>
          <textarea className="input min-h-20" placeholder="نشانی کامل" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} required minLength={8}/>
          <div className="grid grid-cols-2 gap-2"><input className="input" placeholder="عرض جغرافیایی" dir="ltr" value={form.latitude ?? ""} onChange={(e) => setForm({ ...form, latitude: e.target.value })}/><input className="input" placeholder="طول جغرافیایی" dir="ltr" value={form.longitude ?? ""} onChange={(e) => setForm({ ...form, longitude: e.target.value })}/><label className="text-xs text-slate-600">ظرفیت دریافت روزانه<input type="number" className="input mt-1" min={1} value={form.dailyCapacity} onChange={(e) => setForm({ ...form, dailyCapacity: Number(e.target.value) })}/></label><label className="flex items-center gap-2 pt-5 text-sm"><input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })}/>مرکز فعال باشد</label></div>
          <div><b className="text-sm">ساعت کاری هفتگی</b><div className="mt-2 space-y-1.5">{form.openingHours.map((hour) => <div key={hour.day} className="grid grid-cols-[1fr_auto_86px_86px] items-center gap-2 rounded-lg bg-slate-50 px-2 py-1.5 text-xs"><span>{days[hour.day]}</span><label className="flex items-center gap-1"><input type="checkbox" checked={!!hour.closed} onChange={(e) => updateHour(hour.day, { closed: e.target.checked })}/>تعطیل</label><input aria-label={`${days[hour.day]} ساعت شروع`} className="input h-8 px-2 text-center" type="time" disabled={hour.closed} value={hour.open} onChange={(e) => updateHour(hour.day, { open: e.target.value })}/><input aria-label={`${days[hour.day]} ساعت پایان`} className="input h-8 px-2 text-center" type="time" disabled={hour.closed} value={hour.close} onChange={(e) => updateHour(hour.day, { close: e.target.value })}/></div>)}</div></div>
          {!databaseReady && <p className="rounded-lg bg-amber-50 p-2 text-xs text-amber-800">برای ذخیره، migration دیتابیس برنامه را اجرا کنید.</p>}
          <button disabled={!canSave} className="btn-primary w-full">{saving ? "در حال ذخیره…" : editing ? "ذخیره تغییرات" : "ایجاد مرکز"}</button>
        </form>
      </Card>
    </div>
    <section><div className="mb-3 flex items-center gap-2"><PackageCheck className="size-5 text-amber-700"/><h2 className="text-lg font-black">رزروهای دریافت حضوری</h2></div><div className="grid gap-3 lg:grid-cols-2">{orders.length ? orders.map((order) => <article key={order.id} className="rounded-2xl border bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><b>#{order.number}</b><div className="mt-1 text-xs text-slate-500">{order.customerName} · {order.customerPhone}</div></div><span className="rounded-full bg-amber-50 px-2 py-1 text-xs text-amber-800">{order.pickupStatus === "completed" ? "تحویل‌شده" : order.pickupStatus === "ready" ? "آماده تحویل" : "در انتظار آماده‌سازی"}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-600"><span>{order.pickupCenterName}</span><span>{formatDate(order.pickupDate)}، ساعت {order.pickupTime}</span><span>کد تحویل: <b className="font-mono text-slate-900">{order.pickupCode ?? "—"}</b></span><span>مبلغ: {toman(order.total ?? 0)}</span></div><div className="mt-3 flex justify-end">{order.pickupStatus === "awaiting" && <button disabled={!databaseReady || order.paymentStatus !== "paid"} className="btn-primary" onClick={() => mark(order, "ready")}><Clock3 className="size-4"/>آماده تحویل</button>}{order.pickupStatus === "ready" && <button disabled={!databaseReady} className="btn-primary" onClick={() => mark(order, "completed")}><Check className="size-4"/>ثبت تحویل به مشتری</button>}{order.paymentStatus !== "paid" && order.pickupStatus !== "completed" && <span className="text-xs text-amber-700">پس از پرداخت امکان آماده‌سازی فعال می‌شود</span>}</div></article>) : <div className="rounded-2xl border border-dashed p-8 text-center text-sm text-slate-500 lg:col-span-2">هنوز سفارشی برای دریافت حضوری ثبت نشده است.</div>}</div></section>
  </div>;
}
