"use client";
import { useEffect } from "react";
import { jdate, toman } from "@/lib/util";
import { fillLabel } from "./LabelView";

type Line = { title: string; quantity: number; unitPrice: number; lineTotal: number };
type Design = { invoiceWidth: number; invoiceFontSize: number; invoicePadding: number; invoiceBorderStyle: string; invoiceBorderColor: string; invoiceAccentColor: string; invoiceHeaderTemplate: string; invoiceFooter: string; siteTagline: string; siteLogoMediaId: number; invoiceShowLogo: number; invoiceShowSiteName: number; invoiceShowTagline: number; invoiceShowHeaderTemplate: number; invoiceShowBuyer: number; invoiceShowItems: number; invoiceShowShipping: number; invoiceShowPayments: number; invoiceShowFooter: number; invoiceShowSignatures: number };
export function PosInvoice({ sale, items, shop, autoPrint = false, embedded = false, terminal, labelHref, design }: {
  sale: { number: string; customerName: string; customerPhone: string; shippingCity?: string | null; shippingAddress?: string | null; shippingPostalCode?: string | null; shippingCarrierName?: string | null; shippingFreightCollect?: boolean; shippingCost?: number; subtotal: number; discount: number; total: number; paymentMethod: string; settlement: { cash: number; card: number }; createdAt: Date };
  items: Line[]; shop: string; autoPrint?: boolean; embedded?: boolean; terminal?: string; labelHref?: string; design?: Design;
}) {
  useEffect(() => { if (autoPrint) { const t = window.setTimeout(() => window.print(), 350); return () => window.clearTimeout(t); } }, [autoPrint]);
  const headerText = design ? fillLabel(design.invoiceHeaderTemplate, { siteName: shop, invoiceNumber: sale.number, date: jdate(sale.createdAt, true) }) : "";
  const borderColor = design?.invoiceBorderColor ?? "#94a3b8";
  const accent = design?.invoiceAccentColor ?? "#166534";
  const border = design?.invoiceBorderStyle === "none" ? "none" : design?.invoiceBorderStyle === "dashed" ? `2px dashed ${borderColor}` : `1px solid ${borderColor}`;
  const show = (key: keyof Design) => !design || Number(design[key]) === 1;
  return <main dir="rtl" className="invoice-sheet mx-auto bg-white text-stone-900 shadow print:max-w-none print:p-2" style={{ maxWidth: design ? `${design.invoiceWidth}mm` : "36rem", fontSize: design ? `${design.invoiceFontSize}px` : undefined, padding: design ? `${design.invoicePadding}mm` : "1.5rem", border }}>
    {show("invoiceShowHeaderTemplate") && design && <div className="mb-4 whitespace-pre-line border-b-2 pb-3 text-center font-bold" style={{ borderColor }}>{headerText}</div>}
    <div className="mb-5 flex items-start justify-between border-b pb-4" style={{ borderColor: accent }}><div className="flex items-center gap-2">{show("invoiceShowLogo") && design?.siteLogoMediaId ? <img src={`/api/media/${design.siteLogoMediaId}`} alt="لوگو" className="h-12 w-12 object-contain" /> : null}<div>{show("invoiceShowSiteName") && <h1 className="text-2xl font-black" style={{ color: accent }}>{shop}</h1>}{show("invoiceShowTagline") && <p className="mt-1 text-sm">{design?.siteTagline || "فاکتور فروش حضوری"}</p>}</div></div><div className="text-left text-sm"><b dir="ltr">{sale.number}</b><p className="mt-1">{jdate(sale.createdAt, true)}</p></div></div>
    {show("invoiceShowBuyer") && <div className="mb-4 flex justify-between text-sm"><span>{sale.customerName}</span><span dir="ltr">{sale.customerPhone}</span></div>}
    {show("invoiceShowShipping") && sale.shippingAddress && <div className="mb-4 rounded-lg border p-3 text-sm" style={{ borderColor }}><b>نشانی گیرنده</b><p className="mt-1">{sale.shippingCity} — {sale.shippingAddress}</p><p className="mt-1">کد پستی: <span dir="ltr">{sale.shippingPostalCode}</span></p></div>}
    {show("invoiceShowItems") && <table className="w-full text-right text-sm"><thead><tr className="border-y" style={{ borderColor: accent }}><th className="py-2">شرح کالا</th><th>تعداد</th><th>قیمت</th><th>جمع</th></tr></thead><tbody>{items.map((x, i) => <tr key={i} className="border-b" style={{ borderColor }}><td className="py-2">{x.title}</td><td>{x.quantity.toLocaleString("fa-IR")}</td><td>{toman(x.unitPrice)}</td><td>{toman(x.lineTotal)}</td></tr>)}</tbody></table>}
    <div className="mt-4 space-y-2 text-sm"><p className="flex justify-between"><span>جمع کالاها</span><b>{toman(sale.subtotal)}</b></p><p className="flex justify-between"><span>تخفیف</span><b>{toman(sale.discount)}</b></p>{show("invoiceShowShipping") && (sale.shippingFreightCollect ? <p className="flex justify-between rounded bg-amber-50 p-2 font-bold text-amber-900"><span>ارسال پس‌کرایه {sale.shippingCarrierName ? `(${sale.shippingCarrierName})` : ""}</span><b>پرداخت هزینه به شرکت پستی هنگام تحویل</b></p> : sale.shippingCost !== undefined && sale.shippingCost > 0 && <p className="flex justify-between"><span>هزینه ارسال {sale.shippingCarrierName ? `(${sale.shippingCarrierName})` : ""}</span><b>{toman(sale.shippingCost)}</b></p>)}<p className="flex justify-between border-t pt-2 text-base" style={{ borderColor: accent, color: accent }}><span>مبلغ نهایی</span><b>{toman(sale.total)}</b></p>{show("invoiceShowPayments") && <p className="flex justify-between text-xs text-stone-600"><span>نقدی / کارت</span><span>{toman(sale.settlement.cash)} / {toman(sale.settlement.card)}</span></p>}</div>
    {show("invoiceShowFooter") && <p className="mt-8 border-t pt-3 text-center text-xs" style={{ borderColor }}>{design?.invoiceFooter || "از خرید محصولات ارگانیک سپاسگزاریم 🌱"}</p>}{show("invoiceShowSignatures") && <footer className="mt-8 grid grid-cols-2 gap-8 text-center text-xs"><div className="border-t pt-2" style={{ borderColor }}>مهر و امضای فروشنده</div><div className="border-t pt-2" style={{ borderColor }}>امضای خریدار</div></footer>}{terminal && <p className="mt-3 text-xs">کارتخوان: {terminal}</p>}
    <div className="mt-5 flex flex-col gap-2 print:hidden">{!embedded && <button className="btn-primary w-full" onClick={() => window.print()}>چاپ فاکتور (Enter)</button>}{labelHref && <a className="btn-ghost w-full" href={labelHref} target="_blank" rel="noreferrer">چاپ لیبل پستی گیرنده</a>}</div>
  </main>;
}
