"use client";
import { useEffect, useState, type FormEvent } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { api, toast } from "./client";

type Terminal={id:number;name:string;bankName:string|null;terminalCode:string|null;enabled:boolean};
export default function PosTerminalManager({listUrl,manageUrl}:{listUrl:string;manageUrl:string}){
 const [rows,setRows]=useState<Terminal[]>([]),[name,setName]=useState(""),[bankName,setBankName]=useState(""),[terminalCode,setTerminalCode]=useState(""),[editing,setEditing]=useState<number|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const refresh=async()=>{try{setRows(await api<Terminal[]>(listUrl,"GET"))}catch(e){toast((e as Error).message,false)}finally{setLoading(false)}};
 useEffect(()=>{let active=true;api<Terminal[]>(listUrl,"GET").then(x=>{if(active)setRows(x)}).catch(e=>{if(active)toast((e as Error).message,false)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[listUrl]);
 const save=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await api(editing?`${manageUrl}/${editing}`:manageUrl,editing?"PUT":"POST",{name,bankName,terminalCode,enabled:true});setName("");setBankName("");setTerminalCode("");setEditing(null);toast(editing?"کارتخوان ویرایش شد":"کارتخوان ثبت شد");await refresh()}catch(e){toast((e as Error).message,false)}finally{setBusy(false)}};
 const toggle=async(r:Terminal)=>{try{await api(`${manageUrl}/${r.id}`,"PUT",{...r,enabled:!r.enabled});toast("وضعیت کارتخوان به‌روز شد");await refresh()}catch(e){toast((e as Error).message,false)}};
 const remove=async(r:Terminal)=>{if(!window.confirm(`کارتخوان «${r.name}» حذف شود؟`))return;try{await api(`${manageUrl}/${r.id}`,"DELETE");toast("کارتخوان حذف شد");await refresh()}catch(e){toast((e as Error).message,false)}};
 return <div className="mt-4 grid items-start gap-4 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={save} className="rounded-xl border bg-slate-50 p-4"><h3 className="font-bold">{editing?"ویرایش دستگاه پوز":"افزودن دستگاه پوز"}</h3><label className="mt-3 block text-xs font-bold">نام نمایشی<input required className="input mt-1" value={name} onChange={e=>setName(e.target.value)} placeholder="مثلاً پوز بانک ملت صندوق ۱"/></label><label className="mt-3 block text-xs font-bold">بانک یا شرکت پرداخت<input className="input mt-1" value={bankName} onChange={e=>setBankName(e.target.value)} placeholder="اختیاری"/></label><label className="mt-3 block text-xs font-bold">شناسه ترمینال<input dir="ltr" className="input mt-1" value={terminalCode} onChange={e=>setTerminalCode(e.target.value)} placeholder="اختیاری"/></label><div className="mt-4 flex gap-2"><button disabled={busy} className="btn-primary flex-1"><Plus className="size-4"/>{editing?"ذخیره تغییرات":"ثبت کارتخوان"}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setName("");setBankName("");setTerminalCode("")}} className="btn-sm">لغو</button>}</div></form><section className="rounded-xl border p-4"><h3 className="font-bold">دستگاه‌های تعریف‌شده</h3>{loading?<p className="p-5 text-sm text-slate-500">در حال بارگذاری…</p>:rows.length?<div className="mt-3 divide-y">{rows.map(r=><div key={r.id} className="flex flex-wrap items-center gap-3 py-3"><div className="min-w-0 flex-1"><b>{r.name}</b><p className="mt-1 text-xs text-slate-500">{r.bankName||"بدون نام بانک"}{r.terminalCode?` · شناسه ${r.terminalCode}`:""}</p></div><button onClick={()=>{setEditing(r.id);setName(r.name);setBankName(r.bankName??"");setTerminalCode(r.terminalCode??"")}} aria-label={`ویرایش ${r.name}`} className="text-slate-500"><Pencil className="size-4"/></button><button onClick={()=>toggle(r)} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${r.enabled?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{r.enabled?"فعال":"غیرفعال"}</button><button onClick={()=>remove(r)} aria-label={`حذف ${r.name}`} className="text-rose-600"><Trash2 className="size-4"/></button></div>)}</div>:<p className="py-6 text-center text-sm text-slate-500">هنوز کارتخوانی ثبت نشده است.</p>}</section></div>
}
