"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Plus, Trash2, Loader2 } from "lucide-react";
import { api, toast } from "./client";
import { Barcode } from "./LabelView";

type ProductType = { name: string; parameters: string[] };
type Initial = { productTypes: ProductType[]; invoiceWidth: number; invoiceFontSize: number; invoiceHeaderTemplate: string; invoiceBorderStyle: string; barcodeLabelWidth: number; barcodeLabelHeight: number; barcodeFontSize: number; barcodeShowProductName: number; barcodeShowSku: number };
export function PrintDesignManager({ initial }: { initial: Initial }) {
  const router = useRouter();
  const [types, setTypes] = useState<ProductType[]>(initial.productTypes ?? []);
  const [newName, setNewName] = useState("");
  const [newParams, setNewParams] = useState("");
  const [invoice, setInvoice] = useState({ invoiceWidth: initial.invoiceWidth, invoiceFontSize: initial.invoiceFontSize, invoiceHeaderTemplate: initial.invoiceHeaderTemplate, invoiceBorderStyle: initial.invoiceBorderStyle });
  const [barcode, setBarcode] = useState({ barcodeLabelWidth: initial.barcodeLabelWidth, barcodeLabelHeight: initial.barcodeLabelHeight, barcodeFontSize: initial.barcodeFontSize, barcodeShowProductName: initial.barcodeShowProductName, barcodeShowSku: initial.barcodeShowSku });
  const [busy, setBusy] = useState(false);
  async function save(data: object, message: string) { setBusy(true); try { await api("/api/admin/settings", "POST", data); toast(message); router.refresh(); } catch (e) { toast((e as Error).message, false); } finally { setBusy(false); } }
  const addType = () => { const name = newName.trim(); if (!name || types.some((t) => t.name === name)) return; setTypes([...types, { name, parameters: [...new Set(newParams.split(/[,،\n]/).map((x) => x.trim()).filter(Boolean))] }]); setNewName(""); setNewParams(""); };
  return <div className="mt-8 space-y-6">
    <section className="rounded-2xl border border-slate-200 bg-white p-5">
      <h2 className="text-lg font-bold">نوع محصول و پارامترها</h2><p className="mb-4 mt-1 text-sm text-slate-500">نوع محصول اختیاری است. پارامترهای تعریف‌شده هنگام ثبت محصول به شکل مشخصه‌های پیشنهادی در دسترس قرار می‌گیرند.</p>
      <div className="grid gap-3 md:grid-cols-[1fr_2fr_auto]"><label className="text-sm">نام نوع<input className="input mt-1" value={newName} onChange={(e) => setNewName(e.target.value)} placeholder="مثلاً عسل" /></label><label className="text-sm">پارامترها (با کاما جدا کنید)<input className="input mt-1" value={newParams} onChange={(e) => setNewParams(e.target.value)} placeholder="منطقه برداشت، نوع گل، روش فرآوری" /></label><button type="button" className="btn-sm self-end" onClick={addType}><Plus className="h-4 w-4" />افزودن نوع</button></div>
      <div className="mt-4 space-y-2">{types.map((t, i) => <div key={`${t.name}-${i}`} className="grid gap-2 rounded-xl border border-slate-100 p-3 md:grid-cols-[1fr_2fr_auto]"><input aria-label="نام نوع" className="input" value={t.name} onChange={(e) => setTypes(types.map((x, n) => n === i ? { ...x, name: e.target.value } : x))} /><input aria-label="پارامترها" className="input" value={t.parameters.join("، ")} onChange={(e) => setTypes(types.map((x, n) => n === i ? { ...x, parameters: [...new Set(e.target.value.split(/[,،]/).map((v) => v.trim()).filter(Boolean))] } : x))} /><button type="button" className="btn-sm text-rose-600" aria-label="حذف نوع" onClick={() => setTypes(types.filter((_, n) => n !== i))}><Trash2 className="h-4 w-4" />حذف</button></div>)}{!types.length && <p className="text-sm text-slate-400">هنوز نوعی تعریف نشده است.</p>}</div>
      <button disabled={busy} className="btn-primary mt-4" onClick={() => save({ productTypes: types }, "نوع محصولات ذخیره شد")}>{busy && <Loader2 className="h-4 w-4 animate-spin" />}ذخیره نوع‌ها</button>
    </section>
    <section className="grid gap-6 lg:grid-cols-2">
      <div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-3 text-lg font-bold">طراحی فاکتور فروش</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">عرض چاپ (mm)<input type="number" className="input mt-1" value={invoice.invoiceWidth} onChange={(e) => setInvoice({ ...invoice, invoiceWidth: Number(e.target.value) })} /></label><label className="text-sm">اندازه فونت (px)<input type="number" className="input mt-1" value={invoice.invoiceFontSize} onChange={(e) => setInvoice({ ...invoice, invoiceFontSize: Number(e.target.value) })} /></label><label className="text-sm sm:col-span-2">قالب سربرگ<textarea className="input mt-1 min-h-24 font-mono text-xs" value={invoice.invoiceHeaderTemplate} onChange={(e) => setInvoice({ ...invoice, invoiceHeaderTemplate: e.target.value })} /></label><label className="text-sm">کادر فاکتور<select className="input mt-1" value={invoice.invoiceBorderStyle} onChange={(e) => setInvoice({ ...invoice, invoiceBorderStyle: e.target.value })}><option value="solid">خط ممتد</option><option value="dashed">خط‌چین</option><option value="none">بدون کادر</option></select></label></div><p className="mt-2 text-xs text-slate-500">متغیرها: {`{siteName}`}، {`{invoiceNumber}`}، {`{date}`}</p><div className="mt-3 rounded-lg bg-slate-50 p-3 text-center text-sm" style={{ fontSize: invoice.invoiceFontSize }}><b>{invoice.invoiceHeaderTemplate.replaceAll("{siteName}", "فروشگاه ارگانیک").replaceAll("{invoiceNumber}", "INV-1405-123").replaceAll("{date}", "۱۴۰۵/۰۷/۱۲")}</b><div className="mt-2 border-t border-slate-300 pt-2">پیش‌نمایش سربرگ · جدول کالاها و مبالغ در فاکتور حفظ می‌شود</div></div><button disabled={busy} className="btn-primary mt-4" onClick={() => save(invoice, "طراحی فاکتور ذخیره شد")}>ذخیره طراحی فاکتور</button></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-3 text-lg font-bold">تنظیمات برچسب بارکد تنوع‌ها</h2><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">عرض (mm)<input type="number" className="input mt-1" value={barcode.barcodeLabelWidth} onChange={(e) => setBarcode({ ...barcode, barcodeLabelWidth: Number(e.target.value) })} /></label><label className="text-sm">ارتفاع (mm)<input type="number" className="input mt-1" value={barcode.barcodeLabelHeight} onChange={(e) => setBarcode({ ...barcode, barcodeLabelHeight: Number(e.target.value) })} /></label><label className="text-sm">فونت (px)<input type="number" className="input mt-1" value={barcode.barcodeFontSize} onChange={(e) => setBarcode({ ...barcode, barcodeFontSize: Number(e.target.value) })} /></label></div><div className="my-4 flex gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={!!barcode.barcodeShowProductName} onChange={(e) => setBarcode({ ...barcode, barcodeShowProductName: e.target.checked ? 1 : 0 })} />نام محصول</label><label className="flex items-center gap-2"><input type="checkbox" checked={!!barcode.barcodeShowSku} onChange={(e) => setBarcode({ ...barcode, barcodeShowSku: e.target.checked ? 1 : 0 })} />کد SKU</label></div><div className="mx-auto grid place-items-center rounded border border-dashed border-slate-300 bg-slate-50 p-3 text-center" style={{ width: `${Math.min(barcode.barcodeLabelWidth * 2, 300)}px`, minHeight: `${Math.max(barcode.barcodeLabelHeight * 2, 70)}px`, fontSize: barcode.barcodeFontSize }}><b>نمونه محصول ارگانیک</b><Barcode value="ORG-12001" height={34} /></div><button disabled={busy} className="btn-primary mt-4" onClick={() => save(barcode, "تنظیمات بارکد ذخیره شد")}>ذخیره تنظیمات بارکد</button></div>
    </section>
  </div>;
}
