"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2 } from "lucide-react";
import { api, toast } from "./client";
import { Barcode } from "./LabelView";

type Initial = { invoiceWidth: number; invoiceFontSize: number; invoiceHeaderTemplate: string; invoiceBorderStyle: string; barcodeLabelWidth: number; barcodeLabelHeight: number; barcodeFontSize: number; barcodeShowProductName: number; barcodeShowSku: number };
export function PrintDesignManager({ initial }: { initial: Initial }) {
  const router = useRouter();
  const [invoice, setInvoice] = useState({ invoiceWidth: initial.invoiceWidth, invoiceFontSize: initial.invoiceFontSize, invoiceHeaderTemplate: initial.invoiceHeaderTemplate, invoiceBorderStyle: initial.invoiceBorderStyle });
  const [barcode, setBarcode] = useState({ barcodeLabelWidth: initial.barcodeLabelWidth, barcodeLabelHeight: initial.barcodeLabelHeight, barcodeFontSize: initial.barcodeFontSize, barcodeShowProductName: initial.barcodeShowProductName, barcodeShowSku: initial.barcodeShowSku });
  const [busy, setBusy] = useState(false);
  async function save(data: object, message: string) { setBusy(true); try { await api("/api/admin/settings", "POST", data); toast(message); router.refresh(); } catch (e) { toast((e as Error).message, false); } finally { setBusy(false); } }
  return <div className="mt-8 space-y-6">
    <section className="grid gap-6 lg:grid-cols-2">
      <div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-3 text-lg font-bold">طراحی فاکتور فروش</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">عرض چاپ (mm)<input type="number" className="input mt-1" value={invoice.invoiceWidth} onChange={(e) => setInvoice({ ...invoice, invoiceWidth: Number(e.target.value) })} /></label><label className="text-sm">اندازه فونت (px)<input type="number" className="input mt-1" value={invoice.invoiceFontSize} onChange={(e) => setInvoice({ ...invoice, invoiceFontSize: Number(e.target.value) })} /></label><label className="text-sm sm:col-span-2">قالب سربرگ<textarea className="input mt-1 min-h-24 font-mono text-xs" value={invoice.invoiceHeaderTemplate} onChange={(e) => setInvoice({ ...invoice, invoiceHeaderTemplate: e.target.value })} /></label><label className="text-sm">کادر فاکتور<select className="input mt-1" value={invoice.invoiceBorderStyle} onChange={(e) => setInvoice({ ...invoice, invoiceBorderStyle: e.target.value })}><option value="solid">خط ممتد</option><option value="dashed">خط‌چین</option><option value="none">بدون کادر</option></select></label></div><p className="mt-2 text-xs text-slate-500">متغیرها: {`{siteName}`}، {`{invoiceNumber}`}، {`{date}`}</p><div className="mt-3 rounded-lg bg-slate-50 p-3 text-center text-sm" style={{ fontSize: invoice.invoiceFontSize }}><b>{invoice.invoiceHeaderTemplate.replaceAll("{siteName}", "فروشگاه ارگانیک").replaceAll("{invoiceNumber}", "INV-1405-123").replaceAll("{date}", "۱۴۰۵/۰۷/۱۲")}</b><div className="mt-2 border-t border-slate-300 pt-2">پیش‌نمایش سربرگ · جدول کالاها و مبالغ در فاکتور حفظ می‌شود</div></div><button disabled={busy} className="btn-primary mt-4" onClick={() => save(invoice, "طراحی فاکتور ذخیره شد")}>ذخیره طراحی فاکتور</button></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-3 text-lg font-bold">تنظیمات برچسب بارکد تنوع‌ها</h2><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">عرض (mm)<input type="number" className="input mt-1" value={barcode.barcodeLabelWidth} onChange={(e) => setBarcode({ ...barcode, barcodeLabelWidth: Number(e.target.value) })} /></label><label className="text-sm">ارتفاع (mm)<input type="number" className="input mt-1" value={barcode.barcodeLabelHeight} onChange={(e) => setBarcode({ ...barcode, barcodeLabelHeight: Number(e.target.value) })} /></label><label className="text-sm">فونت (px)<input type="number" className="input mt-1" value={barcode.barcodeFontSize} onChange={(e) => setBarcode({ ...barcode, barcodeFontSize: Number(e.target.value) })} /></label></div><div className="my-4 flex gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={!!barcode.barcodeShowProductName} onChange={(e) => setBarcode({ ...barcode, barcodeShowProductName: e.target.checked ? 1 : 0 })} />نام محصول</label><label className="flex items-center gap-2"><input type="checkbox" checked={!!barcode.barcodeShowSku} onChange={(e) => setBarcode({ ...barcode, barcodeShowSku: e.target.checked ? 1 : 0 })} />کد SKU</label></div><div className="mx-auto grid place-items-center rounded border border-dashed border-slate-300 bg-slate-50 p-3 text-center" style={{ width: `${Math.min(barcode.barcodeLabelWidth * 2, 300)}px`, minHeight: `${Math.max(barcode.barcodeLabelHeight * 2, 70)}px`, fontSize: barcode.barcodeFontSize }}><b>نمونه محصول ارگانیک</b><Barcode value="ORG-12001" height={34} /></div><button disabled={busy} className="btn-primary mt-4" onClick={() => save(barcode, "تنظیمات بارکد ذخیره شد")}>ذخیره تنظیمات بارکد</button></div>
    </section>
  </div>;
}
