"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Check, Minus, Plus, Search, ShoppingBag, Sprout, Trash2, Package, X } from "lucide-react";
import { api, toast } from "./client";
import { faNum, toman } from "@/lib/util";
import { InvoiceModal } from "./InvoiceModal";
import { JalaliDatePicker } from "@/components/JalaliDatePicker";
import { Img } from "./ui";
import { Modal } from "./Modal";

type Product = { offerId:number; productId:number; name:string; brand:string; sku:string; price:number; cost:number; stock:number; weight?:number; variantTitle?:string|null; categoryId?:number|null; categoryName?:string; imageId?:number|null };
type Category = { id:number; name:string };
type ProductGroup = { productId:number; name:string; brand:string; categoryId:number|null; categoryName:string; imageId:number|null; variants:Product[] };
type SaleResult = { ok:boolean; id:number; number:string; subtotal:number; discount:number; total:number; commission:number; rewardCode?:string|null };
type Terminal={id:number;name:string;bankName:string|null;terminalCode:string|null};
type ShippingOption={id:number;name:string;cost:number;supportsFreightCollect:boolean};
const phoneDigits=(value:string)=>value.replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d)));
export default function SellerPosClient({products:initial,categories=[],endpoint="/api/seller/pos",central=false}:{products:Product[];categories?:Category[];endpoint?:string;central?:boolean}) {
  const idem=useRef(crypto.randomUUID());
  const [invoice,setInvoice]=useState<string|null>(null),[sendNextReward,setSendNextReward]=useState(false),[nextRewardPercent,setNextRewardPercent]=useState(10);
  const [products,setProducts]=useState(initial),[terminals,setTerminals]=useState<Terminal[]>([]),[terminalId,setTerminalId]=useState(""),[query,setQuery]=useState(""),[categoryFilter,setCategoryFilter]=useState("all"),[brandFilter,setBrandFilter]=useState("all"),[stockFilter,setStockFilter]=useState("available"),[selectedProduct,setSelectedProduct]=useState<ProductGroup|null>(null),[selectedOfferId,setSelectedOfferId]=useState<number|null>(null),[modalQty,setModalQty]=useState(1),[cart,setCart]=useState<Record<number,number>>({}),[name,setName]=useState(""),[phone,setPhone]=useState(""),[birthdate,setBirthdate]=useState(""),[shipping,setShipping]=useState(false),[shippingCity,setShippingCity]=useState(""),[shippingAddress,setShippingAddress]=useState(""),[shippingPostalCode,setShippingPostalCode]=useState(""),[shippingOptions,setShippingOptions]=useState<ShippingOption[]>([]),[shippingCarrierId,setShippingCarrierId]=useState(""),[shippingFreightCollect,setShippingFreightCollect]=useState(false),[shippingLoading,setShippingLoading]=useState(false),[rewardCode,setRewardCode]=useState(""),[rewardApplied,setRewardApplied]=useState(false),[smsConsent,setSmsConsent]=useState(false),[discountPercent,setDiscountPercent]=useState(0),[cash,setCash]=useState(0),[busy,setBusy]=useState(false),[done,setDone]=useState<SaleResult|null>(null);
  const lines=Object.entries(cart).map(([id,qty])=>({p:products.find(x=>x.offerId===Number(id))!,qty})).filter(x=>x.p);
  const subtotal=lines.reduce((sum,x)=>sum+x.p.price*x.qty,0),maxDiscountPercent=lines.length?Math.min(90,...lines.map(({p})=>Math.max(0,Math.floor(((p.price-p.cost)*100)/p.price)))):90,discount=Math.floor(subtotal*discountPercent/100),selectedCarrier=shippingOptions.find(option=>String(option.id)===shippingCarrierId),shippingCost=shippingFreightCollect?0:selectedCarrier?.cost??0,total=subtotal-discount+shippingCost,cashPaid=Math.min(cash,total),card=total-cashPaid,discountInvalid=discountPercent>maxDiscountPercent;
  useEffect(()=>{let active=true;api<Terminal[]>(central?"/api/admin/pos/terminals":"/api/seller/pos/terminals","GET").then(ts=>{if(active){setTerminals(ts);setTerminalId(ts[0]?String(ts[0].id):"")}}).catch(e=>{if(active)toast((e as Error).message,false)});return()=>{active=false}},[central]);
  const shippingWeight=lines.reduce((sum,line)=>sum+(line.p.weight??0)*line.qty,0);
  useEffect(()=>{if(!central||!shipping){setShippingLoading(false);setShippingOptions([]);setShippingCarrierId("");setShippingFreightCollect(false);return}let active=true;setShippingLoading(true);const timer=window.setTimeout(()=>api<ShippingOption[]>("/api/admin/pos/shipping-options","POST",{city:shippingCity,weight:shippingWeight,itemsTotal:subtotal-discount}).then(options=>{if(active){setShippingOptions(options);setShippingCarrierId(current=>options.some(option=>String(option.id)===current)?current:"")}}).catch(error=>{if(active){setShippingOptions([]);setShippingCarrierId("");toast((error as Error).message,false)}}).finally(()=>{if(active)setShippingLoading(false)}),250);return()=>{active=false;window.clearTimeout(timer)}},[central,shipping,shippingCity,shippingWeight,subtotal,discount]);
  const groupedProducts=useMemo(()=>{const map=new Map<number,ProductGroup>();for(const p of products){let group=map.get(p.productId);if(!group){group={productId:p.productId,name:p.name,brand:p.brand,categoryId:p.categoryId??null,categoryName:p.categoryName??"بدون دسته‌بندی",imageId:p.imageId??null,variants:[]};map.set(p.productId,group)}group.variants.push(p)}return [...map.values()]},[products]);
  const categoryOptions=categories.length?categories:[...new Map(groupedProducts.filter(p=>p.categoryId).map(p=>[p.categoryId!,{id:p.categoryId!,name:p.categoryName}])).values()];
  const brandOptions=[...new Set(groupedProducts.map(p=>p.brand).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"fa"));
  const filtered=useMemo(()=>groupedProducts.filter(p=>{
    const text=`${p.name} ${p.brand} ${p.categoryName} ${p.variants.map(v=>`${v.sku} ${v.variantTitle??""}`).join(" ")}`.toLowerCase();
    if(query.trim()&&!text.includes(query.trim().toLowerCase()))return false;
    if(categoryFilter!=="all"&&String(p.categoryId??"")!==categoryFilter)return false;
    if(brandFilter!=="all"&&p.brand!==brandFilter)return false;
    const stocks=p.variants.map(v=>v.stock);
    if(stockFilter==="available"&&!stocks.some(s=>s>0))return false;
    if(stockFilter==="low"&&!stocks.some(s=>s>0&&s<=5))return false;
    if(stockFilter==="out"&&!stocks.every(s=>s<=0))return false;
    return true;
  }),[groupedProducts,query,categoryFilter,brandFilter,stockFilter]);
  const openProduct=(product:ProductGroup)=>{const first=product.variants.find(v=>v.stock>0)??product.variants[0];setSelectedProduct(product);setSelectedOfferId(first?.offerId??null);setModalQty(1)};
  const selectedVariant=selectedProduct?.variants.find(v=>v.offerId===selectedOfferId)??null;
  const selectedRemaining=selectedVariant?Math.max(0,selectedVariant.stock-(cart[selectedVariant.offerId]??0)):0;
  const addSelected=()=>{if(!selectedVariant||selectedRemaining<1)return;qty(selectedVariant.offerId,Math.min(selectedVariant.stock,(cart[selectedVariant.offerId]??0)+modalQty));setSelectedProduct(null);toast("تنوع انتخاب‌شده به فاکتور اضافه شد")};
  const add=(p:Product)=>setCart(old=>({...old,[p.offerId]:Math.min(p.stock,(old[p.offerId]??0)+1)}));
  const qty=(id:number,value:number)=>setCart(old=>{const next={...old};if(value<=0)delete next[id];else{const p=products.find(x=>x.offerId===id);next[id]=Math.min(value,p?.stock??value)}return next});
  const applyReward=async()=>{try{const r=await api<{discountPercent:number;minSubtotal:number}>(`/api/seller/loyalty/rewards/${encodeURIComponent(rewardCode)}`,"GET");if(subtotal<r.minSubtotal)return toast(`حداقل مبلغ این کد ${toman(r.minSubtotal)} است`,false);if(r.discountPercent>maxDiscountPercent)return toast(`برای اقلام این فاکتور حداکثر ${faNum(maxDiscountPercent)}٪ تخفیف مجاز است`,false);setDiscountPercent(r.discountPercent);setRewardApplied(true);toast(`${faNum(r.discountPercent)}٪ تخفیف باشگاه اعمال شد`)}catch(e){toast((e as Error).message,false)}};
  const submit=async()=>{
    if(!lines.length)return toast("ابتدا یک محصول به فاکتور اضافه کنید",false);
    if(!/^09\d{9}$/.test(phoneDigits(phone).replace(/\D/g,"")))return toast("شمارهٔ همراه مشتری را درست وارد کنید",false);
    if(central&&shipping&&(!shippingCity.trim()||shippingAddress.trim().length<8||!/^\d{10}$/.test(phoneDigits(shippingPostalCode).replace(/\D/g,""))))return toast("برای ارسال، شهر و نشانی کامل به‌همراه کد پستی ۱۰ رقمی را وارد کنید",false);
    if(central&&shipping&&(shippingLoading||!shippingCarrierId))return toast("شرکت پستی را انتخاب کنید و منتظر محاسبه هزینه ارسال بمانید",false);
    if(rewardCode&&!rewardApplied)return toast("ابتدا کد باشگاه را بررسی و اعمال کنید",false);
    if(discountInvalid)return toast(`حداکثر تخفیف مجاز این فاکتور ${faNum(maxDiscountPercent)}٪ است`,false);
    const paymentMethod=cashPaid===0?"card":cashPaid===total?"cash":"mixed";
    if(card>0&&!terminalId)return toast("ابتدا کارتخوان فروشگاه را در تنظیمات تعریف و انتخاب کنید",false);
    setBusy(true);
    try{const result=await api<SaleResult>(endpoint,"POST",{idempotencyKey:idem.current,sendNextReward,nextRewardPercent,customerName:name,phone:phoneDigits(phone).replace(/\D/g,""),birthdate:birthdate||null,shipping:central&&shipping,shippingCity,shippingAddress,shippingPostalCode:phoneDigits(shippingPostalCode).replace(/\D/g,""),shippingCarrierId:shipping?Number(shippingCarrierId):null,shippingFreightCollect:shipping&&shippingFreightCollect,smsConsent,discountPercent,rewardCode:rewardApplied?rewardCode.toUpperCase():null,settlement:{cash:cashPaid,card},paymentMethod,terminalId:card>0?Number(terminalId):null,items:lines.map(({p,qty})=>({offerId:p.offerId,qty}))});if(result.id)setInvoice(`/print/pos/${central?"central":"seller"}/${result.id}`);idem.current=crypto.randomUUID();setDone(result);setRewardCode("");setRewardApplied(false);setProducts(old=>old.map(p=>({...p,stock:Math.max(0,p.stock-(cart[p.offerId]??0))})));setCart({});setCash(0);setDiscountPercent(0);toast(central?"فروش ثبت شد و موجودی انبار مرکزی کسر شد":"فروش ثبت شد؛ کمیسیون فروش حضوری صفر است")}
    catch(e){toast((e as Error).message,false)}finally{setBusy(false)}
  };
  if(done)return <>{invoice&&<InvoiceModal src={invoice} onClose={()=>setInvoice(null)}/>}<section className="mx-auto max-w-xl rounded-3xl border border-emerald-200 bg-white p-8 text-center shadow-sm"><span className="mx-auto grid size-14 place-items-center rounded-full bg-emerald-50 text-emerald-700"><Check/></span><h2 className="mt-4 text-xl font-black">فروش حضوری ثبت شد</h2><p className="mt-2 text-sm text-slate-600">فاکتور <b dir="ltr">{done.number}</b> · {toman(done.total)}</p><p className="mt-2 text-xs font-bold text-emerald-700">{central?"موجودی انبار مرکزی کسر شد":"موجودی انبار شما کسر شد · کمیسیون: ۰ تومان"}</p>{done.rewardCode&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-bold text-amber-800">کد پاداش باشگاه برای خرید حضوری بعدی</p><b dir="ltr" className="mt-2 block text-xl tracking-widest">{done.rewardCode}</b><p className="mt-2 text-[11px] leading-5 text-amber-800">در صورت فعال بودن پنل پیامک و رضایت مشتری، این کد برای او پیامک شده است.</p></div>}<button className="btn-primary mt-6" onClick={()=>{setDone(null);setName("");setPhone("");setBirthdate("");setSmsConsent(false);setShipping(false);setShippingFreightCollect(false);setShippingCity("");setShippingAddress("");setShippingPostalCode("")}}>ثبت فاکتور جدید</button><button className="btn-ghost mt-3" onClick={()=>setInvoice(`/print/pos/${central?"central":"seller"}/${done.id}`)}>نمایش و چاپ مجدد</button>{central&&shipping&&<a className="btn-ghost mt-3" href={`/print/pos-label/${done.id}`} target="_blank">چاپ لیبل پستی گیرنده</a>}</section></>;
  return <div className="grid items-start gap-5 xl:grid-cols-[1.2fr_.8fr]">
    <section className="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 md:p-5 dark:border-slate-700 dark:bg-slate-900">
      <div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-base font-black">انتخاب محصولات</h2><p className="mt-1 text-xs text-slate-500">برای انتخاب تنوع و تعداد، روی محصول بزنید.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300">{faNum(filtered.length)} محصول</span></div>
      <div className="grid gap-2 rounded-2xl bg-slate-50 p-3 sm:grid-cols-2 xl:grid-cols-4 dark:bg-slate-800/70">
        <label className="relative sm:col-span-2 xl:col-span-1"><Search className="absolute right-3 top-3 size-4 text-slate-400"/><input aria-label="جست‌وجو در محصولات" className="input pr-10" value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام، برند یا کد کالا…"/></label>
        <select aria-label="فیلتر دسته‌بندی" className="input" value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="all">همهٔ دسته‌بندی‌ها</option>{categoryOptions.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select>
        <select aria-label="فیلتر برند" className="input" value={brandFilter} onChange={e=>setBrandFilter(e.target.value)}><option value="all">همهٔ برندها</option>{brandOptions.map(brand=><option key={brand} value={brand}>{brand}</option>)}</select>
        <select aria-label="فیلتر موجودی" className="input" value={stockFilter} onChange={e=>setStockFilter(e.target.value)}><option value="available">فقط محصولات موجود</option><option value="low">موجودی کم (۱ تا ۵)</option><option value="out">ناموجود</option><option value="all">همهٔ محصولات</option></select>
      </div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">{filtered.map(product=>{const available=product.variants.filter(v=>v.stock>0).length;const minPrice=Math.min(...product.variants.filter(v=>v.stock>0).map(v=>v.price),...product.variants.map(v=>v.price));return <button type="button" key={product.productId} onClick={()=>openProduct(product)} className="group flex min-w-0 items-center gap-3 rounded-2xl border border-slate-200 bg-white p-3 text-right transition hover:border-emerald-300 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-emerald-500 dark:border-slate-700 dark:bg-slate-900 dark:hover:bg-slate-800">
        <Img id={product.imageId} alt={product.name} width={96} height={96} sizes="96px" className="size-20 shrink-0 rounded-xl bg-slate-100 object-cover dark:bg-slate-800"/>
        <span className="min-w-0 flex-1"><span className="line-clamp-2 block min-h-10 text-sm font-extrabold text-slate-800 group-hover:text-emerald-700 dark:text-slate-100">{product.name}</span><span className="mt-1 block truncate text-xs text-slate-500">{product.brand} · {product.categoryName}</span><span className="mt-2 flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-0.5 text-[11px] font-bold ${available?"bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300":"bg-slate-100 text-slate-500 dark:bg-slate-800"}`}>{available?`${faNum(available)} تنوع موجود`:"ناموجود"}</span><span className="text-xs font-black text-slate-800 dark:text-slate-100">{toman(minPrice)}</span></span></span><Package className="size-4 shrink-0 text-slate-300 group-hover:text-emerald-600"/>
      </button>})}</div>
      {!filtered.length&&<p className="p-8 text-center text-sm text-slate-500">محصولی با فیلترهای انتخاب‌شده پیدا نشد.</p>}
    </section>
    {selectedProduct&&<Modal title="انتخاب تنوع و تعداد" onClose={()=>setSelectedProduct(null)}><div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-900"><Img id={selectedProduct.imageId} alt={selectedProduct.name} width={96} height={96} sizes="96px" className="size-20 shrink-0 rounded-xl object-cover"/><div className="min-w-0"><h3 className="font-black text-slate-900 dark:text-slate-100">{selectedProduct.name}</h3><p className="mt-1 text-xs text-slate-500">{selectedProduct.brand} · {selectedProduct.categoryName}</p></div></div>
      <div className="mt-4 space-y-2">{selectedProduct.variants.map(variant=>{const remaining=Math.max(0,variant.stock-(cart[variant.offerId]??0));const isSelected=variant.offerId===selectedOfferId;return <button type="button" key={variant.offerId} disabled={remaining<1} onClick={()=>{setSelectedOfferId(variant.offerId);setModalQty(1)}} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-right transition disabled:cursor-not-allowed disabled:opacity-50 ${isSelected?"border-emerald-400 bg-emerald-50 ring-1 ring-emerald-300 dark:bg-emerald-950/30":"border-slate-200 bg-white hover:border-slate-300 dark:border-slate-700 dark:bg-slate-900 dark:hover:bg-slate-800"}`}><span className={`grid size-4 shrink-0 place-items-center rounded-full border ${isSelected?"border-emerald-600 bg-emerald-600":"border-slate-300"}`}>{isSelected&&<span className="size-1.5 rounded-full bg-white"/>}</span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">{variant.variantTitle||"تنوع اصلی"}</span><span className="mt-1 block text-[11px] text-slate-500" dir="ltr">{variant.sku}</span></span><span className="text-left"><b className="block text-sm">{toman(variant.price)}</b><small className={remaining?"text-emerald-700 dark:text-emerald-300":"text-rose-600"}>{remaining?`${faNum(remaining)} ${central?"عدد":"موجود"}`:"ناموجود"}</small></span></button>})}</div>
      {selectedVariant&&selectedRemaining>0&&<div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-100 p-3 dark:bg-slate-800"><span className="text-sm font-bold">تعداد</span><div className="flex items-center gap-3"><button type="button" aria-label="کم کردن تعداد" className="grid size-9 place-items-center rounded-xl border border-slate-300 bg-white disabled:opacity-40 dark:border-slate-600 dark:bg-slate-900" disabled={modalQty<=1} onClick={()=>setModalQty(n=>Math.max(1,n-1))}><Minus className="size-4"/></button><input aria-label="تعداد انتخاب‌شده" type="number" min={1} max={selectedRemaining} value={modalQty} onChange={e=>setModalQty(Math.min(selectedRemaining,Math.max(1,Number(e.target.value)||1)))} className="input w-20 text-center"/><button type="button" aria-label="افزودن تعداد" className="grid size-9 place-items-center rounded-xl border border-slate-300 bg-white disabled:opacity-40 dark:border-slate-600 dark:bg-slate-900" disabled={modalQty>=selectedRemaining} onClick={()=>setModalQty(n=>Math.min(selectedRemaining,n+1))}><Plus className="size-4"/></button></div></div>}
      <div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" className="btn-ghost" onClick={()=>setSelectedProduct(null)}><X className="size-4"/>انصراف</button><button type="button" disabled={!selectedVariant||selectedRemaining<1} className="btn-primary" onClick={addSelected}><Plus className="size-4"/>افزودن {faNum(modalQty)} عدد به فاکتور</button></div>
    </Modal>}
    <section className="rounded-2xl border border-slate-200 bg-white p-4 md:p-5 dark:border-slate-700 dark:bg-slate-900"><h2 className="flex items-center gap-2 text-base font-black"><ShoppingBag className="size-5 text-emerald-700"/>فاکتور مشتری</h2><div className="mt-4 space-y-2">{lines.map(({p,qty:q})=><div key={p.offerId} className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><Sprout className="size-4 shrink-0 text-emerald-700"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{p.name}</p><p className="mt-1 truncate text-[11px] text-slate-500">{p.variantTitle||p.sku} · {toman(p.price*q)}</p></div><div className="flex items-center gap-2"><button aria-label="کم کردن" onClick={()=>qty(p.offerId,q-1)} className="grid size-7 place-items-center rounded-lg border bg-white dark:border-slate-600 dark:bg-slate-900"><Minus className="size-3"/></button><span className="min-w-5 text-center text-xs font-bold">{faNum(q)}</span><button aria-label="افزودن" onClick={()=>add(p)} disabled={q>=p.stock} className="grid size-7 place-items-center rounded-lg border bg-white disabled:opacity-40 dark:border-slate-600 dark:bg-slate-900"><Plus className="size-3"/></button><button aria-label="حذف" onClick={()=>qty(p.offerId,0)} className="text-rose-500"><Trash2 className="size-4"/></button></div></div>)}</div>
      <div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs font-bold">نام مشتری<input className="input mt-1" value={name} onChange={e=>setName(e.target.value)} placeholder="اختیاری"/></label><label className="text-xs font-bold">شماره همراه مشتری<input className="input mt-1" dir="ltr" inputMode="numeric" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="0912…"/></label><label className="col-span-2 text-xs font-bold">تاریخ تولد (برای باشگاه مشتریان)<div className="mt-1"><JalaliDatePicker value={birthdate} onChange={setBirthdate} allowEmpty placeholder="انتخاب تاریخ تولد"/></div></label></div>
      {central&&<div className="mt-4 rounded-xl border border-slate-200 p-3"><label className="flex cursor-pointer items-center gap-2 text-sm font-bold"><input type="checkbox" checked={shipping} onChange={e=>{setShipping(e.target.checked);if(!e.target.checked){setShippingOptions([]);setShippingCarrierId("");setShippingFreightCollect(false)}}} className="accent-emerald-700"/>این فاکتور نیاز به ارسال دارد</label>{shipping&&<div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">شهر گیرنده<input required className="input mt-1" value={shippingCity} onChange={e=>setShippingCity(e.target.value)} placeholder="مثلاً تهران"/></label><label className="text-xs font-bold">کد پستی ۱۰ رقمی<input required className="input mt-1" dir="ltr" inputMode="numeric" maxLength={10} value={shippingPostalCode} onChange={e=>setShippingPostalCode(e.target.value)} placeholder="۱۰ رقم"/></label><label className="text-xs font-bold sm:col-span-2">نشانی کامل گیرنده<textarea required minLength={8} className="input mt-1 min-h-20" value={shippingAddress} onChange={e=>setShippingAddress(e.target.value)} placeholder="خیابان، کوچه، پلاک و واحد"/></label><label className="text-xs font-bold sm:col-span-2">شرکت پستی<select className="input mt-1" required value={shippingCarrierId} onChange={e=>{setShippingCarrierId(e.target.value);setShippingFreightCollect(!!shippingOptions.find(option=>String(option.id)===e.target.value)?.supportsFreightCollect)}} disabled={shippingLoading}><option value="">{shippingLoading?"در حال محاسبه تعرفه‌ها…":"انتخاب شرکت پستی"}</option>{shippingOptions.map(option=><option key={option.id} value={option.id}>{option.name}{option.supportsFreightCollect?" · پس‌کرایه":shippingCity.trim()?` · ${toman(option.cost)}`:""}</option>)}</select>{shipping&&!shippingLoading&&shippingCity.trim()&&!shippingOptions.length&&<span className="mt-1 block font-normal text-rose-600">برای این آدرس شرکت پستی فعالی پیدا نشد.</span>}</label></div>}</div>}
      {!central&&<div className="mt-3 flex items-center gap-2"><input aria-label="کد تخفیف باشگاه" className="input" value={rewardCode} disabled={rewardApplied} onChange={e=>setRewardCode(e.target.value.toUpperCase())} placeholder="کد تخفیف باشگاه برای مراجعهٔ بعدی"/><button type="button" className="btn-sm shrink-0" disabled={!rewardCode||rewardApplied} onClick={applyReward}>{rewardApplied?"اعمال شد":"بررسی کد"}</button>{rewardApplied&&<button type="button" className="text-xs text-rose-600" onClick={()=>{setRewardApplied(false);setRewardCode("");setDiscountPercent(0)}}>حذف</button>}</div>}
      <label className="mt-3 flex items-center gap-2 text-xs text-slate-600"><input type="checkbox" checked={smsConsent} onChange={e=>setSmsConsent(e.target.checked)} className="accent-emerald-700"/>{central?"مشتری برای عضویت در باشگاه مرکزی و دریافت پیامک‌های مناسبتی رضایت داده است":"مشتری برای دریافت پیامک‌های باشگاه مشتریان رضایت داده است"}</label>
      <div className="mt-4 rounded-xl bg-emerald-50 p-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={sendNextReward} onChange={e=>setSendNextReward(e.target.checked)}/>صدور و پیامک کد تخفیف خرید بعدی</label>{sendNextReward&&<label className="mt-2 block text-xs">درصد هدیه (اعتبار ۳۰ روز)<input type="number" min="1" max="50" className="input mt-1" value={nextRewardPercent} onChange={e=>setNextRewardPercent(Number(e.target.value))}/><span className="mt-1 block">پیامک فقط با رضایت مشتری ارسال می‌شود.</span></label>}</div>
      <label className="mt-4 block text-xs font-bold">تخفیف فاکتور (%)<input type="number" min="0" max={maxDiscountPercent} className={`input mt-1 ${discountInvalid?"!border-rose-400":""}`} value={discountPercent} disabled={rewardApplied} onChange={e=>setDiscountPercent(Math.min(maxDiscountPercent,Math.max(0,Number(e.target.value)||0)))}/><span className={`mt-1 block font-normal ${discountInvalid?"text-rose-600":"text-slate-500"}`}>حداکثر مجاز برای اقلام فاکتور: {faNum(maxDiscountPercent)}٪؛ قیمت پس از تخفیف از قیمت خرید کمتر نمی‌شود.</span></label>
      {card>0&&<label className="mt-3 block text-xs font-bold">دستگاه پوز<select className="input mt-1" value={terminalId} onChange={e=>setTerminalId(e.target.value)}><option value="">انتخاب کارتخوان</option>{terminals.map(t=><option key={t.id} value={t.id}>{t.name}{t.bankName?` · ${t.bankName}`:""}</option>)}</select>{!terminals.length&&<span className="mt-1 block font-normal text-amber-700">ابتدا کارتخوان را از بخش تنظیمات تعریف کنید.</span>}</label>}
      <label className="mt-3 block text-xs font-bold">دریافت نقدی (تومان)<input type="number" min="0" max={total} className="input mt-1" value={cashPaid} onChange={e=>setCash(Math.min(total,Math.max(0,Number(e.target.value)||0)))}/></label>
      <div className="mt-3 space-y-2 border-t pt-3 text-sm"><div className="flex justify-between text-slate-500"><span>جمع کالاها</span><span>{toman(subtotal)}</span></div><div className="flex justify-between text-slate-500"><span>تخفیف</span><span>− {toman(discount)}</span></div>{central&&shipping&&<div className="flex justify-between text-slate-600"><span>ارسال {shippingOptions.find(option=>String(option.id)===shippingCarrierId)?.name??""}</span><span>{shippingLoading?"در حال محاسبه…":shippingFreightCollect?"پس‌کرایه؛ پرداخت به پست":toman(shippingCost)}</span></div>}<div className="flex justify-between font-black"><span>مبلغ نهایی فاکتور</span><span>{toman(total)}</span></div><div className="flex justify-between text-xs text-slate-500"><span>کارتخوان</span><span>{toman(card)}</span></div>{!central&&<div className="flex justify-between text-xs font-bold text-emerald-700"><span>کمیسیون مارکت‌پلیس</span><span>۰ تومان</span></div>}</div>
      <button disabled={busy||!lines.length||discountInvalid||(card>0&&!terminalId)||(central&&shipping&&(shippingLoading||!shippingCarrierId))} onClick={submit} className="btn-primary mt-4 w-full disabled:opacity-50">{busy?"در حال ثبت…":"ثبت و تسویهٔ فروش حضوری"}</button>
    </section>
  </div>;
}
