import Link from "next/link";
import type { CSSProperties } from "react";
import type { SitePageBlock } from "@/db/schema";
import { SiteContentSlider } from "./SiteContentSlider";
import { PublicFormEmbed } from "./PublicFormEmbed";
import { PageBlockFrame } from "./PageBlockFrame";

export function SiteBlockContent({ block, primary = false }: { block: SitePageBlock; primary?: boolean }) {
  const Heading = primary ? "h1" : "h2";
  const heading = <>{block.title && <Heading className="mb-3 text-2xl font-black">{block.title}</Heading>}{block.body && <p className="whitespace-pre-line text-sm leading-8 opacity-80">{block.body}</p>}</>;
  const button = block.href && block.buttonLabel ? <Link className="btn-primary mt-5" href={block.href}>{block.buttonLabel}</Link> : null;
  if (block.type === "form") return <section>{heading}{block.formSlug ? <div className="mt-5"><PublicFormEmbed slug={block.formSlug}/></div> : <p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">فرم عمومی موردنظر انتخاب نشده است.</p>}</section>;
  if (block.type === "shortcode") return <section>{heading}<div className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">شورت‌کدها در صفحهٔ منتشرشده نمایش داده می‌شوند.</div></section>;
  if (block.type === "slider") return <SiteContentSlider title={block.title || ""} body={block.body} items={block.items ?? []} autoplay={block.options?.autoplay} interval={block.options?.interval} />;
  if (block.type === "columns") { const desktopColumns = block.style?.columns ?? Math.max(1, block.columns?.length ?? 1); return <section className="site-builder-columns-wrap">{heading && <div className="mb-5 max-w-3xl">{heading}</div>}<div className="site-builder-columns" style={{ "--builder-mobile-cols": block.style?.mobileColumns ?? 1, "--builder-tablet-cols": block.style?.tabletColumns ?? 2, "--builder-desktop-cols": desktopColumns, gap: block.style?.gap === undefined ? undefined : `${block.style.gap}px` } as CSSProperties}>{(block.columns ?? []).map((column, columnIndex) => <div key={column.id} data-builder-col-span={Math.min(column.desktopSpan ?? 1, desktopColumns)} className="site-builder-column min-w-0" style={{ order: column.mobileOrder ?? columnIndex }}>{column.blocks.filter(child => child.enabled !== false).map((child, childIndex) => <PageBlockFrame key={child.id || childIndex} block={child}><SiteBlockContent block={child}/></PageBlockFrame>)}</div>)}</div>{button}</section>; }
  if (block.type === "hero") return <section className="group relative isolate min-h-72 overflow-hidden rounded-[2rem] border border-amber-200/70 bg-gradient-to-br from-emerald-950 via-emerald-900 to-amber-900 px-6 py-10 text-white shadow-[0_24px_70px_-42px_rgba(6,78,59,.75)] sm:min-h-80 sm:px-12 sm:py-14">{block.mediaId && <img src={`/api/media/${block.mediaId}`} alt={block.caption || ""} className="absolute inset-0 -z-20 size-full object-cover opacity-25 transition-transform duration-700 group-hover:scale-[1.02]" />}<div className="absolute -right-16 -top-24 -z-10 size-72 rounded-full border border-white/10 bg-white/[0.04] sm:size-96"/><div className="absolute -bottom-36 left-8 -z-10 size-72 rounded-full bg-amber-300/10 blur-3xl"/><div className="relative max-w-3xl">{block.options?.badge && <span className="mb-5 inline-flex items-center gap-2 rounded-full border border-amber-100/20 bg-white/10 px-4 py-2 text-xs font-bold text-amber-100 backdrop-blur"><span className="size-1.5 rounded-full bg-amber-300"/>{block.options.badge}</span>}{block.title && <Heading className="mb-4 text-3xl font-black leading-[1.55] tracking-tight sm:text-5xl sm:leading-[1.45]">{block.title}</Heading>}{block.body && <p className="max-w-2xl whitespace-pre-line text-sm leading-8 text-white/80 sm:text-base sm:leading-9">{block.body}</p>}{button}{block.options?.secondaryHref && block.options.secondaryLabel && <Link href={block.options.secondaryHref} className="btn-ghost m-3 border-white/25 !bg-white/10 !text-white hover:!bg-white/20">{block.options.secondaryLabel}</Link>}</div></section>;
  if (block.type === "image") return <section>{heading}<figure className="mt-4 overflow-hidden rounded-3xl bg-white">{block.mediaId ? <img src={`/api/media/${block.mediaId}`} alt={block.caption || block.title || ""} className="max-h-[720px] w-full object-cover" /> : <div className="grid min-h-48 place-items-center bg-amber-50 text-slate-500">تصویر انتخاب کنید</div>}{block.caption && <figcaption className="p-3 text-center text-xs">{block.caption}</figcaption>}</figure>{button}</section>;
  if (block.type === "faq") return <section>{heading}<div className="mt-5 space-y-3">{(block.items ?? []).map((item, i) => <details key={item.id || i} className="rounded-2xl border bg-white p-5"><summary className="cursor-pointer font-bold">{item.title}</summary><p className="mt-3 whitespace-pre-line text-sm leading-8">{item.body}</p></details>)}</div></section>;
  if (["grid", "features"].includes(block.type)) return <section className="py-2">{heading && <div className="max-w-3xl">{heading}</div>}<div className="builder-grid mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{(block.items ?? []).map((item, i) => <article key={item.id || i} style={{ gridColumn: `span ${Math.min(item.colSpan || 1, block.style?.columns || 3)}` }} className="builder-cell relative min-w-0 overflow-hidden rounded-3xl border border-emerald-950/5 bg-white p-5 shadow-[0_12px_42px_-32px_rgba(15,23,42,.35)] transition duration-300 hover:-translate-y-1 hover:border-amber-300 hover:shadow-lg sm:p-6">{item.mediaId && <img src={`/api/media/${item.mediaId}`} alt={item.caption || item.title} className="mb-4 aspect-[16/10] w-full rounded-2xl object-cover" />}{block.type === "features" && <span className="mb-4 grid size-11 place-items-center rounded-2xl bg-amber-100 text-lg font-black text-amber-800">{String(i + 1).padStart(2, "0")}</span>}{item.title && <h3 className="text-lg font-black text-slate-900">{item.title}</h3>}{item.body && <p className="mt-3 whitespace-pre-line text-sm leading-8 text-slate-600">{item.body}</p>}{item.caption && <small className="mt-2 block text-slate-500">{item.caption}</small>}{item.href && item.buttonLabel && <Link href={item.href} className="btn-primary mt-4">{item.buttonLabel}</Link>}</article>)}</div>{button}</section>;
  return <section className={`rounded-3xl p-6 sm:p-9 ${block.type === "cta" ? "border border-amber-200 bg-gradient-to-l from-amber-50 via-white to-emerald-50 text-center shadow-sm" : "border border-slate-200 bg-white shadow-sm"}`}>{heading}{button}</section>;
}
