import Link from "next/link";
import type { SitePageBlock } from "@/db/schema";
import { SiteContentSlider } from "./SiteContentSlider";

export function SiteBlockContent({ block, primary = false }: { block: SitePageBlock; primary?: boolean }) {
  const Heading = primary ? "h1" : "h2";
  const heading = <>{block.title && <Heading className="mb-3 text-2xl font-black">{block.title}</Heading>}{block.body && <p className="whitespace-pre-line text-sm leading-8 opacity-80">{block.body}</p>}</>;
  const button = block.href && block.buttonLabel ? <Link className="btn-primary mt-5" href={block.href}>{block.buttonLabel}</Link> : null;
  if (block.type === "slider") return <SiteContentSlider title={block.title || ""} body={block.body} items={block.items ?? []} autoplay={block.options?.autoplay} interval={block.options?.interval} />;
  if (block.type === "hero") return <section className="relative overflow-hidden rounded-[2rem] bg-amber-950 p-8 text-white sm:p-14">{block.mediaId && <img src={`/api/media/${block.mediaId}`} alt={block.caption || ""} className="absolute inset-0 size-full object-cover opacity-40" />}<div className="relative max-w-3xl">{block.options?.badge && <span className="mb-4 inline-block rounded-full bg-white/20 px-4 py-2 text-sm">{block.options.badge}</span>}{heading}{button}{block.options?.secondaryHref && block.options.secondaryLabel && <Link href={block.options.secondaryHref} className="btn-ghost m-3 !text-inherit">{block.options.secondaryLabel}</Link>}</div></section>;
  if (block.type === "image") return <section>{heading}<figure className="mt-4 overflow-hidden rounded-3xl bg-white">{block.mediaId ? <img src={`/api/media/${block.mediaId}`} alt={block.caption || block.title || ""} className="max-h-[720px] w-full object-cover" /> : <div className="grid min-h-48 place-items-center bg-amber-50 text-slate-500">تصویر انتخاب کنید</div>}{block.caption && <figcaption className="p-3 text-center text-xs">{block.caption}</figcaption>}</figure>{button}</section>;
  if (block.type === "faq") return <section>{heading}<div className="mt-5 space-y-3">{(block.items ?? []).map((item, i) => <details key={item.id || i} className="rounded-2xl border bg-white p-5"><summary className="cursor-pointer font-bold">{item.title}</summary><p className="mt-3 whitespace-pre-line text-sm leading-8">{item.body}</p></details>)}</div></section>;
  if (["grid", "features"].includes(block.type)) return <section>{heading}<div className="builder-grid mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{(block.items ?? []).map((item, i) => <article key={item.id || i} style={{ gridColumn: `span ${Math.min(item.colSpan || 1, block.style?.columns || 3)}` }} className="builder-cell min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">{item.mediaId && <img src={`/api/media/${item.mediaId}`} alt={item.caption || item.title} className="mb-4 aspect-[16/10] w-full rounded-xl object-cover" />}{item.title && <h3 className="text-lg font-black">{item.title}</h3>}{item.body && <p className="mt-3 whitespace-pre-line text-sm leading-8 text-slate-600">{item.body}</p>}{item.caption && <small className="mt-2 block text-slate-500">{item.caption}</small>}{item.href && item.buttonLabel && <Link href={item.href} className="btn-primary mt-4">{item.buttonLabel}</Link>}</article>)}</div>{button}</section>;
  return <section className={`rounded-3xl p-6 sm:p-9 ${block.type === "cta" ? "bg-amber-100 text-center" : "border bg-white"}`}>{heading}{button}</section>;
}
