"use client";
import { useMemo, useState } from "react";
import { CalendarClock, Eye, Film, Heart, Link2, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { api, ImageUploader, toast } from "./client";
import { VideoUploader } from "./VideoUploader";
import { JalaliDatePicker } from "./JalaliDatePicker";
import { Modal } from "./Modal";
import { Badge, Img } from "./ui";

type ProductOption = { id: number; nameFa: string; brand: string; slug: string; mainImageId: number | null };
type Story = { id: number; title: string; caption: string | null; mediaId: number; mediaType: "image" | "video"; productId: number | null; productName: string | null; href: string | null; ctaLabel: string | null; status: string; startsAt: string | null; endsAt: string | null; sortOrder: number; viewCount: number; likeCount: number };
type Draft = { title: string; caption: string; mediaType: "image" | "video"; mediaId: number | null; productId: number | null; href: string; ctaLabel: string; status: "draft" | "published"; startsOn: string; startsTime: string; endsOn: string; endsTime: string; sortOrder: number };
const empty = (): Draft => ({ title: "", caption: "", mediaType: "image", mediaId: null, productId: null, href: "", ctaLabel: "مشاهده", status: "draft", startsOn: "", startsTime: "", endsOn: "", endsTime: "", sortOrder: 0 });
const dateInTehran = (value: string | null) => value ? new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tehran", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value)) : "";
const timeInTehran = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Tehran", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date(value)) : "";
const toIso = (date: string, time: string) => date ? new Date(`${date}T${time || "00:00"}:00+03:30`).toISOString() : null;

export function StoryManager({ initial, products }: { initial: Story[]; products: ProductOption[] }) {
  const [rows, setRows] = useState(initial), [draft, setDraft] = useState<Draft>(empty()), [editing, setEditing] = useState<number | null>(null);
  const [open, setOpen] = useState(false), [productModal, setProductModal] = useState(false), [productQuery, setProductQuery] = useState("");
  const [busy, setBusy] = useState(false), [query, setQuery] = useState("");
  const filtered = useMemo(() => rows.filter((row) => `${row.title} ${row.productName ?? ""}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [rows, query]);
  const filteredProducts = useMemo(() => products.filter((product) => `${product.nameFa} ${product.brand}`.toLocaleLowerCase().includes(productQuery.trim().toLocaleLowerCase())).slice(0, 80), [products, productQuery]);
  const selectedProduct = products.find((product) => product.id === draft.productId);
  const start = (story?: Story) => {
    setEditing(story?.id ?? null); setProductModal(false); setOpen(true);
    setDraft(story ? { title: story.title, caption: story.caption ?? "", mediaType: story.mediaType, mediaId: story.mediaId, productId: story.productId, href: story.href ?? "", ctaLabel: story.ctaLabel ?? "مشاهده", status: story.status === "published" ? "published" : "draft", startsOn: dateInTehran(story.startsAt), startsTime: timeInTehran(story.startsAt), endsOn: dateInTehran(story.endsAt), endsTime: timeInTehran(story.endsAt), sortOrder: story.sortOrder } : empty());
  };
  const save = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!draft.mediaId) { toast("رسانهٔ استوری را انتخاب یا بارگذاری کنید", false); return; }
    setBusy(true);
    try {
      const payload = { ...draft, startsAt: toIso(draft.startsOn, draft.startsTime), endsAt: toIso(draft.endsOn, draft.endsTime) };
      const row = await api<Story>(editing ? `/api/admin/stories/${editing}` : "/api/admin/stories", editing ? "PUT" : "POST", payload);
      const productName = products.find((product) => product.id === row.productId)?.nameFa ?? null;
      const next = { ...row, productName };
      setRows((old) => editing ? old.map((item) => item.id === row.id ? next : item) : [next, ...old]);
      setEditing(null); setOpen(false); toast("استوری ذخیره شد");
    } catch (error) { toast((error as Error).message || "ذخیره استوری انجام نشد", false); } finally { setBusy(false); }
  };
  const archive = async (story: Story) => {
    if (!window.confirm(`استوری «${story.title}» بایگانی شود؟`)) return;
    try { await api(`/api/admin/stories/${story.id}`, "DELETE", {}); setRows((old) => old.map((item) => item.id === story.id ? { ...item, status: "archived" } : item)); toast("استوری بایگانی شد"); }
    catch (error) { toast((error as Error).message, false); }
  };
  const selected = (id: number) => products.find((product) => product.id === id);

  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><label className="relative min-w-56 flex-1 sm:max-w-sm"><Search className="absolute right-3 top-2.5 size-4 text-slate-400"/><input className="input pr-9" placeholder="جست‌وجوی استوری یا محصول" value={query} onChange={(event) => setQuery(event.target.value)}/></label><button onClick={() => start()} className="btn-primary"><Plus className="size-4"/>استوری جدید</button></div>
    {filtered.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((story) => <article key={story.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="relative aspect-[9/5] bg-slate-950">{story.mediaType === "image" ? <Img id={story.mediaId} alt={story.title} className="size-full object-cover"/> : <video src={`/api/media/${story.mediaId}`} preload="metadata" className="size-full object-cover"/>}<span className="absolute right-3 top-3"><Badge tone={story.status === "published" ? "green" : story.status === "archived" ? "gray" : "amber"}>{story.status === "published" ? "منتشر" : story.status === "archived" ? "بایگانی" : "پیش‌نویس"}</Badge></span><span className="absolute left-3 top-3 rounded-full bg-black/50 p-2 text-white">{story.mediaType === "video" ? <Film className="size-4"/> : <span className="text-sm">تصویر</span>}</span></div><div className="p-4"><h2 className="font-black">{story.title}</h2>{story.caption && <p className="mt-1 line-clamp-2 text-sm leading-6 text-slate-500">{story.caption}</p>}{story.productName && <p className="mt-2 flex items-center gap-1 text-xs text-emerald-700"><Link2 className="size-3.5"/>محصول: {story.productName}</p>}<div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-slate-500"><span className="flex items-center gap-1"><Eye className="size-3.5"/>{story.viewCount.toLocaleString("fa-IR")}</span><span className="flex items-center gap-1"><Heart className="size-3.5"/>{story.likeCount.toLocaleString("fa-IR")}</span>{story.startsAt && <span className="flex items-center gap-1"><CalendarClock className="size-3.5"/>{new Intl.DateTimeFormat("fa-IR", { timeZone: "Asia/Tehran", dateStyle: "short", timeStyle: "short" }).format(new Date(story.startsAt))}</span>}</div><div className="mt-4 flex gap-2 border-t pt-3"><button onClick={() => start(story)} className="btn-sm"><Pencil className="size-3.5"/>ویرایش</button>{story.status !== "archived" && <button onClick={() => void archive(story)} className="btn-sm text-rose-600"><Trash2 className="size-3.5"/>بایگانی</button>}</div></div></article>)}</div> : <div className="rounded-2xl border border-dashed p-10 text-center text-sm text-slate-500">استوری‌ای با این مشخصات وجود ندارد.</div>}
    {open && <Modal title={editing ? "ویرایش استوری" : "استوری جدید"} onClose={() => { if (!busy) setOpen(false); }} wide><form onSubmit={save} className="space-y-5">
      <section className="grid gap-4 rounded-2xl border bg-white p-4 sm:grid-cols-2"><label className="text-sm font-bold sm:col-span-2">عنوان<input required minLength={2} maxLength={100} className="input mt-1" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })}/></label><label className="text-sm font-bold sm:col-span-2">متن کوتاه<textarea rows={3} maxLength={500} className="input mt-1 leading-6" value={draft.caption} onChange={(event) => setDraft({ ...draft, caption: event.target.value })}/></label><label className="text-sm font-bold">نوع رسانه<select className="input mt-1" value={draft.mediaType} onChange={(event) => setDraft({ ...draft, mediaType: event.target.value as Draft["mediaType"], mediaId: null })}><option value="image">تصویر</option><option value="video">ویدیو</option></select></label><label className="text-sm font-bold">وضعیت<select className="input mt-1" value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as Draft["status"] })}><option value="draft">پیش‌نویس</option><option value="published">انتشار (طبق زمان‌بندی)</option></select></label></section>
      {draft.mediaType === "image" ? <section className="rounded-2xl border bg-white p-4"><b className="mb-2 block text-sm">رسانهٔ تصویری</b><ImageUploader value={draft.mediaId ? [draft.mediaId] : []} max={1} onChange={(ids) => setDraft({ ...draft, mediaId: ids[0] ?? null })}/><p className="mt-2 text-xs text-slate-400">تصویر از دستگاه یا مرکز فایل انتخاب کنید؛ فایل پس از انتشار به‌صورت عمومی نمایش داده می‌شود.</p></section> : <VideoUploader value={draft.mediaId} onChange={(id) => setDraft({ ...draft, mediaId: id })} kind="video" label="ویدیوی استوری (MP4 یا WebM، تا ۴۰ مگابایت)"/>}
      <section className="space-y-3 rounded-2xl border bg-white p-4"><div><h3 className="font-black">محصول یا پیوند اقدام</h3><p className="mt-1 text-xs text-slate-500">می‌توانید محصول را پیوند دهید یا نشانی مستقلی برای دکمه وارد کنید.</p></div><div className="flex flex-wrap items-center gap-2">{selectedProduct ? <span className="flex items-center gap-2 rounded-xl bg-emerald-50 p-2 text-sm text-emerald-800">{selectedProduct.mainImageId && <Img id={selectedProduct.mainImageId} alt="" className="size-10 rounded-lg object-cover"/>}<span>{selectedProduct.nameFa}<small className="block text-xs">{selectedProduct.brand}</small></span><button type="button" onClick={() => setDraft({ ...draft, productId: null })} className="mr-2 text-rose-600">حذف</button></span> : <button type="button" onClick={() => { setProductQuery(""); setProductModal(true); }} className="btn-sm"><Search className="size-4"/>انتخاب محصول</button>}</div><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">پیوند اختیاری<input dir="ltr" type="url" placeholder="https://… یا /shop" className="input mt-1 text-left" value={draft.href} onChange={(event) => setDraft({ ...draft, href: event.target.value })}/></label><label className="text-sm">متن دکمه<input maxLength={40} className="input mt-1" value={draft.ctaLabel} onChange={(event) => setDraft({ ...draft, ctaLabel: event.target.value })}/></label></div></section>
      <section className="grid gap-4 rounded-2xl border bg-white p-4 sm:grid-cols-2"><div className="space-y-2"><b className="block text-sm">زمان شروع · تقویم شمسی</b><JalaliDatePicker value={draft.startsOn} onChange={(startsOn) => setDraft({ ...draft, startsOn })} allowEmpty placeholder="انتشار فوری"/><label className="block text-xs text-slate-500">ساعت تهران<input type="time" className="input mt-1" value={draft.startsTime} onChange={(event) => setDraft({ ...draft, startsTime: event.target.value })}/></label></div><div className="space-y-2"><b className="block text-sm">زمان پایان · اختیاری</b><JalaliDatePicker value={draft.endsOn} onChange={(endsOn) => setDraft({ ...draft, endsOn })} allowEmpty placeholder="بدون انقضای زمان‌بندی‌شده"/><label className="block text-xs text-slate-500">ساعت تهران<input type="time" className="input mt-1" value={draft.endsTime} onChange={(event) => setDraft({ ...draft, endsTime: event.target.value })}/></label></div><label className="text-sm">ترتیب نمایش<input type="number" min={0} max={10000} className="input mt-1" value={draft.sortOrder} onChange={(event) => setDraft({ ...draft, sortOrder: Number(event.target.value) || 0 })}/></label></section>
      <div className="flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="btn-ghost">انصراف</button><button disabled={busy} className="btn-primary">{busy ? "در حال ذخیره…" : "ذخیره استوری"}</button></div>
    </form></Modal>}
    {productModal && <Modal title="انتخاب محصول استوری" onClose={() => setProductModal(false)}><div className="space-y-3"><label className="relative block"><Search className="absolute right-3 top-2.5 size-4 text-slate-400"/><input autoFocus className="input pr-9" placeholder="جست‌وجو بر اساس نام یا برند" value={productQuery} onChange={(event) => setProductQuery(event.target.value)}/></label><div className="max-h-[55vh] space-y-1 overflow-y-auto">{filteredProducts.map((product) => <button type="button" key={product.id} onClick={() => { setDraft({ ...draft, productId: product.id }); setProductModal(false); }} className="flex w-full items-center gap-3 rounded-xl p-2 text-right hover:bg-emerald-50">{product.mainImageId ? <Img id={product.mainImageId} alt="" className="size-11 rounded-lg object-cover"/> : <span className="grid size-11 place-items-center rounded-lg bg-emerald-50">🌿</span>}<span className="min-w-0"><b className="block truncate text-sm">{product.nameFa}</b><small className="text-xs text-slate-500">{product.brand}</small></span></button>)}{!filteredProducts.length && <p className="p-5 text-center text-sm text-slate-500">محصولی پیدا نشد.</p>}</div></div></Modal>}
  </div>;
}
